package com.workflow.client.naf.validate; 

public class BrokerControlImpl extends PassListBase {

	// Field sizes
    public static final int BROKER_CONTROL_SIZE                      = 1000; // offset -           0
    public static final int COMPANY_NO_SIZE                          = 2;    // offset -        0
    public static final int DIVISION_NO_SIZE                         = 4;    // offset -        2
    public static final int IMPORT_DIVISION_SIZE                     = 1;    // offset -        6
    public static final int EXPORT_DIVISION_SIZE                     = 1;    // offset -        7
    public static final int NAME_SIZE                                = 35;   // offset -         8
    public static final int ADDRESS_1_SIZE                           = 35;   // offset -        43
    public static final int ADDRESS_2_SIZE                           = 35;   // offset -        78
    public static final int CITY_SIZE                                = 35;   // offset -       113
    public static final int STATE_PROVINCE_SIZE                      = 2;    // offset -      148
    public static final int ZIP_SIZE                                 = 9;    // offset -      150
    public static final int PHONE_NO_ALPHA_SIZE                      = 15;   // offset -       159
    public static final int FAX_NO_ALPHA_SIZE                        = 15;   // offset -       174
    public static final int DIST_PORT_SIZE                           = 4;    // offset -      189
    public static final int ENTRY_TYPE_SIZE                          = 2;    // offset -      193
    public static final int MOT_SIZE                                 = 2;    // offset -      195
    public static final int TIME_UPDATED_SIZE                        = 4;    // offset -      197
    public static final int DATE_UPDATED_SIZE                        = 8;    // offset -      201
    public static final int MODIFIED_BY_SIZE                         = 12;   // offset -       209
    public static final int FOREIGN_CO_SIZE                          = 1;    // offset -      221
    public static final int ACH_PAYER_UNIT_SIZE                      = 6;    // offset -      222
    public static final int DUE_DATE_SIZE                            = 1;    // offset -      228
    public static final int OTHER_COUNTRIES_01_SIZE                  = 2;    // offset - 4     229
    public static final int OTHER_COUNTRIES_02_SIZE                  = 2;    // offset - 4     231
    public static final int OTHER_COUNTRIES_03_SIZE                  = 2;    // offset - 4     233
    public static final int OTHER_COUNTRIES_04_SIZE                  = 2;    // offset - 4     235
    public static final int PROFILE_COMP_SIZE                        = 2;    // offset -      237
    public static final int NUMBER_COMP_SIZE                         = 2;    // offset -      239
    public static final int NUMBER_DIV_SIZE                          = 4;    // offset -      241
    public static final int FREIGHT_PAY_SIZE                         = 1;    // offset -      245
    public static final int FRT_PAY_RATE_SIZE                        = 2;    // offset -      246
    public static final int REVRPT_WHOLE_DOLLAR_SIZE                 = 1;    // offset -      248
    public static final int BILLTO_PROF_SIZE                         = 1;    // offset -      249
    public static final int AUTO_SED_SIZE                            = 1;    // offset -      250
    public static final int FRT_PAY_NUMB_SIZE                        = 6;    // offset -      251
    public static final int ACH_SIZE                                 = 1;    // offset -      257
    public static final int REVRPT_SING_COMP_SIZE                    = 1;    // offset -      258
    public static final int REVRPT_ORIG_BILS_SIZE                    = 1;    // offset -      259
    public static final int FAX_TYPE_SIZE                            = 1;    // offset -      260
    public static final int EUROPEAN_DATE_SIZE                       = 1;    // offset -      261
    public static final int ACCT_COMP_SIZE                           = 2;    // offset -      262
    public static final int FMC_NUMB_SIZE                            = 5;    // offset -      264
    public static final int INTEREST_COMPUTED_SIZE                   = 1;    // offset -      269
    public static final int INVCE_TRAN_DATE_SIZE                     = 1;    // offset -      270
    public static final int TRACE_EXCLUDE_SIZE                       = 1;    // offset -      271
    public static final int INQALL_MULTI_CO_SIZE                     = 1;    // offset -      272
    public static final int SIGNATURE_SIZE                           = 35;   // offset -       273
    public static final int PASSWORD_CREDIT_CHECK_SIZE               = 6;    // offset -      308
    public static final int PASSWORD_CHECK_NAME_SIZE                 = 6;    // offset -      314
    public static final int FILE_NO_SIZE                             = 10;   // offset -       320
    public static final int BANK_NO_SIZE                             = 2;    // offset -      330
    public static final int ENIC_CUSTOMERS_SIZE                      = 1;    // offset -      332
    public static final int BOND_AMT_SIZE                            = 11;   // offset -       333
    public static final int PASSWORD_SHIP_ID_SIZE                    = 6;    // offset -      344
    public static final int ABI_BROKER_SIZE                          = 1;    // offset -      350
    public static final int ABI_LIVE_ES_SIZE                         = 1;    // offset -      351
    public static final int ENTRY_NO_SIZE                            = 9;    // offset -      352
    public static final int FILE_AS_ENTRY_SIZE                       = 1;    // offset -      361
    public static final int INFORMAL_LIMIT_SIZE                      = 8;    // offset -      362
    public static final int PREVIOUS_INFORMAL_LIMIT_SIZE             = 8;    // offset -      370
    public static final int INFORMAL_LIMIT_EFFECTIVE_DATE_SIZE       = 8;    // offset -      378
    public static final int RET_US_GOODS_INFORMAL_LIMIT_SIZE         = 8;    // offset -      386
    public static final int BROKER_FILER_SIZE                        = 3;    // offset -      394
    public static final int WEIGHT_PERCENTAGE_SIZE                   = 4;    // offset -      397
    public static final int WEIGHT_VARIANCE_SIZE                     = 4;    // offset -      401
    public static final int VALUE_LIMIT_SIZE                         = 8;    // offset -      405
    public static final int QTY_LIMIT_SIZE                           = 8;    // offset -      413
    public static final int LINE_VALUE_LIMIT_SIZE                    = 11;   // offset -       421
    public static final int CHARGES_LIMIT_AIR_SIZE                   = 11;   // offset -       432
    public static final int CHARGES_LIMIT_OCEAN_SIZE                 = 11;   // offset -       443
    public static final int WEIGHT_LIMIT_AIR_SIZE                    = 12;   // offset -       454
    public static final int WEIGHT_LIMIT_OCEAN_SIZE                  = 12;   // offset -       466
    public static final int DUTY_OVERRIDE_SIZE                       = 12;   // offset -       478
    public static final int VIRGIN_ISLANDS_SIZE                      = 1;    // offset -      490
    public static final int ORIGIN_STATION_SIZE                      = 3;    // offset -      491
    public static final int AGENTS_IATA_CODE_SIZE                    = 9;    // offset -      494
    public static final int COUNTRY_SIZE                             = 2;    // offset -      503
    public static final int PROFIT_SHARE_CHARGE_SIZE                 = 4;    // offset -      505
    public static final int ALLOC_FREIGHT_COST_CHRG_SIZE             = 4;    // offset -      509
    public static final int ALLOCATED_PROFIT_SHARE_CHARGE_SIZE       = 4;    // offset -      513
    public static final int T_C_LOG_FLAG_SIZE                        = 1;    // offset -      517
    public static final int BB_OCEAN_FORM_SIZE                       = 5;    // offset -      518
    public static final int BB_AIR_FORM_SIZE                         = 5;    // offset -      523
    public static final int CARGO_RELEASE_ENTRY_SUMM_SIZE            = 1;    // offset -      528
    public static final int CUSTOM_FIELDS_SIZE                       = 1;    // offset -      529
    public static final int ALLOC_NON_FREIGHT_COST_CHRG_SIZE         = 4;    // offset -      530
    public static final int ADJ_FRT_PROFIT_CHARGE_SIZE               = 4;    // offset -      534
    public static final int ADJ_NON_FRT_PROFIT_CHARGE_SIZE           = 4;    // offset -      538
    public static final int MESSAGE_NO_FOR_INVOICE_2_SIZE            = 4;    // offset -      542
    public static final int PAYMENT_DUE_BASIS_SIZE                   = 5;    // offset -      546
    public static final int PAYMENT_DUE_RESEND_SIZE                  = 1;    // offset -      551
    public static final int PAYMENT_DUE_RECALC_SIZE                  = 1;    // offset -      552
    public static final int VERIFY_FILE_NO_SIZE                      = 1;    // offset -      553
    public static final int ALLOW_PRELOAD_SIZE                       = 1;    // offset -      554
    public static final int CONTAINER_DATES_NOTES_SIZE               = 1;    // offset -      555
    public static final int DEFAULT_PORT_ENTRY_SIZE                  = 1;    // offset -      556
    public static final int PRINT_TEAM_CUSTOMER_SIZE                 = 1;    // offset -      557
    public static final int CRDCK_SIZE                               = 1;    // offset -      558
    public static final int SECONDARY_CHECK_DIGIT_SIZE               = 1;    // offset -      559
    public static final int CREDIT_REQUIRES_DEBIT_SIZE               = 1;    // offset -      560
    public static final int VENDOR_REF_LENGTH_SIZE                   = 2;    // offset -      561
    public static final int ENTER_CI_COUNT_SIZE                      = 1;    // offset -      563
    public static final int DEFAULT_CR_ES_SIZE                       = 1;    // offset -      564
    public static final int FILE_PREFIX_SIZE                         = 2;    // offset -      565
    public static final int ALLOW_MANUAL_SUFFIX_SIZE                 = 1;    // offset -      567
    public static final int FILLER_1_SIZE                            = 2;    // offset -      568
    public static final int ALPH_NUM_SUFX_SIZE                       = 1;    // offset -      570
    public static final int SWL_X_DAYS_SIZE                          = 2;    // offset -      571
    public static final int ACH_LOCK_SIZE                            = 1;    // offset -      573
    public static final int DETERMINE_NAFTA_APTA_SIZE                = 1;    // offset -      574
    public static final int APTA_END_USE_SIZE                        = 1;    // offset -      575
    public static final int BIRD_SIZE                                = 1;    // offset -      576
    public static final int REMOTE_PRINT_SIZE                        = 1;    // offset -      577
    public static final int UOM_PIECES_SIZE                          = 6;    // offset -      578
    public static final int TRACING_EXTRACT_MASTER_CUST_SIZE         = 10;   // offset -       584
    public static final int AEI_EXTRACT_SIZE                         = 1;    // offset -      594
    public static final int ZERO_BILLS_SIZE                          = 1;    // offset -      595
    public static final int CONTROL_PIECES_FLAG_SIZE                 = 1;    // offset -      596
    public static final int CONTROL_VOLUME_FLAG_SIZE                 = 1;    // offset -      597
    public static final int CONTROL_WEIGHT_FLAG_SIZE                 = 1;    // offset -      598
    public static final int CONTROL_COLLECT_FLAG_SIZE                = 1;    // offset -      599
    public static final int CONTROL_PREPAID_FLAG_SIZE                = 1;    // offset -      600
    public static final int SUBSIDIARY_LEDGER_GL_SIZE                = 8;    // offset -      601
    public static final int ORIGINAL_BILL_SUFFIX_SIZE                = 2;    // offset -      609
    public static final int NOT_REC_AUTO_FAX_TEL_SIZE                = 1;    // offset -      611
    public static final int ABI_LIVE_CR_SIZE                         = 1;    // offset -      612
    public static final int CHARGE_VARIANCE_SIZE                     = 4;    // offset -      613
    public static final int CUSTOMS_PRIORITY_SIZE                    = 1;    // offset -      617
    public static final int BOND_TYPE_SIZE                           = 1;    // offset -      618
    public static final int BOND_SURETY_SIZE                         = 3;    // offset -      619
    public static final int IRS_NO_SIZE                              = 12;   // offset -       622
    public static final int REMIT_TO_ADDRESS_1_SIZE                  = 30;   // offset -       634
    public static final int REMIT_TO_ADDRESS_2_SIZE                  = 30;   // offset -       664
    public static final int REMIT_TO_ADDRESS_3_SIZE                  = 30;   // offset -       694
    public static final int STATEMENTS_SIZE                          = 1;    // offset -      724
    public static final int ANNUAL_INTEREST_RATE_SIZE                = 4;    // offset -      725
    public static final int INTEREST_CHARGE_CODE_SIZE                = 4;    // offset -      729
    public static final int DEDUCT_CHARGE_CODE_SIZE                  = 4;    // offset -      733
    public static final int AH_INTEREST_DEDUCT_MESS_SIZE             = 1;    // offset -      737
    public static final int INTEREST_DAYS_FOR_INVOICE_SIZE           = 3;    // offset -      738
    public static final int INVOICE_SUB_TOTAL_SIZE                   = 1;    // offset -      741
    public static final int CREDIT_MEMO_COLUMN_SIZE                  = 3;    // offset -      742
    public static final int CREDIT_MEMO_HIGH_SIZE                    = 1;    // offset -      745
    public static final int INDENT_CHG_99_SIZE                       = 1;    // offset -      746
    public static final int MESSAGE_NO_FOR_INVOICE_SIZE              = 4;    // offset -      747
    public static final int INVOICE_VENDOR_SIZE                      = 1;    // offset -      751
    public static final int INVOICE_REMIT_TO_SIZE                    = 1;    // offset -      752
    public static final int INVOICE_REMIT_TO_COL_SIZE                = 3;    // offset -      753
    public static final int INVOICE_REMIT_TO_ROW_SIZE                = 3;    // offset -      756
    public static final int INVOICE_DUTY_FEES_HEAD_SIZE              = 35;   // offset -       759
    public static final int STATEMENT_DIST_PORT_DEF_SIZE             = 4;    // offset -      794
    public static final int COPIES_7501_SIZE                         = 2;    // offset -      798
    public static final int DEFAULT_STOP_SIZE                        = 1;    // offset -      800
    public static final int MERCH_PURCHASED_SIZE                     = 1;    // offset -      801
    public static final int IMP_OR_OWNER_SIZE                        = 1;    // offset -      802
    public static final int FWS_SIZE                                 = 1;    // offset -      803
    public static final int SQUEEZE_FLAG_SIZE                        = 1;    // offset -      804
    public static final int FCC_SIZE                                 = 1;    // offset -      805
    public static final int FDA_SIZE                                 = 1;    // offset -      806
    public static final int MESSAGE_3461_1_SIZE                      = 4;    // offset -      807
    public static final int MESSAGE_3461_2_SIZE                      = 4;    // offset -      811
    public static final int MESSAGE_3461_3_SIZE                      = 4;    // offset -      815
    public static final int PRO_RATE_WEIGHT_SIZE                     = 1;    // offset -      819
    public static final int PRO_RATE_CHARGES_SIZE                    = 1;    // offset -      820
    public static final int F7501_X_MOVE_SIZE                        = 1;    // offset -      821
    public static final int PAYDATE_DIV_SIZE                         = 1;    // offset -      822
    public static final int CHECK_SHIP_ID_SIZE                       = 1;    // offset -      823
    public static final int SEB_AUTO_CHAIN_SIZE                      = 1;    // offset -      824
    public static final int CREDIT_CASH_POSITION_SIZE                = 1;    // offset -      825
    public static final int ENHANCED_INVOICE_SIZE                    = 1;    // offset -      826
    public static final int LANDED_COST_SIZE                         = 1;    // offset -      827
    public static final int BREAK_BULK_AGENT_FLAG_SIZE               = 1;    // offset -      828
    public static final int CHSPFILE_MODE_SIZE                       = 1;    // offset -      829
    public static final int DO_NAME_ADDRESS_SIZE                     = 1;    // offset -      830
    public static final int ALLOW_MULTIPLE_ADDRESSES_SIZE            = 1;    // offset -      831
    public static final int DIST_PORT_UNLADING_SIZE                  = 4;    // offset -      832
    public static final int LOADING_SHEET_NAME_ADDRESS_SIZE          = 1;    // offset -      836
    public static final int NEXT_ENTRY_NUMBER_LIST_SIZE              = 9;    // offset -      837
    public static final int POWERHOUSE_ACCT_SIZE                     = 1;    // offset -      846
    public static final int NEXT_CUSTOMER_SIZE                       = 10;   // offset -       847
    public static final int PASSWORD_CUST_SIZE                       = 6;    // offset -      857
    public static final int BORDER_SIZE                              = 1;    // offset -      863
    public static final int COPIES_3461_SIZE                         = 2;    // offset -      864
    public static final int LAST_ENTRY_NO_SIZE                       = 9;    // offset -      866
    public static final int BROKERS_BOND_DIV_0_SIZE                  = 1;    // offset -      875
    public static final int COUNTRY_EXPORT_SIZE                      = 2;    // offset -      876
    public static final int CERTIFICATION_ES_SIZE                    = 1;    // offset -      878
    public static final int AUTO_BILL_SIZE                           = 1;    // offset -      879
    public static final int PAPERLESS_ES_SIZE                        = 1;    // offset -      880
    public static final int HOLD_7501_SIZE                           = 1;    // offset -      881
    public static final int BROKERAGE_CHARGE_SIZE                    = 4;    // offset -      882
    public static final int NEXT_SUMM_BILL_NO_SIZE                   = 10;   // offset -       886
    public static final int PRINT_TEAM_DIV_SIZE                      = 1;    // offset -      896
    public static final int INVCE_SKIP_LINE_SIZE                     = 1;    // offset -      897
    public static final int DO_ID_COMBO_FORM_SIZE                    = 1;    // offset -      898
    public static final int DOT_SIZE                                 = 1;    // offset -      899
    public static final int NEXT_VENDOR_SIZE                         = 10;   // offset -       900
    public static final int CUSTOM_1_SIZE                            = 1;    // offset -      910
    public static final int CUSTOM_2_SIZE                            = 1;    // offset -      911
    public static final int CUST_SHIPMENT_HEADER_SIZE                = 1;    // offset -      912
    public static final int CUSTOM_4_SIZE                            = 1;    // offset -      913
    public static final int CUSTOM_5_SIZE                            = 1;    // offset -      914
    public static final int CUSTOM_6_SIZE                            = 1;    // offset -      915
    public static final int CUSTOM_7_SIZE                            = 1;    // offset -      916
    public static final int CUSTOM_8_SIZE                            = 1;    // offset -      917
    public static final int CUSTOM_9_SIZE                            = 1;    // offset -      918
    public static final int CUSTOM_10_SIZE                           = 1;    // offset -      919
    public static final int SEB_PROD_ACCOUNT_SIZE                    = 7;    // offset -      920
    public static final int NEXT_IT_NO_SIZE                          = 9;    // offset -      927
    public static final int OPTIONS_3461_SIZE                        = 1;    // offset -      936
    public static final int REMIT_TO_ADDRESS_4_SIZE                  = 30;   // offset -       937
    public static final int DIV_FOR_NEXT_FILE_SIZE                   = 4;    // offset -      967
    public static final int LOCATION_SIZE                            = 4;    // offset -      971
    public static final int CURRENCY_SIZE                            = 3;    // offset -      975
    public static final int UOM_VOLUME_SIZE                          = 6;    // offset -      978
    public static final int UOM_WEIGHT_SIZE                          = 6;    // offset -      984
    public static final int MESSAGE_NO_SIZE                          = 4;    // offset -      990
    public static final int BREAK_BULK_DIV_FLAG_SIZE                 = 1;    // offset -      994
    public static final int ALLOW_PREPAIDS_SIZE                      = 1;    // offset -      995
    public static final int PART_NOTES_SIZE                          = 1;    // offset -      996
    public static final int ENHANCED_CONTAINERS_SIZE                 = 1;    // offset -      997
    public static final int CR_TO_ES_SIZE                            = 1;    // offset -      998
    public static final int DELETE_FLAG_SIZE                         = 1;    // offset -      999

	// Array offsets
    public static final int BROKER_CONTROL_OFFSET                      = 0;
    public static final int COMPANY_NO_OFFSET                          = 0;
    public static final int DIVISION_NO_OFFSET                         = 2;
    public static final int IMPORT_DIVISION_OFFSET                     = 6;
    public static final int EXPORT_DIVISION_OFFSET                     = 7;
    public static final int NAME_OFFSET                                = 8;
    public static final int ADDRESS_1_OFFSET                           = 43;
    public static final int ADDRESS_2_OFFSET                           = 78;
    public static final int CITY_OFFSET                                = 113;
    public static final int STATE_PROVINCE_OFFSET                      = 148;
    public static final int ZIP_OFFSET                                 = 150;
    public static final int PHONE_NO_ALPHA_OFFSET                      = 159;
    public static final int FAX_NO_ALPHA_OFFSET                        = 174;
    public static final int DIST_PORT_OFFSET                           = 189;
    public static final int ENTRY_TYPE_OFFSET                          = 193;    
    public static final int MOT_OFFSET                                 = 195;     
    public static final int TIME_UPDATED_OFFSET                        = 197;     
    public static final int DATE_UPDATED_OFFSET                        = 201;     
    public static final int MODIFIED_BY_OFFSET                         = 209;     
    public static final int FOREIGN_CO_OFFSET                          = 221;     
    public static final int ACH_PAYER_UNIT_OFFSET                      = 222;     
    public static final int DUE_DATE_OFFSET                            = 228;     
    public static final int OTHER_COUNTRIES_01_OFFSET                  = 229;    
    public static final int OTHER_COUNTRIES_02_OFFSET                  = 231;     
    public static final int OTHER_COUNTRIES_03_OFFSET                  = 233;     
    public static final int OTHER_COUNTRIES_04_OFFSET                  = 235;   
    public static final int PROFILE_COMP_OFFSET                        = 237;     
    public static final int NUMBER_COMP_OFFSET                         = 239;     
    public static final int NUMBER_DIV_OFFSET                          = 241;     
    public static final int FREIGHT_PAY_OFFSET                         = 245;     
    public static final int FRT_PAY_RATE_OFFSET                        = 246;     
    public static final int REVRPT_WHOLE_DOLLAR_OFFSET                 = 248;     
    public static final int BILLTO_PROF_OFFSET                         = 249;     
    public static final int AUTO_SED_OFFSET                            = 250;     
    public static final int FRT_PAY_NUMB_OFFSET                        = 251;     
    public static final int ACH_OFFSET                                 = 257;     
    public static final int REVRPT_SING_COMP_OFFSET                    = 258;     
    public static final int REVRPT_ORIG_BILS_OFFSET                    = 259;     
    public static final int FAX_TYPE_OFFSET                            = 260;     
    public static final int EUROPEAN_DATE_OFFSET                       = 261;     
    public static final int ACCT_COMP_OFFSET                           = 262;     
    public static final int FMC_NUMB_OFFSET                            = 264;     
    public static final int INTEREST_COMPUTED_OFFSET                   = 269;     
    public static final int INVCE_TRAN_DATE_OFFSET                     = 270;     
    public static final int TRACE_EXCLUDE_OFFSET                       = 271;     
    public static final int INQALL_MULTI_CO_OFFSET                     = 272;     
    public static final int SIGNATURE_OFFSET                           = 273;     
    public static final int PASSWORD_CREDIT_CHECK_OFFSET               = 308;     
    public static final int PASSWORD_CHECK_NAME_OFFSET                 = 314;     
    public static final int FILE_NO_OFFSET                             = 320;     
    public static final int BANK_NO_OFFSET                             = 330;     
    public static final int ENIC_CUSTOMERS_OFFSET                      = 332;     
    public static final int BOND_AMT_OFFSET                            = 333;     
    public static final int PASSWORD_SHIP_ID_OFFSET                    = 344;     
    public static final int ABI_BROKER_OFFSET                          = 350;     
    public static final int ABI_LIVE_ES_OFFSET                         = 351;     
    public static final int ENTRY_NO_OFFSET                            = 352;     
    public static final int FILE_AS_ENTRY_OFFSET                       = 361;     
    public static final int INFORMAL_LIMIT_OFFSET                      = 362;     
    public static final int PREVIOUS_INFORMAL_LIMIT_OFFSET             = 370;     
    public static final int INFORMAL_LIMIT_EFFECTIVE_DATE_OFFSET       = 378;     
    public static final int RET_US_GOODS_INFORMAL_LIMIT_OFFSET         = 386;     
    public static final int BROKER_FILER_OFFSET                        = 394;     
    public static final int WEIGHT_PERCENTAGE_OFFSET                   = 397;     
    public static final int WEIGHT_VARIANCE_OFFSET                     = 401;     
    public static final int VALUE_LIMIT_OFFSET                         = 405;     
    public static final int QTY_LIMIT_OFFSET                           = 413;     
    public static final int LINE_VALUE_LIMIT_OFFSET                    = 421;     
    public static final int CHARGES_LIMIT_AIR_OFFSET                   = 432;     
    public static final int CHARGES_LIMIT_OCEAN_OFFSET                 = 443;     
    public static final int WEIGHT_LIMIT_AIR_OFFSET                    = 454;     
    public static final int WEIGHT_LIMIT_OCEAN_OFFSET                  = 466;     
    public static final int DUTY_OVERRIDE_OFFSET                       = 478;     
    public static final int VIRGIN_ISLANDS_OFFSET                      = 490;     
    public static final int ORIGIN_STATION_OFFSET                      = 491;     
    public static final int AGENTS_IATA_CODE_OFFSET                    = 494;     
    public static final int COUNTRY_OFFSET                             = 503;     
    public static final int PROFIT_SHARE_CHARGE_OFFSET                 = 505;     
    public static final int ALLOC_FREIGHT_COST_CHRG_OFFSET             = 509;     
    public static final int ALLOCATED_PROFIT_SHARE_CHARGE_OFFSET       = 513;     
    public static final int T_C_LOG_FLAG_OFFSET                        = 517;     
    public static final int BB_OCEAN_FORM_OFFSET                       = 518;     
    public static final int BB_AIR_FORM_OFFSET                         = 523;     
    public static final int CARGO_RELEASE_ENTRY_SUMM_OFFSET            = 528;     
    public static final int CUSTOM_FIELDS_OFFSET                       = 529;     
    public static final int ALLOC_NON_FREIGHT_COST_CHRG_OFFSET         = 530;     
    public static final int ADJ_FRT_PROFIT_CHARGE_OFFSET               = 534;     
    public static final int ADJ_NON_FRT_PROFIT_CHARGE_OFFSET           = 538;     
    public static final int MESSAGE_NO_FOR_INVOICE_2_OFFSET            = 542;     
    public static final int PAYMENT_DUE_BASIS_OFFSET                   = 546;     
    public static final int PAYMENT_DUE_RESEND_OFFSET                  = 551;     
    public static final int PAYMENT_DUE_RECALC_OFFSET                  = 552;     
    public static final int VERIFY_FILE_NO_OFFSET                      = 553;     
    public static final int ALLOW_PRELOAD_OFFSET                       = 554;     
    public static final int CONTAINER_DATES_NOTES_OFFSET               = 555;     
    public static final int DEFAULT_PORT_ENTRY_OFFSET                  = 556;     
    public static final int PRINT_TEAM_CUSTOMER_OFFSET                 = 557;     
    public static final int CRDCK_OFFSET                               = 558;     
    public static final int SECONDARY_CHECK_DIGIT_OFFSET               = 559;     
    public static final int CREDIT_REQUIRES_DEBIT_OFFSET               = 560;     
    public static final int VENDOR_REF_LENGTH_OFFSET                   = 561;     
    public static final int ENTER_CI_COUNT_OFFSET                      = 563;     
    public static final int DEFAULT_CR_ES_OFFSET                       = 564;     
    public static final int FILE_PREFIX_OFFSET                         = 565;     
    public static final int ALLOW_MANUAL_SUFFIX_OFFSET                 = 567;     
    public static final int FILLER_1_OFFSET                            = 568;     
    public static final int ALPH_NUM_SUFX_OFFSET                       = 570;     
    public static final int SWL_X_DAYS_OFFSET                          = 571;     
    public static final int ACH_LOCK_OFFSET                            = 573;     
    public static final int DETERMINE_NAFTA_APTA_OFFSET                = 574;     
    public static final int APTA_END_USE_OFFSET                        = 575;     
    public static final int BIRD_OFFSET                                = 576;     
    public static final int REMOTE_PRINT_OFFSET                        = 577;     
    public static final int UOM_PIECES_OFFSET                          = 578;     
    public static final int TRACING_EXTRACT_MASTER_CUST_OFFSET         = 584;     
    public static final int AEI_EXTRACT_OFFSET                         = 594;     
    public static final int ZERO_BILLS_OFFSET                          = 595;     
    public static final int CONTROL_PIECES_FLAG_OFFSET                 = 596;     
    public static final int CONTROL_VOLUME_FLAG_OFFSET                 = 597;     
    public static final int CONTROL_WEIGHT_FLAG_OFFSET                 = 598;     
    public static final int CONTROL_COLLECT_FLAG_OFFSET                = 599;     
    public static final int CONTROL_PREPAID_FLAG_OFFSET                = 600;     
    public static final int SUBSIDIARY_LEDGER_GL_OFFSET                = 601;     
    public static final int ORIGINAL_BILL_SUFFIX_OFFSET                = 609;     
    public static final int NOT_REC_AUTO_FAX_TEL_OFFSET                = 611;     
    public static final int ABI_LIVE_CR_OFFSET                         = 612;     
    public static final int CHARGE_VARIANCE_OFFSET                     = 613;     
    public static final int CUSTOMS_PRIORITY_OFFSET                    = 617;     
    public static final int BOND_TYPE_OFFSET                           = 618;     
    public static final int BOND_SURETY_OFFSET                         = 619;     
    public static final int IRS_NO_OFFSET                              = 622;     
    public static final int REMIT_TO_ADDRESS_1_OFFSET                  = 634;     
    public static final int REMIT_TO_ADDRESS_2_OFFSET                  = 664;     
    public static final int REMIT_TO_ADDRESS_3_OFFSET                  = 694;     
    public static final int STATEMENTS_OFFSET                          = 724;     
    public static final int ANNUAL_INTEREST_RATE_OFFSET                = 725;     
    public static final int INTEREST_CHARGE_CODE_OFFSET                = 729;     
    public static final int DEDUCT_CHARGE_CODE_OFFSET                  = 733;     
    public static final int AH_INTEREST_DEDUCT_MESS_OFFSET             = 737;     
    public static final int INTEREST_DAYS_FOR_INVOICE_OFFSET           = 738;     
    public static final int INVOICE_SUB_TOTAL_OFFSET                   = 741;     
    public static final int CREDIT_MEMO_COLUMN_OFFSET                  = 742;     
    public static final int CREDIT_MEMO_HIGH_OFFSET                    = 745;     
    public static final int INDENT_CHG_99_OFFSET                       = 746;     
    public static final int MESSAGE_NO_FOR_INVOICE_OFFSET              = 747;     
    public static final int INVOICE_VENDOR_OFFSET                      = 751;     
    public static final int INVOICE_REMIT_TO_OFFSET                    = 752;     
    public static final int INVOICE_REMIT_TO_COL_OFFSET                = 753;     
    public static final int INVOICE_REMIT_TO_ROW_OFFSET                = 756;     
    public static final int INVOICE_DUTY_FEES_HEAD_OFFSET              = 759;     
    public static final int STATEMENT_DIST_PORT_DEF_OFFSET             = 794;     
    public static final int COPIES_7501_OFFSET                         = 798;     
    public static final int DEFAULT_STOP_OFFSET                        = 800;     
    public static final int MERCH_PURCHASED_OFFSET                     = 801;     
    public static final int IMP_OR_OWNER_OFFSET                        = 802;     
    public static final int FWS_OFFSET                                 = 803;     
    public static final int SQUEEZE_FLAG_OFFSET                        = 804;     
    public static final int FCC_OFFSET                                 = 805;     
    public static final int FDA_OFFSET                                 = 806;     
    public static final int MESSAGE_3461_1_OFFSET                      = 807;     
    public static final int MESSAGE_3461_2_OFFSET                      = 811;     
    public static final int MESSAGE_3461_3_OFFSET                      = 815;     
    public static final int PRO_RATE_WEIGHT_OFFSET                     = 819;     
    public static final int PRO_RATE_CHARGES_OFFSET                    = 820;     
    public static final int F7501_X_MOVE_OFFSET                        = 821;     
    public static final int PAYDATE_DIV_OFFSET                         = 822;     
    public static final int CHECK_SHIP_ID_OFFSET                       = 823;     
    public static final int SEB_AUTO_CHAIN_OFFSET                      = 824;     
    public static final int CREDIT_CASH_POSITION_OFFSET                = 825;     
    public static final int ENHANCED_INVOICE_OFFSET                    = 826;     
    public static final int LANDED_COST_OFFSET                         = 827;     
    public static final int BREAK_BULK_AGENT_FLAG_OFFSET               = 828;     
    public static final int CHSPFILE_MODE_OFFSET                       = 829;     
    public static final int DO_NAME_ADDRESS_OFFSET                     = 830;     
    public static final int ALLOW_MULTIPLE_ADDRESSES_OFFSET            = 831;     
    public static final int DIST_PORT_UNLADING_OFFSET                  = 832;     
    public static final int LOADING_SHEET_NAME_ADDRESS_OFFSET          = 836;     
    public static final int NEXT_ENTRY_NUMBER_LIST_OFFSET              = 837;     
    public static final int POWERHOUSE_ACCT_OFFSET                     = 846;     
    public static final int NEXT_CUSTOMER_OFFSET                       = 847;     
    public static final int PASSWORD_CUST_OFFSET                       = 857;     
    public static final int BORDER_OFFSET                              = 863;     
    public static final int COPIES_3461_OFFSET                         = 864;     
    public static final int LAST_ENTRY_NO_OFFSET                       = 866;     
    public static final int BROKERS_BOND_DIV_0_OFFSET                  = 875;     
    public static final int COUNTRY_EXPORT_OFFSET                      = 876;     
    public static final int CERTIFICATION_ES_OFFSET                    = 878;     
    public static final int AUTO_BILL_OFFSET                           = 879;     
    public static final int PAPERLESS_ES_OFFSET                        = 880;     
    public static final int HOLD_7501_OFFSET                           = 881;     
    public static final int BROKERAGE_CHARGE_OFFSET                    = 882;     
    public static final int NEXT_SUMM_BILL_NO_OFFSET                   = 886;     
    public static final int PRINT_TEAM_DIV_OFFSET                      = 896;     
    public static final int INVCE_SKIP_LINE_OFFSET                     = 897;     
    public static final int DO_ID_COMBO_FORM_OFFSET                    = 898;     
    public static final int DOT_OFFSET                                 = 899;     
    public static final int NEXT_VENDOR_OFFSET                         = 900;     
    public static final int CUSTOM_1_OFFSET                            = 910;     
    public static final int CUSTOM_2_OFFSET                            = 911;     
    public static final int CUST_SHIPMENT_HEADER_OFFSET                = 912;     
    public static final int CUSTOM_4_OFFSET                            = 913;     
    public static final int CUSTOM_5_OFFSET                            = 914;     
    public static final int CUSTOM_6_OFFSET                            = 915;     
    public static final int CUSTOM_7_OFFSET                            = 916;     
    public static final int CUSTOM_8_OFFSET                            = 917;     
    public static final int CUSTOM_9_OFFSET                            = 918;     
    public static final int CUSTOM_10_OFFSET                           = 919;     
    public static final int SEB_PROD_ACCOUNT_OFFSET                    = 920;     
    public static final int NEXT_IT_NO_OFFSET                          = 927;     
    public static final int OPTIONS_3461_OFFSET                        = 936;     
    public static final int REMIT_TO_ADDRESS_4_OFFSET                  = 937;     
    public static final int DIV_FOR_NEXT_FILE_OFFSET                   = 967;     
    public static final int LOCATION_OFFSET                            = 971;     
    public static final int CURRENCY_OFFSET                            = 975;     
    public static final int UOM_VOLUME_OFFSET                          = 978;     
    public static final int UOM_WEIGHT_OFFSET                          = 984;     
    public static final int MESSAGE_NO_OFFSET                          = 990;     
    public static final int BREAK_BULK_DIV_FLAG_OFFSET                 = 994;     
    public static final int ALLOW_PREPAIDS_OFFSET                      = 995;     
    public static final int PART_NOTES_OFFSET                          = 996;     
    public static final int ENHANCED_CONTAINERS_OFFSET                 = 997;     
    public static final int CR_TO_ES_OFFSET                            = 998;     
    public static final int DELETE_FLAG_OFFSET                         = 999;     

	// Data types
    public static final String BROKER_CONTROL_TYPE                      = CHARACTER_TYPE;
    public static final String COMPANY_NO_TYPE                          = ZONED_NUMERIC_TYPE;
    public static final String DIVISION_NO_TYPE                         = ZONED_NUMERIC_TYPE;
    public static final String IMPORT_DIVISION_TYPE                     = CHARACTER_TYPE;
    public static final String EXPORT_DIVISION_TYPE                     = CHARACTER_TYPE;
    public static final String NAME_TYPE                                = CHARACTER_TYPE;
    public static final String ADDRESS_1_TYPE                           = CHARACTER_TYPE;
    public static final String ADDRESS_2_TYPE                           = CHARACTER_TYPE;
    public static final String CITY_TYPE                                = CHARACTER_TYPE;
    public static final String STATE_PROVINCE_TYPE                      = CHARACTER_TYPE;
    public static final String ZIP_TYPE                                 = CHARACTER_TYPE;
    public static final String PHONE_NO_ALPHA_TYPE                      = CHARACTER_TYPE;
    public static final String FAX_NO_ALPHA_TYPE                        = CHARACTER_TYPE;
    public static final String DIST_PORT_TYPE                           = ZONED_NUMERIC_TYPE;
    public static final String ENTRY_TYPE_TYPE                          = ZONED_NUMERIC_TYPE;    
    public static final String MOT_TYPE                                 = ZONED_NUMERIC_TYPE;     
    public static final String TIME_UPDATED_TYPE                        = ZONED_NUMERIC_TYPE;     
    public static final String DATE_UPDATED_TYPE                        = ZONED_NUMERIC_TYPE;     
    public static final String MODIFIED_BY_TYPE                         = CHARACTER_TYPE;     
    public static final String FOREIGN_CO_TYPE                          = CHARACTER_TYPE;     
    public static final String ACH_PAYER_UNIT_TYPE                      = CHARACTER_TYPE;     
    public static final String DUE_DATE_TYPE                            = CHARACTER_TYPE;     
    public static final String OTHER_COUNTRIES_01_TYPE                  = CHARACTER_TYPE;    
    public static final String OTHER_COUNTRIES_02_TYPE                  = CHARACTER_TYPE;     
    public static final String OTHER_COUNTRIES_03_TYPE                  = CHARACTER_TYPE;     
    public static final String OTHER_COUNTRIES_04_TYPE                  = CHARACTER_TYPE;   
    public static final String PROFILE_COMP_TYPE                        = ZONED_NUMERIC_TYPE;     
    public static final String NUMBER_COMP_TYPE                         = ZONED_NUMERIC_TYPE;     
    public static final String NUMBER_DIV_TYPE                          = ZONED_NUMERIC_TYPE;     
    public static final String FREIGHT_PAY_TYPE                         = CHARACTER_TYPE;     
    public static final String FRT_PAY_RATE_TYPE                        = ZONED_NUMERIC_TYPE;     
    public static final String REVRPT_WHOLE_DOLLAR_TYPE                 = CHARACTER_TYPE;     
    public static final String BILLTO_PROF_TYPE                         = CHARACTER_TYPE;     
    public static final String AUTO_SED_TYPE                            = CHARACTER_TYPE;     
    public static final String FRT_PAY_NUMB_TYPE                        = CHARACTER_TYPE;     
    public static final String ACH_TYPE                                 = CHARACTER_TYPE;     
    public static final String REVRPT_SING_COMP_TYPE                    = CHARACTER_TYPE;     
    public static final String REVRPT_ORIG_BILS_TYPE                    = CHARACTER_TYPE;     
    public static final String FAX_TYPE_TYPE                            = CHARACTER_TYPE;     
    public static final String EUROPEAN_DATE_TYPE                       = CHARACTER_TYPE;     
    public static final String ACCT_COMP_TYPE                           = ZONED_NUMERIC_TYPE;     
    public static final String FMC_NUMB_TYPE                            = CHARACTER_TYPE;     
    public static final String INTEREST_COMPUTED_TYPE                   = CHARACTER_TYPE;     
    public static final String INVCE_TRAN_DATE_TYPE                     = CHARACTER_TYPE;     
    public static final String TRACE_EXCLUDE_TYPE                       = CHARACTER_TYPE;     
    public static final String INQALL_MULTI_CO_TYPE                     = CHARACTER_TYPE;     
    public static final String SIGNATURE_TYPE                           = CHARACTER_TYPE;     
    public static final String PASSWORD_CREDIT_CHECK_TYPE               = CHARACTER_TYPE;     
    public static final String PASSWORD_CHECK_NAME_TYPE                 = CHARACTER_TYPE;     
    public static final String FILE_NO_TYPE                             = ZONED_NUMERIC_TYPE;     
    public static final String BANK_NO_TYPE                             = ZONED_NUMERIC_TYPE;     
    public static final String ENIC_CUSTOMERS_TYPE                      = CHARACTER_TYPE;     
    public static final String BOND_AMT_TYPE                            = ZONED_NUMERIC_TYPE;     
    public static final String PASSWORD_SHIP_ID_TYPE                    = CHARACTER_TYPE;     
    public static final String ABI_BROKER_TYPE                          = CHARACTER_TYPE;     
    public static final String ABI_LIVE_ES_TYPE                         = CHARACTER_TYPE;     
    public static final String ENTRY_NO_TYPE                            = ZONED_NUMERIC_TYPE;     
    public static final String FILE_AS_ENTRY_TYPE                       = CHARACTER_TYPE;     
    public static final String INFORMAL_LIMIT_TYPE                      = ZONED_NUMERIC_TYPE;     
    public static final String PREVIOUS_INFORMAL_LIMIT_TYPE             = ZONED_NUMERIC_TYPE;     
    public static final String INFORMAL_LIMIT_EFFECTIVE_DATE_TYPE       = ZONED_NUMERIC_TYPE;     
    public static final String RET_US_GOODS_INFORMAL_LIMIT_TYPE         = ZONED_NUMERIC_TYPE;     
    public static final String BROKER_FILER_TYPE                        = CHARACTER_TYPE;     
    public static final String WEIGHT_PERCENTAGE_TYPE                   = ZONED_NUMERIC_TYPE;     
    public static final String WEIGHT_VARIANCE_TYPE                     = ZONED_NUMERIC_TYPE;     
    public static final String VALUE_LIMIT_TYPE                         = ZONED_NUMERIC_TYPE;     
    public static final String QTY_LIMIT_TYPE                           = ZONED_NUMERIC_TYPE;     
    public static final String LINE_VALUE_LIMIT_TYPE                    = ZONED_NUMERIC_TYPE;     
    public static final String CHARGES_LIMIT_AIR_TYPE                   = ZONED_NUMERIC_TYPE;     
    public static final String CHARGES_LIMIT_OCEAN_TYPE                 = ZONED_NUMERIC_TYPE;     
    public static final String WEIGHT_LIMIT_AIR_TYPE                    = ZONED_NUMERIC_TYPE;     
    public static final String WEIGHT_LIMIT_OCEAN_TYPE                  = ZONED_NUMERIC_TYPE;     
    public static final String DUTY_OVERRIDE_TYPE                       = ZONED_NUMERIC_TYPE;     
    public static final String VIRGIN_ISLANDS_TYPE                      = CHARACTER_TYPE;     
    public static final String ORIGIN_STATION_TYPE                      = CHARACTER_TYPE;     
    public static final String AGENTS_IATA_CODE_TYPE                    = CHARACTER_TYPE;     
    public static final String COUNTRY_TYPE                             = CHARACTER_TYPE;     
    public static final String PROFIT_SHARE_CHARGE_TYPE                 = ZONED_NUMERIC_TYPE;     
    public static final String ALLOC_FREIGHT_COST_CHRG_TYPE             = ZONED_NUMERIC_TYPE;     
    public static final String ALLOCATED_PROFIT_SHARE_CHARGE_TYPE       = ZONED_NUMERIC_TYPE;     
    public static final String T_C_LOG_FLAG_TYPE                        = CHARACTER_TYPE;     
    public static final String BB_OCEAN_FORM_TYPE                       = ZONED_NUMERIC_TYPE;     
    public static final String BB_AIR_FORM_TYPE                         = ZONED_NUMERIC_TYPE;     
    public static final String CARGO_RELEASE_ENTRY_SUMM_TYPE            = CHARACTER_TYPE;     
    public static final String CUSTOM_FIELDS_TYPE                       = CHARACTER_TYPE;     
    public static final String ALLOC_NON_FREIGHT_COST_CHRG_TYPE         = ZONED_NUMERIC_TYPE;     
    public static final String ADJ_FRT_PROFIT_CHARGE_TYPE               = ZONED_NUMERIC_TYPE;     
    public static final String ADJ_NON_FRT_PROFIT_CHARGE_TYPE           = ZONED_NUMERIC_TYPE;     
    public static final String MESSAGE_NO_FOR_INVOICE_2_TYPE            = CHARACTER_TYPE;     
    public static final String PAYMENT_DUE_BASIS_TYPE                   = ZONED_NUMERIC_TYPE;     
    public static final String PAYMENT_DUE_RESEND_TYPE                  = CHARACTER_TYPE;     
    public static final String PAYMENT_DUE_RECALC_TYPE                  = CHARACTER_TYPE;     
    public static final String VERIFY_FILE_NO_TYPE                      = CHARACTER_TYPE;     
    public static final String ALLOW_PRELOAD_TYPE                       = CHARACTER_TYPE;     
    public static final String CONTAINER_DATES_NOTES_TYPE               = CHARACTER_TYPE;     
    public static final String DEFAULT_PORT_ENTRY_TYPE                  = CHARACTER_TYPE;     
    public static final String PRINT_TEAM_CUSTOMER_TYPE                 = CHARACTER_TYPE;     
    public static final String CRDCK_TYPE                               = CHARACTER_TYPE;     
    public static final String SECONDARY_CHECK_DIGIT_TYPE               = ZONED_UNSIGNED_TYPE;     
    public static final String CREDIT_REQUIRES_DEBIT_TYPE               = CHARACTER_TYPE;     
    public static final String VENDOR_REF_LENGTH_TYPE                   = ZONED_NUMERIC_TYPE;     
    public static final String ENTER_CI_COUNT_TYPE                      = CHARACTER_TYPE;     
    public static final String DEFAULT_CR_ES_TYPE                       = CHARACTER_TYPE;     
    public static final String FILE_PREFIX_TYPE                         = ZONED_NUMERIC_TYPE;     
    public static final String ALLOW_MANUAL_SUFFIX_TYPE                 = CHARACTER_TYPE;     
    public static final String FILLER_1_TYPE                            = CHARACTER_TYPE;     
    public static final String ALPH_NUM_SUFX_TYPE                       = CHARACTER_TYPE;     
    public static final String SWL_X_DAYS_TYPE                          = ZONED_NUMERIC_TYPE;     
    public static final String ACH_LOCK_TYPE                            = CHARACTER_TYPE;     
    public static final String DETERMINE_NAFTA_APTA_TYPE                = CHARACTER_TYPE;     
    public static final String APTA_END_USE_TYPE                        = CHARACTER_TYPE;     
    public static final String BIRD_TYPE                                = CHARACTER_TYPE;     
    public static final String REMOTE_PRINT_TYPE                        = CHARACTER_TYPE;     
    public static final String UOM_PIECES_TYPE                          = CHARACTER_TYPE;     
    public static final String TRACING_EXTRACT_MASTER_CUST_TYPE         = CHARACTER_TYPE;     
    public static final String AEI_EXTRACT_TYPE                         = CHARACTER_TYPE;     
    public static final String ZERO_BILLS_TYPE                          = CHARACTER_TYPE;     
    public static final String CONTROL_PIECES_FLAG_TYPE                 = CHARACTER_TYPE;     
    public static final String CONTROL_VOLUME_FLAG_TYPE                 = CHARACTER_TYPE;     
    public static final String CONTROL_WEIGHT_FLAG_TYPE                 = CHARACTER_TYPE;     
    public static final String CONTROL_COLLECT_FLAG_TYPE                = CHARACTER_TYPE;     
    public static final String CONTROL_PREPAID_FLAG_TYPE                = CHARACTER_TYPE;     
    public static final String SUBSIDIARY_LEDGER_GL_TYPE                = ZONED_NUMERIC_TYPE;     
    public static final String ORIGINAL_BILL_SUFFIX_TYPE                = CHARACTER_TYPE;     
    public static final String NOT_REC_AUTO_FAX_TEL_TYPE                = CHARACTER_TYPE;     
    public static final String ABI_LIVE_CR_TYPE                         = CHARACTER_TYPE;     
    public static final String CHARGE_VARIANCE_TYPE                     = ZONED_NUMERIC_TYPE;     
    public static final String CUSTOMS_PRIORITY_TYPE                    = ZONED_NUMERIC_TYPE;     
    public static final String BOND_TYPE_TYPE                           = CHARACTER_TYPE;     
    public static final String BOND_SURETY_TYPE                         = ZONED_NUMERIC_TYPE;     
    public static final String IRS_NO_TYPE                              = CHARACTER_TYPE;     
    public static final String REMIT_TO_ADDRESS_1_TYPE                  = CHARACTER_TYPE;     
    public static final String REMIT_TO_ADDRESS_2_TYPE                  = CHARACTER_TYPE;     
    public static final String REMIT_TO_ADDRESS_3_TYPE                  = CHARACTER_TYPE;     
    public static final String STATEMENTS_TYPE                          = CHARACTER_TYPE;     
    public static final String ANNUAL_INTEREST_RATE_TYPE                = ZONED_NUMERIC_TYPE;     
    public static final String INTEREST_CHARGE_CODE_TYPE                = ZONED_NUMERIC_TYPE;     
    public static final String DEDUCT_CHARGE_CODE_TYPE                  = ZONED_NUMERIC_TYPE;     
    public static final String AH_INTEREST_DEDUCT_MESS_TYPE             = CHARACTER_TYPE;     
    public static final String INTEREST_DAYS_FOR_INVOICE_TYPE           = ZONED_NUMERIC_TYPE;     
    public static final String INVOICE_SUB_TOTAL_TYPE                   = CHARACTER_TYPE;     
    public static final String CREDIT_MEMO_COLUMN_TYPE                  = ZONED_NUMERIC_TYPE;     
    public static final String CREDIT_MEMO_HIGH_TYPE                    = CHARACTER_TYPE;     
    public static final String INDENT_CHG_99_TYPE                       = CHARACTER_TYPE;     
    public static final String MESSAGE_NO_FOR_INVOICE_TYPE              = CHARACTER_TYPE;     
    public static final String INVOICE_VENDOR_TYPE                      = CHARACTER_TYPE;     
    public static final String INVOICE_REMIT_TO_TYPE                    = ZONED_NUMERIC_TYPE;     
    public static final String INVOICE_REMIT_TO_COL_TYPE                = ZONED_NUMERIC_TYPE;     
    public static final String INVOICE_REMIT_TO_ROW_TYPE                = CHARACTER_TYPE;     
    public static final String INVOICE_DUTY_FEES_HEAD_TYPE              = ZONED_NUMERIC_TYPE;     
    public static final String STATEMENT_DIST_PORT_DEF_TYPE             = ZONED_NUMERIC_TYPE;     
    public static final String COPIES_7501_TYPE                         = CHARACTER_TYPE;     
    public static final String DEFAULT_STOP_TYPE                        = CHARACTER_TYPE;     
    public static final String MERCH_PURCHASED_TYPE                     = CHARACTER_TYPE;     
    public static final String IMP_OR_OWNER_TYPE                        = CHARACTER_TYPE;     
    public static final String FWS_TYPE                                 = CHARACTER_TYPE;     
    public static final String SQUEEZE_FLAG_TYPE                        = CHARACTER_TYPE;     
    public static final String FCC_TYPE                                 = CHARACTER_TYPE;     
    public static final String FDA_TYPE                                 = CHARACTER_TYPE;     
    public static final String MESSAGE_3461_1_TYPE                      = CHARACTER_TYPE;     
    public static final String MESSAGE_3461_2_TYPE                      = CHARACTER_TYPE;     
    public static final String MESSAGE_3461_3_TYPE                      = CHARACTER_TYPE;     
    public static final String PRO_RATE_WEIGHT_TYPE                     = CHARACTER_TYPE;     
    public static final String PRO_RATE_CHARGES_TYPE                    = CHARACTER_TYPE;     
    public static final String F7501_X_MOVE_TYPE                        = CHARACTER_TYPE;     
    public static final String PAYDATE_DIV_TYPE                         = CHARACTER_TYPE;     
    public static final String CHECK_SHIP_ID_TYPE                       = CHARACTER_TYPE;     
    public static final String SEB_AUTO_CHAIN_TYPE                      = CHARACTER_TYPE;     
    public static final String CREDIT_CASH_POSITION_TYPE                = CHARACTER_TYPE;     
    public static final String ENHANCED_INVOICE_TYPE                    = CHARACTER_TYPE;     
    public static final String LANDED_COST_TYPE                         = CHARACTER_TYPE;     
    public static final String BREAK_BULK_AGENT_FLAG_TYPE               = CHARACTER_TYPE;     
    public static final String CHSPFILE_MODE_TYPE                       = CHARACTER_TYPE;     
    public static final String DO_NAME_ADDRESS_TYPE                     = CHARACTER_TYPE;     
    public static final String ALLOW_MULTIPLE_ADDRESSES_TYPE            = CHARACTER_TYPE;     
    public static final String DIST_PORT_UNLADING_TYPE                  = ZONED_NUMERIC_TYPE;     
    public static final String LOADING_SHEET_NAME_ADDRESS_TYPE          = CHARACTER_TYPE;     
    public static final String NEXT_ENTRY_NUMBER_LIST_TYPE              = ZONED_NUMERIC_TYPE;     
    public static final String POWERHOUSE_ACCT_TYPE                     = CHARACTER_TYPE;     
    public static final String NEXT_CUSTOMER_TYPE                       = ZONED_NUMERIC_TYPE;     
    public static final String PASSWORD_CUST_TYPE                       = CHARACTER_TYPE;     
    public static final String BORDER_TYPE                              = CHARACTER_TYPE;     
    public static final String COPIES_3461_TYPE                         = ZONED_NUMERIC_TYPE;     
    public static final String LAST_ENTRY_NO_TYPE                       = ZONED_NUMERIC_TYPE;     
    public static final String BROKERS_BOND_DIV_0_TYPE                  = CHARACTER_TYPE;     
    public static final String COUNTRY_EXPORT_TYPE                      = CHARACTER_TYPE;     
    public static final String CERTIFICATION_ES_TYPE                    = CHARACTER_TYPE;     
    public static final String AUTO_BILL_TYPE                           = CHARACTER_TYPE;     
    public static final String PAPERLESS_ES_TYPE                        = CHARACTER_TYPE;     
    public static final String HOLD_7501_TYPE                           = CHARACTER_TYPE;     
    public static final String BROKERAGE_CHARGE_TYPE                    = ZONED_NUMERIC_TYPE;     
    public static final String NEXT_SUMM_BILL_NO_TYPE                   = ZONED_NUMERIC_TYPE;     
    public static final String PRINT_TEAM_DIV_TYPE                      = CHARACTER_TYPE;     
    public static final String INVCE_SKIP_LINE_TYPE                     = CHARACTER_TYPE;     
    public static final String DO_ID_COMBO_FORM_TYPE                    = CHARACTER_TYPE;     
    public static final String DOT_TYPE                                 = CHARACTER_TYPE;     
    public static final String NEXT_VENDOR_TYPE                         = ZONED_NUMERIC_TYPE;     
    public static final String CUSTOM_1_TYPE                            = CHARACTER_TYPE;     
    public static final String CUSTOM_2_TYPE                            = CHARACTER_TYPE;     
    public static final String CUST_SHIPMENT_HEADER_TYPE                = CHARACTER_TYPE;     
    public static final String CUSTOM_4_TYPE                            = CHARACTER_TYPE;     
    public static final String CUSTOM_5_TYPE                            = CHARACTER_TYPE;     
    public static final String CUSTOM_6_TYPE                            = CHARACTER_TYPE;     
    public static final String CUSTOM_7_TYPE                            = CHARACTER_TYPE;     
    public static final String CUSTOM_8_TYPE                            = CHARACTER_TYPE;     
    public static final String CUSTOM_9_TYPE                            = CHARACTER_TYPE;     
    public static final String CUSTOM_10_TYPE                           = CHARACTER_TYPE;     
    public static final String SEB_PROD_ACCOUNT_TYPE                    = CHARACTER_TYPE;     
    public static final String NEXT_IT_NO_TYPE                          = ZONED_NUMERIC_TYPE;     
    public static final String OPTIONS_3461_TYPE                        = CHARACTER_TYPE;     
    public static final String REMIT_TO_ADDRESS_4_TYPE                  = CHARACTER_TYPE;     
    public static final String DIV_FOR_NEXT_FILE_TYPE                   = ZONED_NUMERIC_TYPE;     
    public static final String LOCATION_TYPE                            = CHARACTER_TYPE;     
    public static final String CURRENCY_TYPE                            = CHARACTER_TYPE;     
    public static final String UOM_VOLUME_TYPE                          = CHARACTER_TYPE;     
    public static final String UOM_WEIGHT_TYPE                          = CHARACTER_TYPE;     
    public static final String MESSAGE_NO_TYPE                          = CHARACTER_TYPE;     
    public static final String BREAK_BULK_DIV_FLAG_TYPE                 = CHARACTER_TYPE;     
    public static final String ALLOW_PREPAIDS_TYPE                      = CHARACTER_TYPE;     
    public static final String PART_NOTES_TYPE                          = CHARACTER_TYPE;     
    public static final String ENHANCED_CONTAINERS_TYPE                 = CHARACTER_TYPE;     
    public static final String CR_TO_ES_TYPE                            = CHARACTER_TYPE;     
    public static final String DELETE_FLAG_TYPE                         = CHARACTER_TYPE;     

    public BrokerControlImpl() {
        this(new char[BROKER_CONTROL_SIZE]);
    }
    
    public BrokerControlImpl(char[] data_elements) {
        
        super();
        if (data_elements.length != BROKER_CONTROL_SIZE)
            data_elements = new char[BROKER_CONTROL_SIZE];
            
        for (int i = 0; i < BROKER_CONTROL_SIZE; i++) {
            data_elements[i] = ' ';
        }
        
        DATA_ELEMENT_SIZE = BROKER_CONTROL_SIZE;
        this.data_elements = data_elements;
    }
}
