package com.workflow.client.naf.validate;  

import java.lang.reflect.Field;

public class GenericValidationBufferImpl extends PassListBase {

	protected TransModeImpl	trans_mode;

	// Field sizes
	public static final int GENERIC_VALIDATION_BUFFER_SIZE				= 1500; // offset - 0
    public static final int T_FILE_FLAGS_SIZE				 			= 50;	// offset - 0
    public static final int T_FILE_SET_1_SIZE				 			= 5;	// offset - 0
    public static final int T_CUSTOMER_FLAG_SIZE				 		= 1;	// offset - 0
    public static final int T_CARRIER_FLAG_SIZE				 		= 1;	// offset - 1
    public static final int T_IMPORTER_BOND_FLAG_SIZE				 	= 1;	// offset - 2
    public static final int T_ENTRY_VALID_BONDS_FLAG_SIZE				= 1;	// offset - 3
    public static final int T_LOCATION_FLAG_SIZE				 		= 1;	// offset - 4
    public static final int T_FILE_SET_2_SIZE				 			= 5;	// offset - 5
    public static final int T_COUNTRY_FLAG_SIZE				 		= 1;	// offset - 5
    public static final int T_COUNTRY_FILE_COLUMN_FLAG_SIZE			= 1;	// offset - 6
    public static final int T_COUNTRY_FILE_RESTRICT_FLAG_SIZE			= 1;	// offset - 7
    public static final int T_DIST_PORT_FLAG_SIZE						= 1;	// offset - 8
    public static final int T_DIST_PORT_ENTRY_FLAG_SIZE				= 1;	// offset - 9
    public static final int T_FILE_SET_3_SIZE							= 5;	// offset - 10
    public static final int T_TARIFF_CALC_FLAGS_FLAG_SIZE				= 1;	// offset - 10
    public static final int T_TARIFF_CLASS_FLAG_SIZE					= 1;	// offset - 11
    public static final int T_TARIFF_OGA_CLASS_FLAG_SIZE				= 1;	// offset - 12
    public static final int T_VALID_ENTRY_PORTS_FLAG_SIZE				= 1;	// offset - 13
    public static final int T_VALID_FILERS_FLAG_SIZE					= 1;	// offset - 14
    public static final int T_FILE_SET_4_SIZE							= 5;	// offset - 15
    public static final int T_ENTRY_TYPES_FLAG_SIZE					= 1;	// offset - 15
    public static final int T_TRANS_MODE_FLAG_SIZE						= 1;	// offset - 16
    public static final int T_OGA_CODES_FLAG_SIZE						= 1;	// offset - 17
    public static final int T_TARIFF_VALID_SPI_FLAG_SIZE				= 1;	// offset - 18
    public static final int T_COUNTRY_EXPORT_FLAG_SIZE					= 1;	// offset - 19
    public static final int T_FILE_SET_5_SIZE							= 5;	// offset - 20
    public static final int T_TARIFF_SPI_EXCLUSIONS_FLAG_SIZE			= 1;	// offset - 20
    public static final int T_COUNTRY_FILE_SPI_FLAG_SIZE				= 1;	// offset - 21
    public static final int T_CARRIER_AIRWAYBILL_FLAG_SIZE				= 1;	// offset - 22
    public static final int T_ADA_CVD_CASE_FLAG_SIZE					= 1;	// offset - 23
    public static final int T_ADA_CVD_CASE_RATES_FLAG_SIZE				= 1;	// offset - 24
    public static final int T_FILE_SET_6_SIZE							= 5;	// offset - 25
    public static final int T_PORT_FLAG_SIZE							= 1;	// offset - 25
    public static final int T_MANUFACTURER_FLAG_SIZE					= 1;	// offset - 26
    public static final int T_TARIFF_COMMODITY_F_T_FLAG_SIZE			= 1;	// offset - 27
    public static final int T_ENTRY_NO_CONTROL_FLAG_SIZE				= 1;	// offset - 28
    public static final int T_TARIFF_SPI_ELIGIBLE_FLAG_SIZE			= 1;	// offset - 29
    public static final int T_KEY_SIZE				 					= 62;	// offset - 50
    public static final int TK_FILE_NO_SIZE							= 10;	// offset - 50
    public static final int TK_CI_NO_SIZE								= 22;	// offset - 60
    public static final int TK_CI_LINE_NO_SIZE							= 5;	// offset - 82
    public static final int TK_TARIFF_LINE_NO_SIZE						= 5;	// offset - 87
    public static final int TK_SEQ_NO_SIZE								= 5;	// offset - 92
    public static final int TK_TARIFF_NO_SIZE							= 10;	// offset - 97
    public static final int TK_ES_OR_CR_SIZE							= 1;	// offset - 107
    public static final int T_VALID_DIVISION_NO_SIZE					= 4;	// offset - 108
    public static final int TEMPORARY_INFO_SIZE						= 210;	// offset - 112
    public static final int AIRWAYBILL_PREFIX_SIZE						= 3;	// offset - 112
    public static final int BILL_TO_CUST_SIZE							= 10;	// offset - 115
    public static final int BOND_DATE_SIZE								= 8;	// offset - 125
    public static final int BOND_TYPE_SIZE								= 1;	// offset - 133
    public static final int BROKER_FILER_SIZE							= 3;	// offset - 134
    public static final int CARRIER_SIZE								= 4;	// offset - 137
    public static final int CASE_NO_SIZE								= 10;	// offset - 141
    public static final int COUNTRY_EXPORT_SIZE						= 2;	// offset - 151
    public static final int COUNTRY_ORIGIN_SIZE						= 2;	// offset - 153
    public static final int CHEESE_CONTROL_NO_SIZE						= 5;	// offset - 155
    public static final int CUST_NO_SIZE								= 10;	// offset - 160
    public static final int DATE_ENTRY_SIZE							= 8;	// offset - 170
    public static final int DIST_PORT_SIZE								= 4;	// offset - 178
    public static final int DIST_PORT_ENTRY_SIZE						= 4;	// offset - 182
    public static final int IRS_NO_SIZE								= 12;	// offset - 186
    public static final int LOCATION_SIZE								= 4;	// offset - 198
    public static final int MANUFACTURER_ID_SIZE						= 15;	// offset - 202
    public static final int MASTER_ACCOUNT_NO_FOR_CAT_SIZE				= 10;	// offset - 217
    public static final int OGA_SIZE									= 3;	// offset - 227
    public static final int PORT_LADING_SIZE							= 5;	// offset - 230
    public static final int RELEASE_ID_ENTRY_FILER_SIZE				= 3;	// offset - 235
    public static final int RELEASE_ID_NO_SIZE							= 9;	// offset - 238
    public static final int SHIPMENT_DATE_00001_SIZE					= 8;	// offset - 247
    public static final int SHIPMENT_DATE_00007_SIZE					= 8;	// offset - 255
    public static final int SHIPMENT_DATE_00009_SIZE					= 8;	// offset - 263
    public static final int SHIPMENT_DATE_00012_SIZE					= 8;	// offset - 271
    public static final int SHIPMENT_DATE_00019_SIZE					= 8;	// offset - 279
    public static final int SHIPMENT_DATE_00042_SIZE					= 8;	// offset - 287
    public static final int SHIPMENT_DATE_00043_SIZE					= 8;	// offset - 295
    public static final int SPI_ELIGIBLE_SIZE							= 2;	// offset - 303
    public static final int SPI_PRIMARY_SIZE							= 2;	// offset - 305
    public static final int SPI_CODE_COUNTRY_SIZE						= 1;	// offset - 307
    public static final int TARIFF_NO_SIZE								= 10;	// offset - 308
    public static final int CUSTOM_CI_FLAG_SIZE						= 1;	// offset - 318
    public static final int ADA_CVD_CASE_INFO_SIZE						= 25;	// offset - 322
    public static final int ADA_CVD_CASE_FOUND_SIZE					= 1;	// offset - 322
    public static final int BONDED_CASH_INDICATOR_SIZE					= 1;	// offset - 323
    public static final int CASE_STATUS_SIZE							= 1;	// offset - 324
    public static final int DATE_LIQUIDATION_SUSPENSION_SIZE			= 8;	// offset - 325
    public static final int RELATED_CASE_NO_SIZE						= 10;	// offset - 333
    public static final int ADA_CVD_CASE_RATES_INFO_SIZE				= 40;	// offset - 347
    public static final int ADA_CVD_CASE_RATES_FOUND_SIZE				= 1;	// offset - 347
    public static final int DATE_EFFECTIVE_ENTRY_SIZE					= 8;	// offset - 348
    public static final int DATE_EFFECTIVE_EXPORT_SIZE					= 8;	// offset - 356
    public static final int RATE_INDICATOR_SIZE						= 1;	// offset - 364
    public static final int RATE_1_DEPOSIT_SIZE						= 5;	// offset - 365
    public static final int RATE_2_DEPOSIT_SIZE						= 5;	// offset - 370
    public static final int RATE_3_DEPOSIT_SIZE						= 5;	// offset - 375
    public static final int RATE_INDICATOR_DEPOSIT_SIZE				= 5;	// offset - 380
    public static final int CARRIER_AIRWAYBILL_INFO_SIZE				= 5;	// offset - 387
    public static final int CARRIER_AIRWAYBILL_FOUND_SIZE				= 1;	// offset - 387
    public static final int CARRIER_INFO_SIZE							= 5;	// offset - 392
    public static final int CARRIER_FOUND_SIZE							= 1;	// offset - 392
    public static final int CARRIER_MOT_SIZE							= 2;	// offset - 393
    public static final int AUTOMATED_AIR_MANIFEST_CAR_SIZE			= 1;	// offset - 395
    public static final int COUNTRY_EXPORT_INFO_SIZE					= 5;	// offset - 397
    public static final int CE_COUNTRY_FOUND_SIZE						= 1;	// offset - 397
    public static final int CE_ANDEAN_ASEAN_SIZE						= 1;	// offset - 398
    public static final int COUNTRY_FILE_COLUMN_INFO_SIZE				= 5;	// offset - 402
    public static final int COUNTRY_FILE_COLUMN_FOUND_SIZE				= 1;	// offset - 402
    public static final int RATE_COLUMN_IND_SIZE						= 1;	// offset - 403
    public static final int COUNTRY_FILE_RESTRICT_INFO_SIZE			= 20;	// offset - 407
    public static final int COUNTRY_FILE_RESTRICT_FOUND_SIZE			= 1;	// offset - 407
    public static final int CFR_DATE_EFFECTIVE_SIZE					= 8;	// offset - 408
    public static final int CFR_DATE_EXPIRATION_SIZE					= 8;	// offset - 416
    public static final int RESTRICTION_IND_SIZE						= 1;	// offset - 424
    public static final int COUNTRY_FILE_SPI_INFO_SIZE					= 5;	// offset - 427
    public static final int COUNTRY_FILE_SPI_FOUND_SIZE				= 1;	// offset - 427
    public static final int COUNTRY_INFO_SIZE							= 10;	// offset - 432
    public static final int COUNTRY_FOUND_SIZE							= 1;	// offset - 432
    public static final int ANDEAN_ASEAN_SIZE							= 1;	// offset - 433
    public static final int FOLKLORE_SIZE								= 1;	// offset - 434
    public static final int FREE_ASSOCIATION_OF_STATES_SIZE			= 1;	// offset - 435
    public static final int INSULAR_POSSESSION_SIZE					= 1;	// offset - 436
    public static final int QUOTA_REQUIREMENT_SIZE						= 1;	// offset - 437
    public static final int SAMPLE_SIZE								= 1;	// offset - 438
    public static final int VALIDATE_VISA_NO_SIZE						= 1;	// offset - 439
    public static final int CI_VISA_REQUIREMENT_SIZE					= 1;	// offset - 440
    public static final int CUSTOMER_INFO_SIZE							= 30;	// offset - 442
    public static final int CREDIT_CHECK_SIZE							= 1;	// offset - 442
    public static final int CREDIT_CHECK_CUSTOMER_SIZE					= 10;	// offset - 443
    public static final int CREDIT_LIMIT_SIZE							= 13;	// offset - 453
    public static final int AIRCRAFT_AGREEMENT_SIZE					= 1;	// offset - 466
    public static final int PRINT_DET_SUM_BOTH_RPTS_SIZE				= 1;	// offset - 467
    public static final int DEFAULT_CUST_REF_SIZE						= 1;	// offset - 468
    public static final int DIST_PORT_ENTRY_INFO_SIZE					= 40;	// offset - 472
    public static final int DIST_PORT_ENTRY_FOUND_SIZE					= 1;	// offset - 472
    public static final int DPE_NAME_SIZE								= 35;	// offset - 473
    public static final int VALID_ABI_PORT_OF_ENTRY_SIZE				= 1;	// offset - 508
    public static final int AUTOMATED_AIR_MANIFEST_DP_SIZE				= 1;	// offset - 509
    public static final int DIST_PORT_INFO_SIZE						= 5;	// offset - 512
    public static final int DIST_PORT_FOUND_SIZE						= 1;	// offset - 512
    public static final int MOT_AIR_SIZE								= 1;	// offset - 513
    public static final int MOT_OCEAN_SIZE								= 1;	// offset - 514
    public static final int MOT_SURFACE_SIZE							= 1;	// offset - 515
    public static final int ENTRY_NO_CONTROL_INFO_SIZE					= 15;	// offset - 517
    public static final int ENTRY_NO_CONTROL_FOUND_SIZE				= 1;	// offset - 517
    public static final int FILE_NO_SIZE								= 10;	// offset - 518
    public static final int ENTRY_VALID_BONDS_INFO_SIZE				= 5;	// offset - 532
    public static final int ENTRY_VALID_BONDS_FOUND_SIZE				= 1;	// offset - 532
    public static final int IMPORTER_BOND_INFO_SIZE					= 20;	// offset - 537
    public static final int IMPORTER_BOND_FOUND_SIZE					= 1;	// offset - 537
    public static final int IB_BOND_SURETY_SIZE						= 3;	// offset - 538
    public static final int DATE_BOND_EFFECTIVE_SIZE					= 8;	// offset - 541
    public static final int LOCATION_INFO_SIZE							= 5;	// offset - 557
    public static final int LOCATION_FOUND_SIZE						= 1;	// offset - 557
    public static final int FACILITY_TYPE_SIZE							= 2;	// offset - 558
    public static final int STATUS_LOCATION_SIZE						= 1;	// offset - 560
    public static final int AUTOMATED_AIR_MANIFEST_LOC_SIZE			= 1;	// offset - 561
    public static final int MANUFACTURER_INFO_SIZE						= 5;	// offset - 562
    public static final int MANUFACTURER_FOUND_SIZE					= 1;	// offset - 562
    public static final int OGA_CODES_INFO_SIZE						= 5;	// offset - 567
    public static final int REQUIRED_OPTIONAL_SIZE						= 1;	// offset - 567
    public static final int PORT_INFO_SIZE								= 5;	// offset - 572
    public static final int PORT_FOUND_SIZE							= 1;	// offset - 572
    public static final int VALID_IMP_EXP_BOTH_SIZE					= 1;	// offset - 573
    public static final int TARIFF_CALC_FLAGS_INFO_SIZE				= 15;	// offset - 577
    public static final int TARIFF_CALC_FLAGS_FOUND_SIZE				= 1;	// offset - 577
    public static final int AIRCRAFT_SIZE								= 1;	// offset - 578
    public static final int CALC_99_FLAG_SIZE							= 1;	// offset - 579
    public static final int TCFI_GOVERNMENT_SIZE						= 1;	// offset - 580
    public static final int HONG_KONG_VISA_NO_SIZE						= 1;	// offset - 581
    public static final int INFORMAL_RESTRICTED_SIZE					= 1;	// offset - 582
    public static final int RESTRICTED_ENTRY_TYPE_SIZE					= 2;	// offset - 583
    public static final int SPECIAL_PROVISIONS_SIZE					= 1;	// offset - 585
    public static final int SUBJECT_TO_250_LIMIT_SIZE					= 1;	// offset - 586
    public static final int TARIFF_NO_NOT_ALLOWED_SIZE					= 1;	// offset - 587
    public static final int MAY_APPLY_9905_SIZE						= 1;	// offset - 588
    public static final int TARIFF_CLASS_INFO_SIZE						= 70;	// offset - 592
    public static final int TARIFF_CLASS_FOUND_SIZE					= 1;	// offset - 592
    public static final int COUNTRY_ORIGIN_EDIT_CODE_SIZE				= 2;	// offset - 593
    public static final int DATE_TARIFF_EFFECTIVE_SIZE					= 8;	// offset - 595
    public static final int GROUP_PROCESSING_SIZE						= 1;	// offset - 603
    public static final int QTY_EDIT_DENOMINATOR_SIZE					= 1;	// offset - 604
    public static final int QTY_EDIT_HIGH_SIZE							= 10;	// offset - 605
    public static final int QTY_EDIT_LOW_SIZE							= 10;	// offset - 615
    public static final int QTY_EDIT_NUMERATOR_SIZE					= 1;	// offset - 625
    public static final int QTY_EDIT_RELATIONSHIP_SIZE					= 1;	// offset - 626
    public static final int UOM_1_SIZE									= 3;	// offset - 627
    public static final int UOM_2_SIZE									= 3;	// offset - 630
    public static final int UOM_3_SIZE									= 3;	// offset - 633
    public static final int VALUE_EDIT_QTY_SIZE						= 1;	// offset - 636
    public static final int VALUE_EDIT_RELATIONSHIP_SIZE				= 1;	// offset - 637
    public static final int VALUE_EDIT_TYPE_SIZE						= 1;	// offset - 638
    public static final int VALUE_HIGH_BOUNDS_SIZE						= 10;	// offset - 639
    public static final int VALUE_LOW_BOUNDS_SIZE						= 10;	// offset - 649
    public static final int TARIFF_COMMODITY_F_T_INFO_SIZE				= 5;	// offset - 662
    public static final int TARIFF_COMMODITY_F_T_FOUND_SIZE			= 1;	// offset - 662
    public static final int FLAG_TAX_FEE_SIZE							= 1;	// offset - 663
    public static final int TARIFF_OGA_CLASS_INFO_SIZE					= 5;	// offset - 667
    public static final int TARIFF_OGA_CLASS_FOUND_SIZE				= 1;	// offset - 667
    public static final int TARIFF_SPI_ELIGIBLE_INFO_SIZE				= 5;	// offset - 672
    public static final int TARIFF_SPI_ELIGIBLE_FOUND_SIZE				= 1;	// offset - 672
    public static final int TARIFF_SPI_EXCLUSIONS_INFO_SIZE			= 5;	// offset - 677
    public static final int TARIFF_SPI_EXCLUSIONS_FOUND_SIZE			= 1;	// offset - 677
    public static final int TARIFF_VALID_SPI_INFO_SIZE					= 5;	// offset - 682
    public static final int TARIFF_VALID_SPI_FOUND_SIZE				= 1;	// offset - 682
    public static final int SPI_FOUND_SPI_STAR_SIZE					= 1;	// offset - 683
    public static final int SPI_VALID_COUNTRY_SIZE						= 1;	// offset - 684
    public static final int VALID_ENTRY_PORTS_INFO_SIZE				= 5;	// offset - 687
    public static final int VALID_ENTRY_PORTS_FOUND_SIZE				= 1;	// offset - 687
    public static final int VALID_FILER_INFO_SIZE						= 5;	// offset - 692
    public static final int VALID_FILERS_FOUND_SIZE					= 1;	// offset - 692
    public static final int ENTRY_TYPE_SEARCH_FIELD_SIZE				= 200;	// offset - 697
    public static final int ENTRY_TYPE_SIZE							= 2;	// offset - 697
    public static final int ENTRY_TYPE_ALPHA_SIZE						= 2;	// offset - 697
    public static final int ENTRY_TYPE_DESC_SIZE						= 35;	// offset - 699
    public static final int TYPE_FORMAL_INFORMAL_ETC_SIZE				= 1;	// offset - 734
    public static final int VALID_ABI_ENTRY_TYPE_SIZE					= 1;	// offset - 735
    public static final int ENTRY_TYPE_7501_DUE_SIZE					= 1;	// offset - 736
    public static final int ENTRY_TYPE_QUOTA_NOT_RELEASED_SIZE			= 1;	// offset - 737
    public static final int EXCLUDE_MOT_SIZE							= 1;	// offset - 738
    public static final int TIME_UPDATED_01_SIZE						= 4;	// offset - 739
    public static final int DATE_UPDATED_01_SIZE						= 8;	// offset - 743
    public static final int MODIFIED_BY_01_SIZE						= 12;	// offset - 751
    public static final int ENT_PORT_LADING_REQUIRED_SIZE				= 1;	// offset - 763
    public static final int GOVERNMENT_SIZE							= 1;	// offset - 764
    public static final int SURETY_REQUIRED_SIZE						= 1;	// offset - 765
    public static final int PORT_UNLADING_REQUIRED_SIZE				= 1;	// offset - 766
    public static final int QUOTA_SIZE									= 1;	// offset - 767
    public static final int FTZ_SIZE									= 1;	// offset - 768
    public static final int LOCATION_CODE_REQUIRED_SIZE				= 1;	// offset - 769
    public static final int ALLOW_INSULAR_POSSESSIONS_SIZE				= 1;	// offset - 770
    public static final int VISA_REQUIREMENT_SIZE						= 1;	// offset - 771
    public static final int AGRICULTURE_LICENSE_SIZE					= 1;	// offset - 772
    public static final int ALLOW_PENALTIES_SIZE						= 1;	// offset - 773
    public static final int CHARGES_REQUIRED_SIZE						= 1;	// offset - 774
    public static final int ALLOW_CONSOLIDATIONS_SIZE					= 1;	// offset - 775
    public static final int PAYMENT_DAYS_SIZE							= 3;	// offset - 776
    public static final int PAYMENT_DAYS_QUOTA_SIZE					= 3;	// offset - 779
    public static final int ENTRY_DAYS_SIZE							= 3;	// offset - 782
    public static final int FORM_7512_SIZE								= 1;	// offset - 785
    public static final int ABI_IN_BOND_SIZE							= 1;	// offset - 786
    public static final int IN_BOND_FOREIGN_PORT_SIZE					= 1;	// offset - 787
    public static final int IN_BOND_TRANSPORTATION_SIZE				= 1;	// offset - 788
    public static final int IN_BOND_EXPORTATION_SIZE					= 1;	// offset - 789
    public static final int IN_BOND_IMMEDIATE_EXPORTATION_SIZE			= 1;	// offset - 790
    public static final int IN_BOND_TRANSFER_PERMIT_SIZE				= 1;	// offset - 791
    public static final int IB_TARIFF_SIZE								= 1;	// offset - 792
    public static final int TRACING_DATE_NO_SIZE						= 5;	// offset - 793
    public static final int PURGE_DAYS_SIZE							= 5;	// offset - 798
    public static final int VALID_DRAWBACK_TYPE_SIZE					= 1;	// offset - 803
    public static final int VALID_AES_ENTRY_TYPE_SIZE					= 1;	// offset - 804
    public static final int ALLOW_CA_SIZE								= 1;	// offset - 805
    public static final int NCAP_ENTRY_TYPE_SIZE						= 3;	// offset - 806
    public static final int ELIGIBLE_NAFTA_REFUND_SIZE					= 1;	// offset - 809
    public static final int RECON_ELIGIBLE_SIZE						= 1;	// offset - 810
    public static final int AUTO_ES_SIZE								= 1;	// offset - 811
    public static final int ALLOW_AII_SIZE								= 1;	// offset - 812
    public static final int LIQ_ELIGIBLE_SIZE							= 1;	// offset - 813
    public static final int SECTION_321_SIZE							= 1;	// offset - 814
    public static final int REQUIRE_CBTPA_CERT_SIZE					= 1;	// offset - 815
    public static final int REQUIRE_STEEL_LICENSE_SIZE					= 1;	// offset - 816
    public static final int ALLOW_RLF_SIZE								= 1;	// offset - 817
    public static final int FILLER_01_SIZE								= 79;	// offset - 818
    public static final int MOT_SIZE									= 200;	// offset - 897
    public static final int USER_CLASS_ID_SIZE							= 12;	// offset - 1097
    public static final int CI_NO_SIZE									= 22;	// offset - 1109
    public static final int SEVERE_NO_SIZE								= 5;	// offset - 1131
    public static final int ERROR_NO_SIZE								= 5;	// offset - 1136
    public static final int WARNING_NO_SIZE							= 5;	// offset - 1141
    public static final int SEVERE_MSG_SIZE							= 50;	// offset - 1146
    public static final int ERROR_MSG_SIZE								= 50;	// offset - 1196
    public static final int WARNING_MSG_SIZE							= 50;	// offset - 1246
    public static final int PERFORM_EOS_FLAG_SIZE						= 1;	// offset - 1296
    public static final int FILLER_03_SIZE								= 1;	// offset - 1297
    public static final int MASTER_ACC_NO_FOR_SHIPPER_SIZE				= 10;	// offset - 1298
    public static final int T_FATALS_SIZE								= 3;	// offset - 1308
    public static final int T_SEVERES_SIZE								= 3;	// offset - 1311
    public static final int T_WARNINGS_SIZE				 			= 3;	// offset - 1314
    public static final int CHSPQCKE_CI_LINE_NO_01_SIZE				= 5;   //  repeats 18 times:  offset - 1317
    public static final int CHSPQCKE_CI_LINE_NO_02_SIZE				= 5;   //  repeats 18 times:  offset - 1322
    public static final int CHSPQCKE_CI_LINE_NO_03_SIZE				= 5;   //  repeats 18 times:  offset - 1327
    public static final int CHSPQCKE_CI_LINE_NO_04_SIZE				= 5;   //  repeats 18 times:  offset - 1332
    public static final int CHSPQCKE_CI_LINE_NO_05_SIZE				= 5;   //  repeats 18 times:  offset - 1337
    public static final int CHSPQCKE_CI_LINE_NO_06_SIZE				= 5;   //  repeats 18 times:  offset - 1342
    public static final int CHSPQCKE_CI_LINE_NO_07_SIZE				= 5;   //  repeats 18 times:  offset - 1347
    public static final int CHSPQCKE_CI_LINE_NO_08_SIZE				= 5;   //  repeats 18 times:  offset - 1352
    public static final int CHSPQCKE_CI_LINE_NO_09_SIZE				= 5;   //  repeats 18 times:  offset - 1357
    public static final int CHSPQCKE_CI_LINE_NO_10_SIZE				= 5;   //  repeats 18 times:  offset - 1362
    public static final int CHSPQCKE_CI_LINE_NO_11_SIZE				= 5;   //  repeats 18 times:  offset - 1367
    public static final int CHSPQCKE_CI_LINE_NO_12_SIZE				= 5;   //  repeats 18 times:  offset - 1372
    public static final int CHSPQCKE_CI_LINE_NO_13_SIZE				= 5;   //  repeats 18 times:  offset - 1377
    public static final int CHSPQCKE_CI_LINE_NO_14_SIZE				= 5;   //  repeats 18 times:  offset - 1382
    public static final int CHSPQCKE_CI_LINE_NO_15_SIZE				= 5;   //  repeats 18 times:  offset - 1387
    public static final int CHSPQCKE_CI_LINE_NO_16_SIZE				= 5;   //  repeats 18 times:  offset - 1392
    public static final int CHSPQCKE_CI_LINE_NO_17_SIZE				= 5;   //  repeats 18 times:  offset - 1397
    public static final int CHSPQCKE_CI_LINE_NO_18_SIZE				= 5;   //  repeats 18 times:  offset - 1402
    public static final int AIRCRAFT_EXPIRATION_SIZE					= 8;	// offset - 1407
    public static final int ES_EDI_SIZE								= 1;	// offset - 1415
    public static final int FILLER_04_SIZE								= 84;	// offset - 1416

	// Array offsets
	public static final int GENERIC_VALIDATION_BUFFER_OFFSET 			= 0;
    public static final int T_FILE_FLAGS_OFFSET 						= 0;
    public static final int T_FILE_SET_1_OFFSET 						= 0;
    public static final int T_CUSTOMER_FLAG_OFFSET						= 0;
    public static final int T_CARRIER_FLAG_OFFSET						= 1;
    public static final int T_IMPORTER_BOND_FLAG_OFFSET				= 2;
    public static final int T_ENTRY_VALID_BONDS_FLAG_OFFSET			= 3;
    public static final int T_LOCATION_FLAG_OFFSET						= 4;
    public static final int T_FILE_SET_2_OFFSET						= 5;
    public static final int T_COUNTRY_FLAG_OFFSET						= 5;
    public static final int T_COUNTRY_FILE_COLUMN_FLAG_OFFSET			= 6;
    public static final int T_COUNTRY_FILE_RESTRICT_FLAG_OFFSET		= 7;
    public static final int T_DIST_PORT_FLAG_OFFSET					= 8;
    public static final int T_DIST_PORT_ENTRY_FLAG_OFFSET				= 9;
    public static final int T_FILE_SET_3_OFFSET						= 10;
    public static final int T_TARIFF_CALC_FLAGS_FLAG_OFFSET			= 10;
    public static final int T_TARIFF_CLASS_FLAG_OFFSET					= 11;
    public static final int T_TARIFF_OGA_CLASS_FLAG_OFFSET				= 12;
    public static final int T_VALID_ENTRY_PORTS_FLAG_OFFSET			= 13;
    public static final int T_VALID_FILERS_FLAG_OFFSET					= 14;
    public static final int T_FILE_SET_4_OFFSET						= 15;
    public static final int T_ENTRY_TYPES_FLAG_OFFSET					= 15;
    public static final int T_TRANS_MODE_FLAG_OFFSET					= 16;
    public static final int T_OGA_CODES_FLAG_OFFSET					= 17;
    public static final int T_TARIFF_VALID_SPI_FLAG_OFFSET				= 18;
    public static final int T_COUNTRY_EXPORT_FLAG_OFFSET				= 19;
    public static final int T_FILE_SET_5_OFFSET						= 20;
    public static final int T_TARIFF_SPI_EXCLUSIONS_FLAG_OFFSET		= 20;
    public static final int T_COUNTRY_FILE_SPI_FLAG_OFFSET				= 21;
    public static final int T_CARRIER_AIRWAYBILL_FLAG_OFFSET			= 22;
    public static final int T_ADA_CVD_CASE_FLAG_OFFSET					= 23;
    public static final int T_ADA_CVD_CASE_RATES_FLAG_OFFSET			= 24;
    public static final int T_FILE_SET_6_OFFSET						= 25;
    public static final int T_PORT_FLAG_OFFSET							= 25;
    public static final int T_MANUFACTURER_FLAG_OFFSET					= 26;
    public static final int T_TARIFF_COMMODITY_F_T_FLAG_OFFSET			= 27;
    public static final int T_ENTRY_NO_CONTROL_FLAG_OFFSET				= 28;
    public static final int T_TARIFF_SPI_ELIGIBLE_FLAG_OFFSET			= 29;
    public static final int T_KEY_OFFSET								= 50;
    public static final int TK_FILE_NO_OFFSET							= 50;
    public static final int TK_CI_NO_OFFSET							= 60;
    public static final int TK_CI_LINE_NO_OFFSET						= 82;
    public static final int TK_TARIFF_LINE_NO_OFFSET					= 87;
    public static final int TK_SEQ_NO_OFFSET							= 92;
    public static final int TK_TARIFF_NO_OFFSET						= 97;
    public static final int TK_ES_OR_CR_OFFSET							= 107;
    public static final int T_VALID_DIVISION_NO_OFFSET					= 108;
    public static final int TEMPORARY_INFO_OFFSET						= 112;
    public static final int AIRWAYBILL_PREFIX_OFFSET					= 112;
    public static final int BILL_TO_CUST_OFFSET						= 115;
    public static final int BOND_DATE_OFFSET							= 125;
    public static final int BOND_TYPE_OFFSET							= 133;
    public static final int BROKER_FILER_OFFSET						= 134;
    public static final int CARRIER_OFFSET								= 137;
    public static final int CASE_NO_OFFSET								= 141;
    public static final int COUNTRY_EXPORT_OFFSET						= 151;
    public static final int COUNTRY_ORIGIN_OFFSET						= 153;
    public static final int CHEESE_CONTROL_NO_OFFSET					= 155;
    public static final int CUST_NO_OFFSET								= 160;
    public static final int DATE_ENTRY_OFFSET							= 170;
    public static final int DIST_PORT_OFFSET							= 178;
    public static final int DIST_PORT_ENTRY_OFFSET						= 182;
    public static final int IRS_NO_OFFSET								= 186;
    public static final int LOCATION_OFFSET							= 198;
    public static final int MANUFACTURER_ID_OFFSET						= 202;
    public static final int MASTER_ACCOUNT_NO_FOR_CAT_OFFSET			= 217;
    public static final int OGA_OFFSET									= 227;
    public static final int PORT_LADING_OFFSET							= 230;
    public static final int RELEASE_ID_ENTRY_FILER_OFFSET				= 235;
    public static final int RELEASE_ID_NO_OFFSET						= 238;
    public static final int SHIPMENT_DATE_00001_OFFSET					= 247;
    public static final int SHIPMENT_DATE_00007_OFFSET					= 255;
    public static final int SHIPMENT_DATE_00009_OFFSET					= 263;
    public static final int SHIPMENT_DATE_00012_OFFSET					= 271;
    public static final int SHIPMENT_DATE_00019_OFFSET					= 279;
    public static final int SHIPMENT_DATE_00042_OFFSET					= 287;
    public static final int SHIPMENT_DATE_00043_OFFSET					= 295;
    public static final int SPI_ELIGIBLE_OFFSET						= 303;
    public static final int SPI_PRIMARY_OFFSET							= 305;
    public static final int SPI_CODE_COUNTRY_OFFSET					= 307;
    public static final int TARIFF_NO_OFFSET							= 308;
    public static final int CUSTOM_CI_FLAG_OFFSET						= 318;
    public static final int ADA_CVD_CASE_INFO_OFFSET					= 322;
    public static final int ADA_CVD_CASE_FOUND_OFFSET					= 322;
    public static final int BONDED_CASH_INDICATOR_OFFSET				= 323;
    public static final int CASE_STATUS_OFFSET							= 324;
    public static final int DATE_LIQUIDATION_SUSPENSION_OFFSET			= 325;
    public static final int RELATED_CASE_NO_OFFSET						= 333;
    public static final int ADA_CVD_CASE_RATES_INFO_OFFSET				= 347;
    public static final int ADA_CVD_CASE_RATES_FOUND_OFFSET			= 347;
    public static final int DATE_EFFECTIVE_ENTRY_OFFSET				= 348;
    public static final int DATE_EFFECTIVE_EXPORT_OFFSET				= 356;
    public static final int RATE_INDICATOR_OFFSET						= 364;
    public static final int RATE_1_DEPOSIT_OFFSET						= 365;
    public static final int RATE_2_DEPOSIT_OFFSET						= 370;
    public static final int RATE_3_DEPOSIT_OFFSET						= 375;
    public static final int RATE_INDICATOR_DEPOSIT_OFFSET				= 380;
    public static final int CARRIER_AIRWAYBILL_INFO_OFFSET				= 387;
    public static final int CARRIER_AIRWAYBILL_FOUND_OFFSET			= 387;
    public static final int CARRIER_INFO_OFFSET						= 392;
    public static final int CARRIER_FOUND_OFFSET						= 392;
    public static final int CARRIER_MOT_OFFSET							= 393;
    public static final int AUTOMATED_AIR_MANIFEST_CAR_OFFSET			= 395;
    public static final int COUNTRY_EXPORT_INFO_OFFSET					= 397;
    public static final int CE_COUNTRY_FOUND_OFFSET					= 397;
    public static final int CE_ANDEAN_ASEAN_OFFSET						= 398;
    public static final int COUNTRY_FILE_COLUMN_INFO_OFFSET			= 402;
    public static final int COUNTRY_FILE_COLUMN_FOUND_OFFSET			= 402;
    public static final int RATE_COLUMN_IND_OFFSET						= 403;
    public static final int COUNTRY_FILE_RESTRICT_INFO_OFFSET			= 407;
    public static final int COUNTRY_FILE_RESTRICT_FOUND_OFFSET			= 407;
    public static final int CFR_DATE_EFFECTIVE_OFFSET					= 408;
    public static final int CFR_DATE_EXPIRATION_OFFSET					= 416;
    public static final int RESTRICTION_IND_OFFSET						= 424;
    public static final int COUNTRY_FILE_SPI_INFO_OFFSET				= 427;
    public static final int COUNTRY_FILE_SPI_FOUND_OFFSET				= 427;
    public static final int COUNTRY_INFO_OFFSET						= 432;
    public static final int COUNTRY_FOUND_OFFSET						= 432;
    public static final int ANDEAN_ASEAN_OFFSET						= 433;
    public static final int FOLKLORE_OFFSET							= 434;
    public static final int FREE_ASSOCIATION_OF_STATES_OFFSET			= 435;
    public static final int INSULAR_POSSESSION_OFFSET					= 436;
    public static final int QUOTA_REQUIREMENT_OFFSET					= 437;
    public static final int SAMPLE_OFFSET								= 438;
    public static final int VALIDATE_VISA_NO_OFFSET					= 439;
    public static final int CI_VISA_REQUIREMENT_OFFSET					= 440;
    public static final int CUSTOMER_INFO_OFFSET						= 442;
    public static final int CREDIT_CHECK_OFFSET						= 442;
    public static final int CREDIT_CHECK_CUSTOMER_OFFSET				= 443;
    public static final int CREDIT_LIMIT_OFFSET						= 453;
    public static final int AIRCRAFT_AGREEMENT_OFFSET					= 466;
    public static final int PRINT_DET_SUM_BOTH_RPTS_OFFSET				= 467;
    public static final int DEFAULT_CUST_REF_OFFSET					= 468;
    public static final int DIST_PORT_ENTRY_INFO_OFFSET				= 472;
    public static final int DIST_PORT_ENTRY_FOUND_OFFSET				= 472;
    public static final int DPE_NAME_OFFSET							= 473;
    public static final int VALID_ABI_PORT_OF_ENTRY_OFFSET				= 508;
    public static final int AUTOMATED_AIR_MANIFEST_DP_OFFSET			= 509;
    public static final int DIST_PORT_INFO_OFFSET						= 512;
    public static final int DIST_PORT_FOUND_OFFSET						= 512;
    public static final int MOT_AIR_OFFSET								= 513;
    public static final int MOT_OCEAN_OFFSET							= 514;
    public static final int MOT_SURFACE_OFFSET							= 515;
    public static final int ENTRY_NO_CONTROL_INFO_OFFSET				= 517;
    public static final int ENTRY_NO_CONTROL_FOUND_OFFSET				= 517;
    public static final int FILE_NO_OFFSET								= 518;
    public static final int ENTRY_VALID_BONDS_INFO_OFFSET				= 532;
    public static final int ENTRY_VALID_BONDS_FOUND_OFFSET				= 532;
    public static final int IMPORTER_BOND_INFO_OFFSET					= 537;
    public static final int IMPORTER_BOND_FOUND_OFFSET					= 537;
    public static final int IB_BOND_SURETY_OFFSET						= 538;
    public static final int DATE_BOND_EFFECTIVE_OFFSET					= 541;
    public static final int LOCATION_INFO_OFFSET						= 557;
    public static final int LOCATION_FOUND_OFFSET						= 557;
    public static final int FACILITY_TYPE_OFFSET						= 558;
    public static final int STATUS_LOCATION_OFFSET						= 560;
    public static final int AUTOMATED_AIR_MANIFEST_LOC_OFFSET			= 561;
    public static final int MANUFACTURER_INFO_OFFSET					= 562;
    public static final int MANUFACTURER_FOUND_OFFSET					= 562;
    public static final int OGA_CODES_INFO_OFFSET						= 567;
    public static final int REQUIRED_OPTIONAL_OFFSET					= 567;
    public static final int PORT_INFO_OFFSET							= 572;
    public static final int PORT_FOUND_OFFSET							= 572;
    public static final int VALID_IMP_EXP_BOTH_OFFSET					= 573;
    public static final int TARIFF_CALC_FLAGS_INFO_OFFSET				= 577;
    public static final int TARIFF_CALC_FLAGS_FOUND_OFFSET				= 577;
    public static final int AIRCRAFT_OFFSET							= 578;
    public static final int CALC_99_FLAG_OFFSET						= 579;
    public static final int TCFI_GOVERNMENT_OFFSET						= 580;
    public static final int HONG_KONG_VISA_NO_OFFSET					= 581;
    public static final int INFORMAL_RESTRICTED_OFFSET					= 582;
    public static final int RESTRICTED_ENTRY_TYPE_OFFSET				= 583;
    public static final int SPECIAL_PROVISIONS_OFFSET					= 585;
    public static final int SUBJECT_TO_250_LIMIT_OFFSET				= 586;
    public static final int TARIFF_NO_NOT_ALLOWED_OFFSET				= 587;
    public static final int MAY_APPLY_9905_OFFSET						= 588;
    public static final int TARIFF_CLASS_INFO_OFFSET					= 592;
    public static final int TARIFF_CLASS_FOUND_OFFSET					= 592;
    public static final int COUNTRY_ORIGIN_EDIT_CODE_OFFSET			= 593;
    public static final int DATE_TARIFF_EFFECTIVE_OFFSET				= 595;
    public static final int GROUP_PROCESSING_OFFSET					= 603;
    public static final int QTY_EDIT_DENOMINATOR_OFFSET				= 604;
    public static final int QTY_EDIT_HIGH_OFFSET						= 605;
    public static final int QTY_EDIT_LOW_OFFSET						= 615;
    public static final int QTY_EDIT_NUMERATOR_OFFSET					= 625;
    public static final int QTY_EDIT_RELATIONSHIP_OFFSET				= 626;
    public static final int UOM_1_OFFSET								= 627;
    public static final int UOM_2_OFFSET								= 630;
    public static final int UOM_3_OFFSET								= 633;
    public static final int VALUE_EDIT_QTY_OFFSET						= 636;
    public static final int VALUE_EDIT_RELATIONSHIP_OFFSET				= 637;
    public static final int VALUE_EDIT_TYPE_OFFSET						= 638;
    public static final int VALUE_HIGH_BOUNDS_OFFSET					= 639;
    public static final int VALUE_LOW_BOUNDS_OFFSET					= 649;
    public static final int TARIFF_COMMODITY_F_T_INFO_OFFSET			= 662;
    public static final int TARIFF_COMMODITY_F_T_FOUND_OFFSET			= 662;
    public static final int FLAG_TAX_FEE_OFFSET						= 663;
    public static final int TARIFF_OGA_CLASS_INFO_OFFSET				= 667;
    public static final int TARIFF_OGA_CLASS_FOUND_OFFSET				= 667;
    public static final int TARIFF_SPI_ELIGIBLE_INFO_OFFSET			= 672;
    public static final int TARIFF_SPI_ELIGIBLE_FOUND_OFFSET			= 672;
    public static final int TARIFF_SPI_EXCLUSIONS_INFO_OFFSET			= 677;
    public static final int TARIFF_SPI_EXCLUSIONS_FOUND_OFFSET			= 677;
    public static final int TARIFF_VALID_SPI_INFO_OFFSET				= 682;
    public static final int TARIFF_VALID_SPI_FOUND_OFFSET				= 682;
    public static final int SPI_FOUND_SPI_STAR_OFFSET					= 683;
    public static final int SPI_VALID_COUNTRY_OFFSET					= 684;
    public static final int VALID_ENTRY_PORTS_INFO_OFFSET				= 687;
    public static final int VALID_ENTRY_PORTS_FOUND_OFFSET				= 687;
    public static final int VALID_FILER_INFO_OFFSET					= 692;
    public static final int VALID_FILERS_FOUND_OFFSET					= 692;
    public static final int ENTRY_TYPE_SEARCH_FIELD_OFFSET				= 697;
    public static final int ENTRY_TYPE_OFFSET							= 697;
    public static final int ENTRY_TYPE_ALPHA_OFFSET					= 697;
    public static final int ENTRY_TYPE_DESC_OFFSET						= 699;
    public static final int TYPE_FORMAL_INFORMAL_ETC_OFFSET			= 734;
    public static final int VALID_ABI_ENTRY_TYPE_OFFSET				= 735;
    public static final int ENTRY_TYPE_7501_DUE_OFFSET					= 736;
    public static final int ENTRY_TYPE_QUOTA_NOT_RELEASED_OFFSET		= 737;
    public static final int EXCLUDE_MOT_OFFSET							= 738;
    public static final int TIME_UPDATED_01_OFFSET						= 739;
    public static final int DATE_UPDATED_01_OFFSET						= 743;
    public static final int MODIFIED_BY_01_OFFSET						= 751;
    public static final int ENT_PORT_LADING_REQUIRED_OFFSET			= 763;
    public static final int GOVERNMENT_OFFSET							= 764;
    public static final int SURETY_REQUIRED_OFFSET						= 765;
    public static final int PORT_UNLADING_REQUIRED_OFFSET				= 766;
    public static final int QUOTA_OFFSET								= 767;
    public static final int FTZ_OFFSET									= 768;
    public static final int LOCATION_CODE_REQUIRED_OFFSET				= 769;
    public static final int ALLOW_INSULAR_POSSESSIONS_OFFSET			= 770;
    public static final int VISA_REQUIREMENT_OFFSET					= 771;
    public static final int AGRICULTURE_LICENSE_OFFSET					= 772;
    public static final int ALLOW_PENALTIES_OFFSET						= 773;
    public static final int CHARGES_REQUIRED_OFFSET					= 774;
    public static final int ALLOW_CONSOLIDATIONS_OFFSET				= 775;
    public static final int PAYMENT_DAYS_OFFSET						= 776;
    public static final int PAYMENT_DAYS_QUOTA_OFFSET					= 779;
    public static final int ENTRY_DAYS_OFFSET							= 782;
    public static final int FORM_7512_OFFSET							= 785;
    public static final int ABI_IN_BOND_OFFSET							= 786;
    public static final int IN_BOND_FOREIGN_PORT_OFFSET				= 787;
    public static final int IN_BOND_TRANSPORTATION_OFFSET				= 788;
    public static final int IN_BOND_EXPORTATION_OFFSET					= 789;
    public static final int IN_BOND_IMMEDIATE_EXPORTATION_OFFSET		= 790;
    public static final int IN_BOND_TRANSFER_PERMIT_OFFSET				= 791;
    public static final int IB_TARIFF_OFFSET							= 792;
    public static final int TRACING_DATE_NO_OFFSET						= 793;
    public static final int PURGE_DAYS_OFFSET							= 798;
    public static final int VALID_DRAWBACK_TYPE_OFFSET					= 803;
    public static final int VALID_AES_ENTRY_TYPE_OFFSET				= 804;
    public static final int ALLOW_CA_OFFSET							= 805;
    public static final int NCAP_ENTRY_TYPE_OFFSET						= 806;
    public static final int ELIGIBLE_NAFTA_REFUND_OFFSET				= 809;
    public static final int RECON_ELIGIBLE_OFFSET						= 810;
    public static final int AUTO_ES_OFFSET								= 811;
    public static final int ALLOW_AII_OFFSET							= 812;
    public static final int LIQ_ELIGIBLE_OFFSET						= 813;
    public static final int SECTION_321_OFFSET							= 814;
    public static final int REQUIRE_CBTPA_CERT_OFFSET					= 815;
    public static final int REQUIRE_STEEL_LICENSE_OFFSET				= 816;
    public static final int ALLOW_RLF_OFFSET							= 817;
    public static final int FILLER_01_OFFSET							= 818;
    public static final int MOT_OFFSET									= 897;
    public static final int USER_CLASS_ID_OFFSET						= 1097;
    public static final int CI_NO_OFFSET								= 1109;
    public static final int SEVERE_NO_OFFSET							= 1131;
    public static final int ERROR_NO_OFFSET							= 1136;
    public static final int WARNING_NO_OFFSET							= 1141;
    public static final int SEVERE_MSG_OFFSET							= 1146;
    public static final int ERROR_MSG_OFFSET							= 1196;
    public static final int WARNING_MSG_OFFSET							= 1246;
    public static final int PERFORM_EOS_FLAG_OFFSET					= 1296;
    public static final int FILLER_03_OFFSET							= 1297;
    public static final int MASTER_ACC_NO_FOR_SHIPPER_OFFSET			= 1298;
    public static final int T_FATALS_OFFSET							= 1308;
    public static final int T_SEVERES_OFFSET							= 1311;
    public static final int T_WARNINGS_OFFSET							= 1314;
    public static final int CHSPQCKE_CI_LINE_NO_01_OFFSET				= 1317;
    public static final int CHSPQCKE_CI_LINE_NO_02_OFFSET				= 1322;
    public static final int CHSPQCKE_CI_LINE_NO_03_OFFSET				= 1327;
    public static final int CHSPQCKE_CI_LINE_NO_04_OFFSET				= 1332;
    public static final int CHSPQCKE_CI_LINE_NO_05_OFFSET				= 1337;
    public static final int CHSPQCKE_CI_LINE_NO_06_OFFSET				= 1342;
    public static final int CHSPQCKE_CI_LINE_NO_07_OFFSET				= 1347;
    public static final int CHSPQCKE_CI_LINE_NO_08_OFFSET				= 1352;
    public static final int CHSPQCKE_CI_LINE_NO_09_OFFSET				= 1357;
    public static final int CHSPQCKE_CI_LINE_NO_10_OFFSET				= 1362;
    public static final int CHSPQCKE_CI_LINE_NO_11_OFFSET				= 1367;
    public static final int CHSPQCKE_CI_LINE_NO_12_OFFSET				= 1372;
    public static final int CHSPQCKE_CI_LINE_NO_13_OFFSET				= 1377;
    public static final int CHSPQCKE_CI_LINE_NO_14_OFFSET				= 1382;
    public static final int CHSPQCKE_CI_LINE_NO_15_OFFSET				= 1387;
    public static final int CHSPQCKE_CI_LINE_NO_16_OFFSET				= 1392;
    public static final int CHSPQCKE_CI_LINE_NO_17_OFFSET				= 1397;
    public static final int CHSPQCKE_CI_LINE_NO_18_OFFSET				= 1402;
    public static final int AIRCRAFT_EXPIRATION_OFFSET					= 1407;
    public static final int ES_EDI_OFFSET								= 1415;
    public static final int FILLER_04_OFFSET							= 1416;
    
	// Data types
	public static final String GENERIC_VALIDATION_BUFFER_TYPE 			= CHARACTER_TYPE;
    public static final String T_FILE_FLAGS_TYPE 						= CHARACTER_TYPE;
    public static final String T_FILE_SET_1_TYPE 						= CHARACTER_TYPE;
    public static final String T_CUSTOMER_FLAG_TYPE						= CHARACTER_TYPE;
    public static final String T_CARRIER_FLAG_TYPE						= CHARACTER_TYPE;
    public static final String T_IMPORTER_BOND_FLAG_TYPE				= CHARACTER_TYPE;
    public static final String T_ENTRY_VALID_BONDS_FLAG_TYPE			= CHARACTER_TYPE;
    public static final String T_LOCATION_FLAG_TYPE						= CHARACTER_TYPE;
    public static final String T_FILE_SET_2_TYPE						= CHARACTER_TYPE;
    public static final String T_COUNTRY_FLAG_TYPE						= CHARACTER_TYPE;
    public static final String T_COUNTRY_FILE_COLUMN_FLAG_TYPE			= CHARACTER_TYPE;
    public static final String T_COUNTRY_FILE_RESTRICT_FLAG_TYPE		= CHARACTER_TYPE;
    public static final String T_DIST_PORT_FLAG_TYPE					= CHARACTER_TYPE;
    public static final String T_DIST_PORT_ENTRY_FLAG_TYPE				= CHARACTER_TYPE;
    public static final String T_FILE_SET_3_TYPE						= CHARACTER_TYPE;
    public static final String T_TARIFF_CALC_FLAGS_FLAG_TYPE			= CHARACTER_TYPE;
    public static final String T_TARIFF_CLASS_FLAG_TYPE					= CHARACTER_TYPE;
    public static final String T_TARIFF_OGA_CLASS_FLAG_TYPE				= CHARACTER_TYPE;
    public static final String T_VALID_ENTRY_PORTS_FLAG_TYPE			= CHARACTER_TYPE;
    public static final String T_VALID_FILERS_FLAG_TYPE					= CHARACTER_TYPE;
    public static final String T_FILE_SET_4_TYPE						= CHARACTER_TYPE;
    public static final String T_ENTRY_TYPES_FLAG_TYPE					= CHARACTER_TYPE;
    public static final String T_TRANS_MODE_FLAG_TYPE					= CHARACTER_TYPE;
    public static final String T_OGA_CODES_FLAG_TYPE					= CHARACTER_TYPE;
    public static final String T_TARIFF_VALID_SPI_FLAG_TYPE				= CHARACTER_TYPE;
    public static final String T_COUNTRY_EXPORT_FLAG_TYPE				= CHARACTER_TYPE;
    public static final String T_FILE_SET_5_TYPE						= CHARACTER_TYPE;
    public static final String T_TARIFF_SPI_EXCLUSIONS_FLAG_TYPE		= CHARACTER_TYPE;
    public static final String T_COUNTRY_FILE_SPI_FLAG_TYPE				= CHARACTER_TYPE;
    public static final String T_CARRIER_AIRWAYBILL_FLAG_TYPE			= CHARACTER_TYPE;
    public static final String T_ADA_CVD_CASE_FLAG_TYPE					= CHARACTER_TYPE;
    public static final String T_ADA_CVD_CASE_RATES_FLAG_TYPE			= CHARACTER_TYPE;
    public static final String T_FILE_SET_6_TYPE						= CHARACTER_TYPE;
    public static final String T_PORT_FLAG_TYPE							= CHARACTER_TYPE;
    public static final String T_MANUFACTURER_FLAG_TYPE					= CHARACTER_TYPE;
    public static final String T_TARIFF_COMMODITY_F_T_FLAG_TYPE			= CHARACTER_TYPE;
    public static final String T_ENTRY_NO_CONTROL_FLAG_TYPE				= CHARACTER_TYPE;
    public static final String T_TARIFF_SPI_ELIGIBLE_FLAG_TYPE			= CHARACTER_TYPE;
    public static final String T_KEY_TYPE								= CHARACTER_TYPE;
    public static final String TK_FILE_NO_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String TK_CI_NO_TYPE							= CHARACTER_TYPE;
    public static final String TK_CI_LINE_NO_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String TK_TARIFF_LINE_NO_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String TK_SEQ_NO_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String TK_TARIFF_NO_TYPE						= CHARACTER_TYPE;
    public static final String TK_ES_OR_CR_TYPE							= CHARACTER_TYPE;
    public static final String T_VALID_DIVISION_NO_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String TEMPORARY_INFO_TYPE						= CHARACTER_TYPE;
    public static final String AIRWAYBILL_PREFIX_TYPE					= CHARACTER_TYPE;
    public static final String BILL_TO_CUST_TYPE						= CHARACTER_TYPE;
    public static final String BOND_DATE_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String BOND_TYPE_TYPE							= CHARACTER_TYPE;
    public static final String BROKER_FILER_TYPE						= CHARACTER_TYPE;
    public static final String CARRIER_TYPE								= CHARACTER_TYPE;
    public static final String CASE_NO_TYPE								= CHARACTER_TYPE;
    public static final String COUNTRY_EXPORT_TYPE						= CHARACTER_TYPE;
    public static final String COUNTRY_ORIGIN_TYPE						= CHARACTER_TYPE;
    public static final String CHEESE_CONTROL_NO_TYPE					= CHARACTER_TYPE;
    public static final String CUST_NO_TYPE								= CHARACTER_TYPE;
    public static final String DATE_ENTRY_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String DIST_PORT_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String DIST_PORT_ENTRY_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String IRS_NO_TYPE								= CHARACTER_TYPE;
    public static final String LOCATION_TYPE							= CHARACTER_TYPE;
    public static final String MANUFACTURER_ID_TYPE						= CHARACTER_TYPE;
    public static final String MASTER_ACCOUNT_NO_FOR_CAT_TYPE			= CHARACTER_TYPE;
    public static final String OGA_TYPE									= CHARACTER_TYPE;
    public static final String PORT_LADING_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String RELEASE_ID_ENTRY_FILER_TYPE				= CHARACTER_TYPE;
    public static final String RELEASE_ID_NO_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String SHIPMENT_DATE_00001_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String SHIPMENT_DATE_00007_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String SHIPMENT_DATE_00009_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String SHIPMENT_DATE_00012_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String SHIPMENT_DATE_00019_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String SHIPMENT_DATE_00042_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String SHIPMENT_DATE_00043_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String SPI_ELIGIBLE_TYPE						= CHARACTER_TYPE;
    public static final String SPI_PRIMARY_TYPE							= CHARACTER_TYPE;
    public static final String SPI_CODE_COUNTRY_TYPE					= CHARACTER_TYPE;
    public static final String TARIFF_NO_TYPE							= CHARACTER_TYPE;
    public static final String CUSTOM_CI_FLAG_TYPE						= CHARACTER_TYPE;
    public static final String ADA_CVD_CASE_INFO_TYPE					= CHARACTER_TYPE;
    public static final String ADA_CVD_CASE_FOUND_TYPE					= CHARACTER_TYPE;
    public static final String BONDED_CASH_INDICATOR_TYPE				= CHARACTER_TYPE;
    public static final String CASE_STATUS_TYPE							= CHARACTER_TYPE;
    public static final String DATE_LIQUIDATION_SUSPENSION_TYPE			= ZONED_NUMERIC_TYPE;
    public static final String RELATED_CASE_NO_TYPE						= CHARACTER_TYPE;
    public static final String ADA_CVD_CASE_RATES_INFO_TYPE				= CHARACTER_TYPE;
    public static final String ADA_CVD_CASE_RATES_FOUND_TYPE			= CHARACTER_TYPE;
    public static final String DATE_EFFECTIVE_ENTRY_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String DATE_EFFECTIVE_EXPORT_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String RATE_INDICATOR_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String RATE_1_DEPOSIT_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String RATE_2_DEPOSIT_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String RATE_3_DEPOSIT_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String RATE_INDICATOR_DEPOSIT_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CARRIER_AIRWAYBILL_INFO_TYPE				= CHARACTER_TYPE;
    public static final String CARRIER_AIRWAYBILL_FOUND_TYPE			= CHARACTER_TYPE;
    public static final String CARRIER_INFO_TYPE						= CHARACTER_TYPE;
    public static final String CARRIER_FOUND_TYPE						= CHARACTER_TYPE;
    public static final String CARRIER_MOT_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String AUTOMATED_AIR_MANIFEST_CAR_TYPE			= CHARACTER_TYPE;
    public static final String COUNTRY_EXPORT_INFO_TYPE					= CHARACTER_TYPE;
    public static final String CE_COUNTRY_FOUND_TYPE					= CHARACTER_TYPE;
    public static final String CE_ANDEAN_ASEAN_TYPE						= CHARACTER_TYPE;
    public static final String COUNTRY_FILE_COLUMN_INFO_TYPE			= CHARACTER_TYPE;
    public static final String COUNTRY_FILE_COLUMN_FOUND_TYPE			= CHARACTER_TYPE;
    public static final String RATE_COLUMN_IND_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String COUNTRY_FILE_RESTRICT_INFO_TYPE			= CHARACTER_TYPE;
    public static final String COUNTRY_FILE_RESTRICT_FOUND_TYPE			= CHARACTER_TYPE;
    public static final String CFR_DATE_EFFECTIVE_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String CFR_DATE_EXPIRATION_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String RESTRICTION_IND_TYPE						= CHARACTER_TYPE;
    public static final String COUNTRY_FILE_SPI_INFO_TYPE				= CHARACTER_TYPE;
    public static final String COUNTRY_FILE_SPI_FOUND_TYPE				= CHARACTER_TYPE;
    public static final String COUNTRY_INFO_TYPE						= CHARACTER_TYPE;
    public static final String COUNTRY_FOUND_TYPE						= CHARACTER_TYPE;
    public static final String ANDEAN_ASEAN_TYPE						= CHARACTER_TYPE;
    public static final String FOLKLORE_TYPE							= CHARACTER_TYPE;
    public static final String FREE_ASSOCIATION_OF_STATES_TYPE			= CHARACTER_TYPE;
    public static final String INSULAR_POSSESSION_TYPE					= CHARACTER_TYPE;
    public static final String QUOTA_REQUIREMENT_TYPE					= CHARACTER_TYPE;
    public static final String SAMPLE_TYPE								= CHARACTER_TYPE;
    public static final String VALIDATE_VISA_NO_TYPE					= CHARACTER_TYPE;
    public static final String CI_VISA_REQUIREMENT_TYPE					= CHARACTER_TYPE;
    public static final String CUSTOMER_INFO_TYPE						= CHARACTER_TYPE;
    public static final String CREDIT_CHECK_TYPE						= CHARACTER_TYPE;
    public static final String CREDIT_CHECK_CUSTOMER_TYPE				= CHARACTER_TYPE;
    public static final String CREDIT_LIMIT_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String AIRCRAFT_AGREEMENT_TYPE					= CHARACTER_TYPE;
    public static final String PRINT_DET_SUM_BOTH_RPTS_TYPE				= CHARACTER_TYPE;
    public static final String DEFAULT_CUST_REF_TYPE					= CHARACTER_TYPE;
    public static final String DIST_PORT_ENTRY_INFO_TYPE				= CHARACTER_TYPE;
    public static final String DIST_PORT_ENTRY_FOUND_TYPE				= CHARACTER_TYPE;
    public static final String DPE_NAME_TYPE							= CHARACTER_TYPE;
    public static final String VALID_ABI_PORT_OF_ENTRY_TYPE				= CHARACTER_TYPE;
    public static final String AUTOMATED_AIR_MANIFEST_DP_TYPE			= CHARACTER_TYPE;
    public static final String DIST_PORT_INFO_TYPE						= CHARACTER_TYPE;
    public static final String DIST_PORT_FOUND_TYPE						= CHARACTER_TYPE;
    public static final String MOT_AIR_TYPE								= CHARACTER_TYPE;
    public static final String MOT_OCEAN_TYPE							= CHARACTER_TYPE;
    public static final String MOT_SURFACE_TYPE							= CHARACTER_TYPE;
    public static final String ENTRY_NO_CONTROL_INFO_TYPE				= CHARACTER_TYPE;
    public static final String ENTRY_NO_CONTROL_FOUND_TYPE				= CHARACTER_TYPE;
    public static final String FILE_NO_TYPE								= ZONED_NUMERIC_TYPE;
    public static final String ENTRY_VALID_BONDS_INFO_TYPE				= CHARACTER_TYPE;
    public static final String ENTRY_VALID_BONDS_FOUND_TYPE				= CHARACTER_TYPE;
    public static final String IMPORTER_BOND_INFO_TYPE					= CHARACTER_TYPE;
    public static final String IMPORTER_BOND_FOUND_TYPE					= CHARACTER_TYPE;
    public static final String IB_BOND_SURETY_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String DATE_BOND_EFFECTIVE_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String LOCATION_INFO_TYPE						= CHARACTER_TYPE;
    public static final String LOCATION_FOUND_TYPE						= CHARACTER_TYPE;
    public static final String FACILITY_TYPE_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String STATUS_LOCATION_TYPE						= CHARACTER_TYPE;
    public static final String AUTOMATED_AIR_MANIFEST_LOC_TYPE			= CHARACTER_TYPE;
    public static final String MANUFACTURER_INFO_TYPE					= CHARACTER_TYPE;
    public static final String MANUFACTURER_FOUND_TYPE					= CHARACTER_TYPE;
    public static final String OGA_CODES_INFO_TYPE						= CHARACTER_TYPE;
    public static final String REQUIRED_OPTIONAL_TYPE					= CHARACTER_TYPE;
    public static final String PORT_INFO_TYPE							= CHARACTER_TYPE;
    public static final String PORT_FOUND_TYPE							= CHARACTER_TYPE;
    public static final String VALID_IMP_EXP_BOTH_TYPE					= CHARACTER_TYPE;
    public static final String TARIFF_CALC_FLAGS_INFO_TYPE				= CHARACTER_TYPE;
    public static final String TARIFF_CALC_FLAGS_FOUND_TYPE				= CHARACTER_TYPE;
    public static final String AIRCRAFT_TYPE							= CHARACTER_TYPE;
    public static final String CALC_99_FLAG_TYPE						= CHARACTER_TYPE;
    public static final String TCFI_GOVERNMENT_TYPE						= CHARACTER_TYPE;
    public static final String HONG_KONG_VISA_NO_TYPE					= CHARACTER_TYPE;
    public static final String INFORMAL_RESTRICTED_TYPE					= CHARACTER_TYPE;
    public static final String RESTRICTED_ENTRY_TYPE_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String SPECIAL_PROVISIONS_TYPE					= CHARACTER_TYPE;
    public static final String SUBJECT_TO_250_LIMIT_TYPE				= CHARACTER_TYPE;
    public static final String TARIFF_NO_NOT_ALLOWED_TYPE				= CHARACTER_TYPE;
    public static final String MAY_APPLY_9905_TYPE						= CHARACTER_TYPE;
    public static final String TARIFF_CLASS_INFO_TYPE					= CHARACTER_TYPE;
    public static final String TARIFF_CLASS_FOUND_TYPE					= CHARACTER_TYPE;
    public static final String COUNTRY_ORIGIN_EDIT_CODE_TYPE			= CHARACTER_TYPE;
    public static final String DATE_TARIFF_EFFECTIVE_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String GROUP_PROCESSING_TYPE					= CHARACTER_TYPE;
    public static final String QTY_EDIT_DENOMINATOR_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String QTY_EDIT_HIGH_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String QTY_EDIT_LOW_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String QTY_EDIT_NUMERATOR_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String QTY_EDIT_RELATIONSHIP_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String UOM_1_TYPE								= CHARACTER_TYPE;
    public static final String UOM_2_TYPE								= CHARACTER_TYPE;
    public static final String UOM_3_TYPE								= CHARACTER_TYPE;
    public static final String VALUE_EDIT_QTY_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String VALUE_EDIT_RELATIONSHIP_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String VALUE_EDIT_TYPE_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String VALUE_HIGH_BOUNDS_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String VALUE_LOW_BOUNDS_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String TARIFF_COMMODITY_F_T_INFO_TYPE			= CHARACTER_TYPE;
    public static final String TARIFF_COMMODITY_F_T_FOUND_TYPE			= CHARACTER_TYPE;
    public static final String FLAG_TAX_FEE_TYPE						= CHARACTER_TYPE;
    public static final String TARIFF_OGA_CLASS_INFO_TYPE				= CHARACTER_TYPE;
    public static final String TARIFF_OGA_CLASS_FOUND_TYPE				= CHARACTER_TYPE;
    public static final String TARIFF_SPI_ELIGIBLE_INFO_TYPE			= CHARACTER_TYPE;
    public static final String TARIFF_SPI_ELIGIBLE_FOUND_TYPE			= CHARACTER_TYPE;
    public static final String TARIFF_SPI_EXCLUSIONS_INFO_TYPE			= CHARACTER_TYPE;
    public static final String TARIFF_SPI_EXCLUSIONS_FOUND_TYPE			= CHARACTER_TYPE;
    public static final String TARIFF_VALID_SPI_INFO_TYPE				= CHARACTER_TYPE;
    public static final String TARIFF_VALID_SPI_FOUND_TYPE				= CHARACTER_TYPE;
    public static final String SPI_FOUND_SPI_STAR_TYPE					= CHARACTER_TYPE;
    public static final String SPI_VALID_COUNTRY_TYPE					= CHARACTER_TYPE;
    public static final String VALID_ENTRY_PORTS_INFO_TYPE				= CHARACTER_TYPE;
    public static final String VALID_ENTRY_PORTS_FOUND_TYPE				= CHARACTER_TYPE;
    public static final String VALID_FILER_INFO_TYPE					= CHARACTER_TYPE;
    public static final String VALID_FILERS_FOUND_TYPE					= CHARACTER_TYPE;
    public static final String ENTRY_TYPE_SEARCH_FIELD_TYPE				= CHARACTER_TYPE;
    public static final String ENTRY_TYPE_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String ENTRY_TYPE_ALPHA_TYPE					= CHARACTER_TYPE;
    public static final String ENTRY_TYPE_DESC_TYPE						= CHARACTER_TYPE;
    public static final String TYPE_FORMAL_INFORMAL_ETC_TYPE			= CHARACTER_TYPE;
    public static final String VALID_ABI_ENTRY_TYPE_TYPE				= CHARACTER_TYPE;
    public static final String ENTRY_TYPE_7501_DUE_TYPE					= CHARACTER_TYPE;
    public static final String ENTRY_TYPE_QUOTA_NOT_RELEASED_TYPE		= CHARACTER_TYPE;
    public static final String EXCLUDE_MOT_TYPE							= CHARACTER_TYPE;
    public static final String TIME_UPDATED_01_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String DATE_UPDATED_01_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String MODIFIED_BY_01_TYPE						= CHARACTER_TYPE;
    public static final String ENT_PORT_LADING_REQUIRED_TYPE			= CHARACTER_TYPE;
    public static final String GOVERNMENT_TYPE							= CHARACTER_TYPE;
    public static final String SURETY_REQUIRED_TYPE						= CHARACTER_TYPE;
    public static final String PORT_UNLADING_REQUIRED_TYPE				= CHARACTER_TYPE;
    public static final String QUOTA_TYPE								= CHARACTER_TYPE;
    public static final String FTZ_TYPE									= CHARACTER_TYPE;
    public static final String LOCATION_CODE_REQUIRED_TYPE				= CHARACTER_TYPE;
    public static final String ALLOW_INSULAR_POSSESSIONS_TYPE			= CHARACTER_TYPE;
    public static final String VISA_REQUIREMENT_TYPE					= CHARACTER_TYPE;
    public static final String AGRICULTURE_LICENSE_TYPE					= CHARACTER_TYPE;
    public static final String ALLOW_PENALTIES_TYPE						= CHARACTER_TYPE;
    public static final String CHARGES_REQUIRED_TYPE					= CHARACTER_TYPE;
    public static final String ALLOW_CONSOLIDATIONS_TYPE				= CHARACTER_TYPE;
    public static final String PAYMENT_DAYS_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String PAYMENT_DAYS_QUOTA_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String ENTRY_DAYS_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String FORM_7512_TYPE							= CHARACTER_TYPE;
    public static final String ABI_IN_BOND_TYPE							= CHARACTER_TYPE;
    public static final String IN_BOND_FOREIGN_PORT_TYPE				= CHARACTER_TYPE;
    public static final String IN_BOND_TRANSPORTATION_TYPE				= CHARACTER_TYPE;
    public static final String IN_BOND_EXPORTATION_TYPE					= CHARACTER_TYPE;
    public static final String IN_BOND_IMMEDIATE_EXPORTATION_TYPE		= CHARACTER_TYPE;
    public static final String IN_BOND_TRANSFER_PERMIT_TYPE				= CHARACTER_TYPE;
    public static final String IB_TARIFF_TYPE							= CHARACTER_TYPE;
    public static final String TRACING_DATE_NO_TYPE						= ZONED_NUMERIC_TYPE;
    public static final String PURGE_DAYS_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String VALID_DRAWBACK_TYPE_TYPE					= CHARACTER_TYPE;
    public static final String VALID_AES_ENTRY_TYPE_TYPE				= CHARACTER_TYPE;
    public static final String ALLOW_CA_TYPE							= CHARACTER_TYPE;
    public static final String NCAP_ENTRY_TYPE_TYPE						= CHARACTER_TYPE;
    public static final String ELIGIBLE_NAFTA_REFUND_TYPE				= CHARACTER_TYPE;
    public static final String RECON_ELIGIBLE_TYPE						= CHARACTER_TYPE;
    public static final String AUTO_ES_TYPE								= CHARACTER_TYPE;
    public static final String ALLOW_AII_TYPE							= CHARACTER_TYPE;
    public static final String LIQ_ELIGIBLE_TYPE						= CHARACTER_TYPE;
    public static final String SECTION_321_TYPE							= CHARACTER_TYPE;
    public static final String REQUIRE_CBTPA_CERT_TYPE					= CHARACTER_TYPE;
    public static final String REQUIRE_STEEL_LICENSE_TYPE				= CHARACTER_TYPE;
    public static final String ALLOW_RLF_TYPE							= CHARACTER_TYPE;
    public static final String FILLER_01_TYPE							= CHARACTER_TYPE;
    public static final String MOT_TYPE									= RECORD_TYPE;
    public static final String USER_CLASS_ID_TYPE						= CHARACTER_TYPE;
    public static final String CI_NO_TYPE								= CHARACTER_TYPE;
    public static final String SEVERE_NO_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String ERROR_NO_TYPE							= ZONED_NUMERIC_TYPE;
    public static final String WARNING_NO_TYPE							= ZONED_UNSIGNED_TYPE;
    public static final String SEVERE_MSG_TYPE							= CHARACTER_TYPE;
    public static final String ERROR_MSG_TYPE							= CHARACTER_TYPE;
    public static final String WARNING_MSG_TYPE							= CHARACTER_TYPE;
    public static final String PERFORM_EOS_FLAG_TYPE					= CHARACTER_TYPE;
    public static final String FILLER_03_TYPE							= CHARACTER_TYPE;
    public static final String MASTER_ACC_NO_FOR_SHIPPER_TYPE			= CHARACTER_TYPE;
    public static final String T_FATALS_TYPE							= ZONED_UNSIGNED_TYPE;
    public static final String T_SEVERES_TYPE							= ZONED_UNSIGNED_TYPE;
    public static final String T_WARNINGS_TYPE							= ZONED_UNSIGNED_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_01_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_02_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_03_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_04_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_05_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_06_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_07_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_08_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_09_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_10_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_11_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_12_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_13_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_14_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_15_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_16_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_17_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String CHSPQCKE_CI_LINE_NO_18_TYPE				= ZONED_NUMERIC_TYPE;
    public static final String AIRCRAFT_EXPIRATION_TYPE					= ZONED_NUMERIC_TYPE;
    public static final String ES_EDI_TYPE								= CHARACTER_TYPE;
    public static final String FILLER_04_TYPE							= CHARACTER_TYPE;
    
    public GenericValidationBufferImpl() {
        this(new char[GENERIC_VALIDATION_BUFFER_SIZE]);
    }
    
    public GenericValidationBufferImpl(char[] data_elements) {
        
        super();
        if (data_elements.length != GENERIC_VALIDATION_BUFFER_SIZE)
            data_elements = new char[GENERIC_VALIDATION_BUFFER_SIZE];
            
        for (int i = 0; i < GENERIC_VALIDATION_BUFFER_SIZE; i++) {
            data_elements[i] = ' ';
        }
        
        DATA_ELEMENT_SIZE = GENERIC_VALIDATION_BUFFER_SIZE;
        this.data_elements = data_elements;
        trans_mode = new TransModeImpl();
    }
    
	public TransModeImpl getTransMode() {
		return trans_mode;
	}
}
