package com.workflow.client.naf.validate;   

import java.lang.reflect.Field;

public class ShipmentHeaderImpl extends PassListBase {

    // Field sizes
    public static final int SHIPMENT_HEADER_SIZE                     =   1750;     // offset     0
    public static final int FILE_NO_SIZE                             =   10;     // offset     0
    public static final int CUST_NO_SIZE                             =   10;     // offset    10
    public static final int DATE_REVERSE_JULIAN_LOG_SIZE             =    6;     // offset    20
    public static final int VESSEL_AIRLINE_NAME_SIZE                 =   20;     // offset    26
    public static final int OPEN_CLOSED_SIZE                         =    1;     // offset    46
    public static final int COMPANY_NO_SIZE                          =    2;     // offset    47
    public static final int DIVISION_NO_SIZE                         =    4;     // offset    49
    public static final int TIB_EXTENSIONS_SIZE                      =    1;     // offset    53
    public static final int CI_TOT_ENTERED_SIZE                      =    5;     // offset    54
    public static final int PORT_LADING_SIZE                         =    5;     // offset    59
    public static final int DIST_PORT_SIZE                           =    4;     // offset    64
    public static final int BROKER_FILER_SIZE                        =    3;     // offset    68
    public static final int ENTRY_NO_SIZE                            =    9;     // offset    71
    public static final int CONCEPT_SIZE                             =   10;     // offset    80
    public static final int ENTRY_TYPE_SIZE                          =    2;     // offset    90
    public static final int MOT_SIZE                                 =    2;     // offset    92
    public static final int CARRIER_SIZE                             =    4;     // offset    94
    public static final int VOYAGE_FLIGHT_NO_SIZE                    =   10;     // offset    98
    public static final int BROKER_TEAM_SIZE                         =    4;     // offset   108
    public static final int BOND_TYPE_SIZE                           =    1;     // offset   112
    public static final int CERTIFICATION_CR_ES_SIZE                 =    1;     // offset   113
    public static final int BOND_SURETY_SIZE                         =    3;     // offset   114
    public static final int BOND_AMT_SIZE                            =   11;     // offset   117
    public static final int SHIPPER_NAME_SIZE                        =   35;     // offset   128
    public static final int DESC_OF_GOODS_SIZE                       =   70;     // offset   163
    public static final int DIST_PORT_ENTRY_SIZE                     =    4;     // offset   233
    public static final int COUNTRY_EXPORT_SIZE                      =    2;     // offset   237
    public static final int COUNTRY_ORIGIN_SIZE                      =    2;     // offset   239
    public static final int PIECE_COUNT_SIZE                         =   12;     // offset   241
    public static final int UOM_SIZE                                 =    6;     // offset   253
    public static final int WEIGHT_GROSS_SIZE                        =   12;     // offset   259
    public static final int UOM_WEIGHT_SIZE                          =    6;     // offset   271
    public static final int VOLUME_TOT_SIZE                          =   12;     // offset   277
    public static final int FREIGHT_VENDOR_NO_SIZE                   =   10;     // offset   289
    public static final int LOCATION_SIZE                            =    4;     // offset   299
    public static final int LOCATION_OF_GOODS_SIZE                   =   35;     // offset   303
    public static final int EXAM_TYPE_SIZE                           =    2;     // offset   338
    public static final int EXAMINATION_LOCATION_SIZE                =    4;     // offset   340
    public static final int VAN_DEVANNING_LOCATION_SIZE              =   35;     // offset   344
    public static final int GENERAL_ORDER_WAREHOUSE_NO_SIZE          =   12;     // offset   379
    public static final int CONSOLIDATED_PERSONAL_SAMPLE_SIZE        =    1;     // offset   391
    public static final int CUSTOMS_TEAM_SIZE                        =    3;     // offset   392
    public static final int USER_CLASS_ID_SIZE                       =   12;     // offset   395
    public static final int CUSTOMS_PRIORITY_SIZE                    =    1;     // offset   407
    public static final int NON_ID_LIVE_ENTRY_SIZE                   =    1;     // offset   408
    public static final int ENTRY_DATE_ELECTION_SIZE                 =    1;     // offset   409
    public static final int ENTRY_DATE_ESTIMATED_ACTUAL_SIZE         =    1;     // offset   410
    public static final int SQUEEZE_IT_SIZE                          =    1;     // offset   411
    public static final int NO_TIB_EXTENSIONS_SIZE                   =    1;     // offset   412
    public static final int ADA_CVD_SURETY_SIZE                      =    3;     // offset   413
    public static final int VALUE_ENTERED_SIZE                       =   13;     // offset   416
    public static final int INTERNATIONAL_FREIGHT_CHARGES_SIZE       =   12;     // offset   429
    public static final int INBOUND_CONSOLIDATOR_SIZE                =   10;     // offset   441
    public static final int FORWARDER_SIZE                           =   10;     // offset   451
    public static final int ACH_PAYMENT_SIZE                         =    1;     // offset   461
    public static final int ABI_PAYMENT_TYPE_SIZE                    =    1;     // offset   462
    public static final int IRS_TAX_DEFERRED_SIZE                    =    1;     // offset   463
    public static final int IRS_TAX_DEFERRED_EFT_SIZE                =    1;     // offset   464
    public static final int ABI_ENTRY_SIZE                           =    1;     // offset   465
    public static final int RATE_PER_METER_SIZE                      =    6;     // offset   466
    public static final int OVERRIDE_FILE_CLOSING_SIZE               =    1;     // offset   472
    public static final int SIGNATURE_FOR_ES_SIZE                    =   35;     // offset   473
    public static final int SIGNATURE_FOR_CR_SIZE                    =   35;     // offset   508
    public static final int TRANSACTION_CONTROL_NO_SIZE              =   10;     // offset   543
    public static final int MANIFEST_NO_SIZE                         =   13;     // offset   553
    public static final int INLAND_BILL_OF_LADING_SIZE               =   13;     // offset   566
    public static final int BROKER_YN_SIZE                           =    1;     // offset   579
    public static final int LOW_HIGH_MPF_SIZE                        =    1;     // offset   580
    public static final int MESSAGE_7501_SIZE                        =    4;     // offset   581
    public static final int MESSAGE_TIB_SIZE                         =    4;     // offset   585
    public static final int IMP_OR_OWNER_SIZE                        =    1;     // offset   589
    public static final int MERCH_PURCHASED_SIZE                     =    1;     // offset   590
    public static final int CONTAINER_TOT_SIZE                       =    5;     // offset   591
    public static final int DO_TOT_SIZE                              =    5;     // offset   596
    public static final int CI_TOT_SIZE                              =    5;     // offset   601
    public static final int DUTY_AMT_LIQUIDATED_SIZE                 =   12;     // offset   606
    public static final int TAX_AMT_LIQUIDATED_SIZE                  =   12;     // offset   618
    public static final int FEE_AMT_LIQUIDATED_SIZE                  =   12;     // offset   630
    public static final int ADA_AMT_LIQUIDATED_SIZE                  =   12;     // offset   642
    public static final int CVD_AMT_LIQUIDATED_SIZE                  =   12;     // offset   654
    public static final int PROTEST_LIQUIDATION_SIZE                 =    1;     // offset   666
    public static final int TYPE_LIQUIDATION_SIZE                    =    2;     // offset   667
    public static final int ACTION_LIQUIDATION_SIZE                  =    2;     // offset   669
    public static final int EXTEND_SUSPEND_LIQ_SIZE                  =    2;     // offset   671
    public static final int NO_EXTEND_SUSPEND_LIQUIDATION_SIZE       =    1;     // offset   673
    public static final int CUSTOMS_DOC_FILING_LOC_SIZE              =   18;     // offset   674
    public static final int DUTY_TOT_SIZE                            =   12;     // offset   692
    public static final int TIB_DUTY_TOT_SIZE                        =   12;     // offset   704
    public static final int TAX_DEFERRED_TOT_SIZE                    =   12;     // offset   716
    public static final int TAX_NON_DEFERRED_TOT_SIZE                =   12;     // offset   728
    public static final int FEES_TOT_SIZE                            =   12;     // offset   740
    public static final int ADA_NON_BONDED_TOT_SIZE                  =   12;     // offset   752
    public static final int CVD_NON_BONDED_TOT_SIZE                  =   12;     // offset   764
    public static final int CVD_BONDED_TOT_SIZE                      =   12;     // offset   776
    public static final int ADA_BONDED_TOT_SIZE                      =   12;     // offset   788
    public static final int DUTY_FEES_TAXES_BILLED_TOT_SIZE          =   12;     // offset   800
    public static final int DUTY_FEES_TAXES_PAID_TOT_SIZE            =   12;     // offset   812
    public static final int CHECK_NO_FOR_DUTY_SIZE                   =   10;     // offset   824
    public static final int DUTY_PAID_DIRECT_SIZE                    =    1;     // offset   834
    public static final int DUTY_PAID_DIRECT_AMT_SIZE                =   12;     // offset   835
    public static final int STATEMENT_NO_SHIPMENT_SIZE               =   11;     // offset   847
    public static final int FREIGHT_BILLED_TOT_SIZE                  =   12;     // offset   858
    public static final int FREIGHT_PAID_TOT_SIZE                    =   12;     // offset   870
    public static final int CHECK_NO_FOR_FREIGHT_SIZE                =   10;     // offset   882
    public static final int FREIGHT_PAID_DIRECT_SIZE                 =    1;     // offset   892
    public static final int FREIGHT_PAID_DIRECT_AMT_SIZE             =   12;     // offset   893
    public static final int BILLED_TO_DATE_TOT_SIZE                  =   12;     // offset   905
    public static final int PAID_BY_CLIENT_TOT_SIZE                  =   12;     // offset   917
    public static final int CR_PROCESSING_RESULTS_SIZE               =    1;     // offset   929
    public static final int CR_DISPOSITION_SIZE                      =    2;     // offset   930
    public static final int CR_CERTIFICATION_OUTPUT_MESS_SIZE        =   33;     // offset   932
    public static final int EXAMINATION_OVERRIDDEN_SIZE              =    1;     // offset   965
    public static final int CENSUS_WARNING_SIZE                      =    1;     // offset   966
    public static final int SQUEEZED_SIZE                            =    1;     // offset   967
    public static final int USER_CLASS_ID_CR_SIZE                    =   12;     // offset   968
    public static final int USER_CLASS_ID_ES_SIZE                    =   12;     // offset   980
    public static final int AII_TRANSACTION_SIZE                     =    1;     // offset   992
    public static final int CERTIFICATION_CR_SIZE                    =    1;     // offset   993
    public static final int ALREADY_SENT_CR_SIZE                     =    1;     // offset   994
    public static final int ERROR_FREE_CR_SIZE                       =    1;     // offset   995
    public static final int VALIDATE_CR_SIZE                         =    1;     // offset   996
    public static final int VALIDATE_ES_SIZE                         =    1;     // offset   997
    public static final int ALREADY_SENT_ES_SIZE                     =    1;     // offset   998
    public static final int ABI_STATUS_ES_SIZE                       =    1;     // offset   999
    public static final int CERTIFICATION_ES_SIZE                    =    1;     // offset  1000
    public static final int FILE_OPENED_FOR_NO_CREDIT_SIZE           =    1;     // offset  1001
    public static final int CREDIT_LIMIT_CODE_SIZE                   =    1;     // offset  1002
    public static final int VESSEL_FLAG_SIZE                         =    2;     // offset  1003
    public static final int HIGH_SEB_CHG_SIZE                        =    1;     // offset  1005
    public static final int ABI_ENTRY_SUMMARY_SIZE                   =    1;     // offset  1006
    public static final int DESTINATION_STATE_SIZE                   =    2;     // offset  1007
    public static final int VALUE_STATEMENT_SIZE                     =    1;     // offset  1009
    public static final int CHARGES_SIZE                             =   11;     // offset  1010
    public static final int CHARGES_VALUE_REMAINING_SIZE             =   11;     // offset  1021
    public static final int CHARGES_REMAINING_SIZE                   =   11;     // offset  1032
    public static final int MULTIPLE_EXPORT_SIZE                     =    1;     // offset  1043
    public static final int WEIGHT_REMAINING_SIZE                    =   12;     // offset  1044
    public static final int WEIGHT_VALUE_REMAINING_SIZE              =   11;     // offset  1056
    public static final int PRINT_DUTY_LINES_SIZE                    =    1;     // offset  1067
    public static final int SEND_DUTY_LINES_SIZE                     =    1;     // offset  1068
    public static final int VALUE_US_SIZE                            =   13;     // offset  1069
    public static final int CURRENCY_SIZE                            =    3;     // offset  1082
    public static final int EXCHANGE_RATE_SIZE                       =    8;     // offset  1085
    public static final int USER_ENTERED_WEIGHT_TOTAL_SIZE           =   12;     // offset  1093
    public static final int USER_ENTERED_WEIGHT_VALUE_SIZE           =   13;     // offset  1105
    public static final int USER_ENTERED_CHARGES_TOTAL_SIZE          =   11;     // offset  1118
    public static final int USER_ENTERED_CHARGES_VALUE_SIZE          =   13;     // offset  1129
    public static final int DUTY_DIF_SIZE                            =   11;     // offset  1142
    public static final int CONVERT_FOR_ES_SIZE                      =    1;     // offset  1153
    public static final int CONVERT_FOR_CR_SIZE                      =    1;     // offset  1154
    public static final int DATE_ENTRY_SIZE                          =    8;     // offset  1155
    public static final int VALIDATION_DIVISION_SIZE                 =    4;     // offset  1163
    public static final int UOM_VOLUME_SIZE                          =    6;     // offset  1167
    public static final int ABI_BRANCH_DESIGNATION_SIZE              =    2;     // offset  1173
    public static final int MESSAGE_NO_1_SIZE                        =    4;     // offset  1175
    public static final int MESSAGE_NO_2_SIZE                        =    4;     // offset  1179
    public static final int MESSAGE_NO_3_SIZE                        =    4;     // offset  1183
    public static final int FDA_DISPOSITION_SIZE                     =    2;     // offset  1187
    public static final int FDA_OUTPUT_MESS_SIZE                     =   33;     // offset  1189
    public static final int OGA_IDENTIFIER_SIZE                      =    3;     // offset  1222
    public static final int OGA_OUTPUT_MESS_SIZE                     =   33;     // offset  1225
    public static final int PAPERLESS_ES_SIZE                        =    1;     // offset  1258
    public static final int OGA_DISPOSITION_SIZE                     =    2;     // offset  1259
    public static final int PROTEST_NO_1_SIZE                        =   12;     // offset  1261
    public static final int PROTEST_TYPE_1_SIZE                      =    1;     // offset  1273
    public static final int PROTEST_STATUS_1_SIZE                    =    2;     // offset  1274
    public static final int PROTEST_SUMMONS_INDICATOR_1_SIZE         =    1;     // offset  1276
    public static final int PROTEST_NO_2_SIZE                        =   12;     // offset  1277
    public static final int PROTEST_TYPE_2_SIZE                      =    1;     // offset  1289
    public static final int PROTEST_STATUS_2_SIZE                    =    2;     // offset  1290
    public static final int PROTEST_SUMMONS_INDICATOR_2_SIZE         =    1;     // offset  1292
    public static final int STATEMENT_PAYABLE_SCHEDULED_SIZE         =    1;     // offset  1293
    public static final int OTHER_AMT_SIZE                           =   12;     // offset  1294
    public static final int MANUFACTURER_ID_SIZE                     =   15;     // offset  1306
    public static final int FDA_CORRECTION_SIZE                      =    1;     // offset  1321
    public static final int FCC_CORRECTION_SIZE                      =    1;     // offset  1322
    public static final int FWS_CORRECTION_SIZE                      =    1;     // offset  1323
    public static final int CHINVHDR_SIZE                            =    1;     // offset  1324
    public static final int CHSPCIHD_SIZE                            =    1;     // offset  1325
    public static final int CHSPCRHD_SIZE                            =    1;     // offset  1326
    public static final int CHSPESHD_SIZE                            =    1;     // offset  1327
    public static final int PRO_RATE_WEIGHT_SIZE                     =    1;     // offset  1328
    public static final int PRO_RATE_CHARGES_SIZE                    =    1;     // offset  1329
    public static final int CREDIT_CODE_SIZE                         =    1;     // offset  1330
    public static final int RELEASE_ORIGIN_SIZE                      =    2;     // offset  1331
    public static final int SHIPPER_SIZE                             =   10;     // offset  1333
    public static final int NCAP_OPEN_CLOSED_SIZE                    =    1;     // offset  1343
    public static final int NCAP_RELEASE_SIZE                        =    1;     // offset  1344
    public static final int NCAP_ENTRY_SUMMARY_SIZE                  =    1;     // offset  1345
    public static final int FILLER_1_SIZE                            =    1;     // offset  1346
    public static final int CUSTOMS_STATUS_SIZE                      =    1;     // offset  1347
    public static final int ALREADY_SENT_BR_SIZE                     =    1;     // offset  1348
    public static final int ERROR_FREE_BR_SIZE                       =    1;     // offset  1349
    public static final int ABI_BORDER_RELEASE_SIZE                  =    1;     // offset  1350
    public static final int MULTIPLE_CONSIGNEE_SIZE                  =    1;     // offset  1351
    public static final int PROVINCE_SIZE                            =    2;     // offset  1352
    public static final int USER_ENTERED_VALUE_SIZE                  =    1;     // offset  1354
    public static final int WATCH_FLAG_SIZE                          =    1;     // offset  1355
    public static final int SHIPMENT_TYPE_SIZE                       =    1;     // offset  1356
    public static final int CR_OTHER_SIZE                            =   12;     // offset  1357
    public static final int CR_VALUE_ENTERED_SIZE                    =   13;     // offset  1369
    public static final int DEDUCT_BROKERAGE_SIZE                    =    1;     // offset  1382
    public static final int LINE_RELEASED_SIZE                       =    1;     // offset  1383
    public static final int INT_EXAM_LOCATION_SIZE                   =    4;     // offset  1384
    public static final int EDI_UPLOADED_SIZE                        =    1;     // offset  1388
    public static final int BREAK_BULK_DIVISION_SIZE                 =    4;     // offset  1389
    public static final int CO_LOADED_SIZE                           =    1;     // offset  1393
    public static final int MASTER_LOADER_SIZE                       =   10;     // offset  1394
    public static final int MASTER_BILL_SIZE                         =   12;     // offset  1404
    public static final int MASTER_BILL_2_SIZE                       =   12;     // offset  1416
    public static final int PROFIT_ALLOC_METHOD_SIZE                 =    2;     // offset  1428
    public static final int ACTUAL_HBL_COUNT_SIZE                    =    3;     // offset  1430
    public static final int CONTROL_HBL_COUNT_SIZE                   =    3;     // offset  1433
    public static final int BB_SHIPMENT_TYPE_SIZE                    =    1;     // offset  1436
    public static final int TYPE_FORMAL_INFORMAL_ETC_SIZE            =    1;     // offset  1437
    public static final int FINAL_WITHDRAWAL_SIZE                    =    1;     // offset  1438
    public static final int LCL_FCL_FLAG_SIZE                        =    1;     // offset  1439
    public static final int CHARGEABLE_WEIGHT_SIZE                   =    7;     // offset  1440
    public static final int ADD_CONSIGNEE_SIZE                       =    1;     // offset  1447
    public static final int VALUE_FOREIGN_SIZE                       =   13;     // offset  1448
    public static final int TIB_FEES_TOT_SIZE                        =   12;     // offset  1461
    public static final int BB_OPEN_CLOSED_SIZE                      =    1;     // offset  1473
    public static final int AIRPORT_CODE_SIZE                        =    3;     // offset  1474
    public static final int TRANSPORT_SIZE                           =    1;     // offset  1477
    public static final int BIRD_FILER_SIZE                          =    3;     // offset  1478
    public static final int EDI_ADD_SCREEN_SEQ_SIZE                  =    1;     // offset  1481
    public static final int AEI_UPLOAD_SIZE                          =    1;     // offset  1482
    public static final int BUSINESS_PRODUCT_SIZE                    =    4;     // offset  1483
    public static final int BIRD_REF_SIZE                            =   20;     // offset  1487
    public static final int TIB_BOND_110_SIZE                        =    1;     // offset  1507
    public static final int CI_TOT_TO_BILL_SIZE                      =    3;     // offset  1508
    public static final int ENTRY_DATE_BASIS_SIZE                    =    1;     // offset  1511
    public static final int RND_VALUE_ENTERED_SIZE                   =   13;     // offset  1512
    public static final int REQ_SWL_PERMIT_SIZE                      =    1;     // offset  1525
    public static final int ESTIMATED_VALUE_SIZE                     =   11;     // offset  1526
    public static final int ESTIMATED_FREIGHT_SIZE                   =   10;     // offset  1537
    public static final int FDA_RELEASE_NO_SIZE                      =    7;     // offset  1547
    public static final int SHIP_ID_SIZE                             =   30;     // offset  1554
    public static final int ISSUER_DUNS_NO_SIZE                      =   11;     // offset  1584
    public static final int TRANS_REF_NO_SIZE                        =   35;     // offset  1595
    public static final int SHIPMENT_STATUS_SIZE                     =    1;     // offset  1630
    public static final int DEFERRAL_CLAIM_TYPE_SIZE                 =    3;     // offset  1631
    public static final int DEFERRAL_PART_INDICATOR_SIZE             =    1;     // offset  1634
    public static final int ENTRY_LIST_DISCLAIMER_SIZE               =    1;     // offset  1635
    public static final int DUTY_DEFERRED_SIZE                       =   12;     // offset  1636
    public static final int FOREIGN_DUTY_DEFERRED_SIZE               =   12;     // offset  1648
    public static final int TOT_DUTY_RECEIVED_SIZE                   =   15;     // offset  1660
    public static final int PROCESS_9802_SIZE                        =    1;     // offset  1675
    public static final int SKIP_BILLING_SIZE                        =    1;     // offset  1676
    public static final int IT_PORT_SIZE                             =    4;     // offset  1677
    public static final int RECON_NAFTA_SIZE                         =    1;     // offset  1681
    public static final int RECON_CLASS_SIZE                         =    1;     // offset  1682
    public static final int RECON_VALUE_SIZE                         =    1;     // offset  1683
    public static final int RECON_9802_SIZE                          =    1;     // offset  1684
    public static final int BOND_PRODUCER_ACCOUNT_SIZE               =   10;     // offset  1685
    public static final int ITAR_SIZE                                =    1;     // offset  1695
    public static final int BB_CONCEPT_SIZE                          =   10;     // offset  1696
    public static final int SQ_RELEASED_SIZE                         =    1;     // offset  1706
    public static final int AUTO_ES_SIZE                             =    1;     // offset  1707
    public static final int ESTIMATED_VALUE_FLAG_SIZE                =    1;     // offset  1708
    public static final int AUTO_BILLING_SIZE                        =    1;     // offset  1709
    public static final int ITDS_SIZE                                =    1;     // offset  1710
    public static final int RND_RCLS_VAL_ENTERED_SIZE                =   13;     // offset  1711
    public static final int INT_AMT_LIQUIDATED_SIZE                  =   12;     // offset  1724
    public static final int RLF_TRANSACTION_SIZE                     =    1;     // offset  1736
    public static final int PREPAID_COLLECT_SIZE                     =    1;     // offset  1737
    public static final int USCS_ENTRY_TYPE_SIZE                     =    2;     // offset  1738
    public static final int AII_ACCEPTED_SIZE                        =    1;     // offset  1740
    public static final int SEND_BCS_SIZE                            =    1;     // offset  1741
    public static final int FILLER_SIZE                              =    8;     // offset  1742

    // Array offsets
    public static final int SEARCH_SHIPMENT_HEADER_OFFSET            = 0;
    public static final int FILE_NO_OFFSET                           =  0;
    public static final int CUST_NO_OFFSET                           =  10;
    public static final int DATE_REVERSE_JULIAN_LOG_OFFSET           =  20;
    public static final int VESSEL_AIRLINE_NAME_OFFSET               =  26;
    public static final int OPEN_CLOSED_OFFSET                       =  46;
    public static final int COMPANY_NO_OFFSET                        =  47;
    public static final int DIVISION_NO_OFFSET                       =  49;
    public static final int TIB_EXTENSIONS_OFFSET                    =  53;
    public static final int CI_TOT_ENTERED_OFFSET                    =  54;
    public static final int PORT_LADING_OFFSET                       =  59;
    public static final int DIST_PORT_OFFSET                         =  64;
    public static final int BROKER_FILER_OFFSET                      =  68;
    public static final int ENTRY_NO_OFFSET                          =  71;
    public static final int CONCEPT_OFFSET                           =  80;
    public static final int ENTRY_TYPE_OFFSET                        =  90;
    public static final int MOT_OFFSET                               =  92;
    public static final int CARRIER_OFFSET                           =  94;
    public static final int VOYAGE_FLIGHT_NO_OFFSET                  =  98;
    public static final int BROKER_TEAM_OFFSET                       =  108;
    public static final int BOND_TYPE_OFFSET                         =  112;
    public static final int CERTIFICATION_CR_ES_OFFSET               =  113;
    public static final int BOND_SURETY_OFFSET                       =  114;
    public static final int BOND_AMT_OFFSET                          =  117;
    public static final int SHIPPER_NAME_OFFSET                      =  128;
    public static final int DESC_OF_GOODS_OFFSET                     =  163;
    public static final int DIST_PORT_ENTRY_OFFSET                   =  233;
    public static final int COUNTRY_EXPORT_OFFSET                    =  237;
    public static final int COUNTRY_ORIGIN_OFFSET                    =  239;
    public static final int PIECE_COUNT_OFFSET                       =  241;
    public static final int UOM_OFFSET                               =  253;
    public static final int WEIGHT_GROSS_OFFSET                      =  259;
    public static final int UOM_WEIGHT_OFFSET                        =  271;
    public static final int VOLUME_TOT_OFFSET                        =  277;
    public static final int FREIGHT_VENDOR_NO_OFFSET                 =  289;
    public static final int LOCATION_OFFSET                          =  299;
    public static final int LOCATION_OF_GOODS_OFFSET                 =  303;
    public static final int EXAM_TYPE_OFFSET                         =  338;
    public static final int EXAMINATION_LOCATION_OFFSET              =  340;
    public static final int VAN_DEVANNING_LOCATION_OFFSET            =  344;
    public static final int GENERAL_ORDER_WAREHOUSE_NO_OFFSET        =  379;
    public static final int CONSOLIDATED_PERSONAL_SAMPLE_OFFSET      =  391;
    public static final int CUSTOMS_TEAM_OFFSET                      =  392;
    public static final int USER_CLASS_ID_OFFSET                     =  395;
    public static final int CUSTOMS_PRIORITY_OFFSET                  =  407;
    public static final int NON_ID_LIVE_ENTRY_OFFSET                 =  408;
    public static final int ENTRY_DATE_ELECTION_OFFSET               =  409;
    public static final int ENTRY_DATE_ESTIMATED_ACTUAL_OFFSET       =  410;
    public static final int SQUEEZE_IT_OFFSET                        =  411;
    public static final int NO_TIB_EXTENSIONS_OFFSET                 =  412;
    public static final int ADA_CVD_SURETY_OFFSET                    =  413;
    public static final int VALUE_ENTERED_OFFSET                     =  416;
    public static final int INTERNATIONAL_FREIGHT_CHARGES_OFFSET     =  429;
    public static final int INBOUND_CONSOLIDATOR_OFFSET              =  441;
    public static final int FORWARDER_OFFSET                         =  451;
    public static final int ACH_PAYMENT_OFFSET                       =  461;
    public static final int ABI_PAYMENT_TYPE_OFFSET                  =  462;
    public static final int IRS_TAX_DEFERRED_OFFSET                  =  463;
    public static final int IRS_TAX_DEFERRED_EFT_OFFSET              =  464;
    public static final int ABI_ENTRY_OFFSET                         =  465;
    public static final int RATE_PER_METER_OFFSET                    =  466;
    public static final int OVERRIDE_FILE_CLOSING_OFFSET             =  472;
    public static final int SIGNATURE_FOR_ES_OFFSET                  =  473;
    public static final int SIGNATURE_FOR_CR_OFFSET                  =  508;
    public static final int TRANSACTION_CONTROL_NO_OFFSET            =  543;
    public static final int MANIFEST_NO_OFFSET                       =  553;
    public static final int INLAND_BILL_OF_LADING_OFFSET             =  566;
    public static final int BROKER_YN_OFFSET                         =  579;
    public static final int LOW_HIGH_MPF_OFFSET                      =  580;
    public static final int MESSAGE_7501_OFFSET                      =  581;
    public static final int MESSAGE_TIB_OFFSET                       =  585;
    public static final int IMP_OR_OWNER_OFFSET                      =  589;
    public static final int MERCH_PURCHASED_OFFSET                   =  590;
    public static final int CONTAINER_TOT_OFFSET                     =  591;
    public static final int DO_TOT_OFFSET                            =  596;
    public static final int CI_TOT_OFFSET                            =  601;
    public static final int DUTY_AMT_LIQUIDATED_OFFSET               =  606;
    public static final int TAX_AMT_LIQUIDATED_OFFSET                =  618;
    public static final int FEE_AMT_LIQUIDATED_OFFSET                =  630;
    public static final int ADA_AMT_LIQUIDATED_OFFSET                =  642;
    public static final int CVD_AMT_LIQUIDATED_OFFSET                =  654;
    public static final int PROTEST_LIQUIDATION_OFFSET               =  666;
    public static final int TYPE_LIQUIDATION_OFFSET                  =  667;
    public static final int ACTION_LIQUIDATION_OFFSET                =  669;
    public static final int EXTEND_SUSPEND_LIQ_OFFSET                =  671;
    public static final int NO_EXTEND_SUSPEND_LIQUIDATION_OFFSET     =  673;
    public static final int CUSTOMS_DOC_FILING_LOC_OFFSET            =  674;
    public static final int DUTY_TOT_OFFSET                          =  692;
    public static final int TIB_DUTY_TOT_OFFSET                      =  704;
    public static final int TAX_DEFERRED_TOT_OFFSET                  =  716;
    public static final int TAX_NON_DEFERRED_TOT_OFFSET              =  728;
    public static final int FEES_TOT_OFFSET                          =  740;
    public static final int ADA_NON_BONDED_TOT_OFFSET                =  752;
    public static final int CVD_NON_BONDED_TOT_OFFSET                =  764;
    public static final int CVD_BONDED_TOT_OFFSET                    =  776;
    public static final int ADA_BONDED_TOT_OFFSET                    =  788;
    public static final int DUTY_FEES_TAXES_BILLED_TOT_OFFSET        =  800;
    public static final int DUTY_FEES_TAXES_PAID_TOT_OFFSET          =  812;
    public static final int CHECK_NO_FOR_DUTY_OFFSET                 =  824;
    public static final int DUTY_PAID_DIRECT_OFFSET                  =  834;
    public static final int DUTY_PAID_DIRECT_AMT_OFFSET              =  835;
    public static final int STATEMENT_NO_SHIPMENT_OFFSET             =  847;
    public static final int FREIGHT_BILLED_TOT_OFFSET                =  858;
    public static final int FREIGHT_PAID_TOT_OFFSET                  =  870;
    public static final int CHECK_NO_FOR_FREIGHT_OFFSET              =  882;
    public static final int FREIGHT_PAID_DIRECT_OFFSET               =  892;
    public static final int FREIGHT_PAID_DIRECT_AMT_OFFSET           =  893;
    public static final int BILLED_TO_DATE_TOT_OFFSET                =  905;
    public static final int PAID_BY_CLIENT_TOT_OFFSET                =  917;
    public static final int CR_PROCESSING_RESULTS_OFFSET             =  929;
    public static final int CR_DISPOSITION_OFFSET                    =  930;
    public static final int CR_CERTIFICATION_OUTPUT_MESS_OFFSET      =  932;
    public static final int EXAMINATION_OVERRIDDEN_OFFSET            =  965;
    public static final int CENSUS_WARNING_OFFSET                    =  966;
    public static final int SQUEEZED_OFFSET                          =  967;
    public static final int USER_CLASS_ID_CR_OFFSET                  =  968;
    public static final int USER_CLASS_ID_ES_OFFSET                  =  980;
    public static final int AII_TRANSACTION_OFFSET                   =  992;
    public static final int CERTIFICATION_CR_OFFSET                  =  993;
    public static final int ALREADY_SENT_CR_OFFSET                   =  994;
    public static final int ERROR_FREE_CR_OFFSET                     =  995;
    public static final int VALIDATE_CR_OFFSET                       =  996;
    public static final int VALIDATE_ES_OFFSET                       =  997;
    public static final int ALREADY_SENT_ES_OFFSET                   =  998;
    public static final int ABI_STATUS_ES_OFFSET                     =  999;
    public static final int CERTIFICATION_ES_OFFSET                  =  1000;
    public static final int FILE_OPENED_FOR_NO_CREDIT_OFFSET         =  1001;
    public static final int CREDIT_LIMIT_CODE_OFFSET                 =  1002;
    public static final int VESSEL_FLAG_OFFSET                       =  1003;
    public static final int HIGH_SEB_CHG_OFFSET                      =  1005;
    public static final int ABI_ENTRY_SUMMARY_OFFSET                 =  1006;
    public static final int DESTINATION_STATE_OFFSET                 =  1007;
    public static final int VALUE_STATEMENT_OFFSET                   =  1009;
    public static final int CHARGES_OFFSET                           =  1010;
    public static final int CHARGES_VALUE_REMAINING_OFFSET           =  1021;
    public static final int CHARGES_REMAINING_OFFSET                 =  1032;
    public static final int MULTIPLE_EXPORT_OFFSET                   =  1043;
    public static final int WEIGHT_REMAINING_OFFSET                  =  1044;
    public static final int WEIGHT_VALUE_REMAINING_OFFSET            =  1056;
    public static final int PRINT_DUTY_LINES_OFFSET                  =  1067;
    public static final int SEND_DUTY_LINES_OFFSET                   =  1068;
    public static final int VALUE_US_OFFSET                          =  1069;
    public static final int CURRENCY_OFFSET                          =  1082;
    public static final int EXCHANGE_RATE_OFFSET                     =  1085;
    public static final int USER_ENTERED_WEIGHT_TOTAL_OFFSET         =  1093;
    public static final int USER_ENTERED_WEIGHT_VALUE_OFFSET         =  1105;
    public static final int USER_ENTERED_CHARGES_TOTAL_OFFSET        =  1118;
    public static final int USER_ENTERED_CHARGES_VALUE_OFFSET        =  1129;
    public static final int DUTY_DIF_OFFSET                          =  1142;
    public static final int CONVERT_FOR_ES_OFFSET                    =  1153;
    public static final int CONVERT_FOR_CR_OFFSET                    =  1154;
    public static final int DATE_ENTRY_OFFSET                        =  1155;
    public static final int VALIDATION_DIVISION_OFFSET               =  1163;
    public static final int UOM_VOLUME_OFFSET                        =  1167;
    public static final int ABI_BRANCH_DESIGNATION_OFFSET            =  1173;
    public static final int MESSAGE_NO_1_OFFSET                      =  1175;
    public static final int MESSAGE_NO_2_OFFSET                      =  1179;
    public static final int MESSAGE_NO_3_OFFSET                      =  1183;
    public static final int FDA_DISPOSITION_OFFSET                   =  1187;
    public static final int FDA_OUTPUT_MESS_OFFSET                   =  1189;
    public static final int OGA_IDENTIFIER_OFFSET                    =  1222;
    public static final int OGA_OUTPUT_MESS_OFFSET                   =  1225;
    public static final int PAPERLESS_ES_OFFSET                      =  1258;
    public static final int OGA_DISPOSITION_OFFSET                   =  1259;
    public static final int PROTEST_NO_1_OFFSET                      =  1261;
    public static final int PROTEST_TYPE_1_OFFSET                    =  1273;
    public static final int PROTEST_STATUS_1_OFFSET                  =  1274;
    public static final int PROTEST_SUMMONS_INDICATOR_1_OFFSET       =  1276;
    public static final int PROTEST_NO_2_OFFSET                      =  1277;
    public static final int PROTEST_TYPE_2_OFFSET                    =  1289;
    public static final int PROTEST_STATUS_2_OFFSET                  =  1290;
    public static final int PROTEST_SUMMONS_INDICATOR_2_OFFSET       =  1292;
    public static final int STATEMENT_PAYABLE_SCHEDULED_OFFSET       =  1293;
    public static final int OTHER_AMT_OFFSET                         =  1294;
    public static final int MANUFACTURER_ID_OFFSET                   =  1306;
    public static final int FDA_CORRECTION_OFFSET                    =  1321;
    public static final int FCC_CORRECTION_OFFSET                    =  1322;
    public static final int FWS_CORRECTION_OFFSET                    =  1323;
    public static final int CHINVHDR_OFFSET                          =  1324;
    public static final int CHSPCIHD_OFFSET                          =  1325;
    public static final int CHSPCRHD_OFFSET                          =  1326;
    public static final int CHSPESHD_OFFSET                          =  1327;
    public static final int PRO_RATE_WEIGHT_OFFSET                   =  1328;
    public static final int PRO_RATE_CHARGES_OFFSET                  =  1329;
    public static final int CREDIT_CODE_OFFSET                       =  1330;
    public static final int RELEASE_ORIGIN_OFFSET                    =  1331;
    public static final int SHIPPER_OFFSET                           =  1333;
    public static final int NCAP_OPEN_CLOSED_OFFSET                  =  1343;
    public static final int NCAP_RELEASE_OFFSET                      =  1344;
    public static final int NCAP_ENTRY_SUMMARY_OFFSET                =  1345;
    public static final int FILLER_1_OFFSET                          =  1346;
    public static final int CUSTOMS_STATUS_OFFSET                    =  1347;
    public static final int ALREADY_SENT_BR_OFFSET                   =  1348;
    public static final int ERROR_FREE_BR_OFFSET                     =  1349;
    public static final int ABI_BORDER_RELEASE_OFFSET                =  1350;
    public static final int MULTIPLE_CONSIGNEE_OFFSET                =  1351;
    public static final int PROVINCE_OFFSET                          =  1352;
    public static final int USER_ENTERED_VALUE_OFFSET                =  1354;
    public static final int WATCH_FLAG_OFFSET                        =  1355;
    public static final int SHIPMENT_TYPE_OFFSET                     =  1356;
    public static final int CR_OTHER_OFFSET                          =  1357;
    public static final int CR_VALUE_ENTERED_OFFSET                  =  1369;
    public static final int DEDUCT_BROKERAGE_OFFSET                  =  1382;
    public static final int LINE_RELEASED_OFFSET                     =  1383;
    public static final int INT_EXAM_LOCATION_OFFSET                 =  1384;
    public static final int EDI_UPLOADED_OFFSET                      =  1388;
    public static final int BREAK_BULK_DIVISION_OFFSET               =  1389;
    public static final int CO_LOADED_OFFSET                         =  1393;
    public static final int MASTER_LOADER_OFFSET                     =  1394;
    public static final int MASTER_BILL_OFFSET                       =  1404;
    public static final int MASTER_BILL_2_OFFSET                     =  1416;
    public static final int PROFIT_ALLOC_METHOD_OFFSET               =  1428;
    public static final int ACTUAL_HBL_COUNT_OFFSET                  =  1430;
    public static final int CONTROL_HBL_COUNT_OFFSET                 =  1433;
    public static final int BB_SHIPMENT_TYPE_OFFSET                  =  1436;
    public static final int TYPE_FORMAL_INFORMAL_ETC_OFFSET          =  1437;
    public static final int FINAL_WITHDRAWAL_OFFSET                  =  1438;
    public static final int LCL_FCL_FLAG_OFFSET                      =  1439;
    public static final int CHARGEABLE_WEIGHT_OFFSET                 =  1440;
    public static final int ADD_CONSIGNEE_OFFSET                     =  1447;
    public static final int VALUE_FOREIGN_OFFSET                     =  1448;
    public static final int TIB_FEES_TOT_OFFSET                      =  1461;
    public static final int BB_OPEN_CLOSED_OFFSET                    =  1473;
    public static final int AIRPORT_CODE_OFFSET                      =  1474;
    public static final int TRANSPORT_OFFSET                         =  1477;
    public static final int BIRD_FILER_OFFSET                        =  1478;
    public static final int EDI_ADD_SCREEN_SEQ_OFFSET                =  1481;
    public static final int AEI_UPLOAD_OFFSET                        =  1482;
    public static final int BUSINESS_PRODUCT_OFFSET                  =  1483;
    public static final int BIRD_REF_OFFSET                          =  1487;
    public static final int TIB_BOND_110_OFFSET                      =  1507;
    public static final int CI_TOT_TO_BILL_OFFSET                    =  1508;
    public static final int ENTRY_DATE_BASIS_OFFSET                  =  1511;
    public static final int RND_VALUE_ENTERED_OFFSET                 =  1512;
    public static final int REQ_SWL_PERMIT_OFFSET                    =  1525;
    public static final int ESTIMATED_VALUE_OFFSET                   =  1526;
    public static final int ESTIMATED_FREIGHT_OFFSET                 =  1537;
    public static final int FDA_RELEASE_NO_OFFSET                    =  1547;
    public static final int SHIP_ID_OFFSET                           =  1554;
    public static final int ISSUER_DUNS_NO_OFFSET                    =  1584;
    public static final int TRANS_REF_NO_OFFSET                      =  1595;
    public static final int SHIPMENT_STATUS_OFFSET                   =  1630;
    public static final int DEFERRAL_CLAIM_TYPE_OFFSET               =  1631;
    public static final int DEFERRAL_PART_INDICATOR_OFFSET           =  1634;
    public static final int ENTRY_LIST_DISCLAIMER_OFFSET             =  1635;
    public static final int DUTY_DEFERRED_OFFSET                     =  1636;
    public static final int FOREIGN_DUTY_DEFERRED_OFFSET             =  1648;
    public static final int TOT_DUTY_RECEIVED_OFFSET                 =  1660;
    public static final int PROCESS_9802_OFFSET                      =  1675;
    public static final int SKIP_BILLING_OFFSET                      =  1676;
    public static final int IT_PORT_OFFSET                           =  1677;
    public static final int RECON_NAFTA_OFFSET                       =  1681;
    public static final int RECON_CLASS_OFFSET                       =  1682;
    public static final int RECON_VALUE_OFFSET                       =  1683;
    public static final int RECON_9802_OFFSET                        =  1684;
    public static final int BOND_PRODUCER_ACCOUNT_OFFSET             =  1685;
    public static final int ITAR_OFFSET                              =  1695;
    public static final int BB_CONCEPT_OFFSET                        =  1696;
    public static final int SQ_RELEASED_OFFSET                       =  1706;
    public static final int AUTO_ES_OFFSET                           =  1707;
    public static final int ESTIMATED_VALUE_FLAG_OFFSET              =  1708;
    public static final int AUTO_BILLING_OFFSET                      =  1709;
    public static final int ITDS_OFFSET                              =  1710;
    public static final int RND_RCLS_VAL_ENTERED_OFFSET              =  1711;
    public static final int INT_AMT_LIQUIDATED_OFFSET                =  1724;
    public static final int RLF_TRANSACTION_OFFSET                   =  1736;
    public static final int PREPAID_COLLECT_OFFSET                   =  1737;
    public static final int USCS_ENTRY_TYPE_OFFSET                   =  1738;
    public static final int AII_ACCEPTED_OFFSET                      =  1740;
    public static final int SEND_BCS_OFFSET                          =  1741;
    public static final int FILLER_OFFSET                            =  1742;

    // Data Types
    public static final String SEARCH_SHIPMENT_HEADER_TYPE            =  CHARACTER_TYPE;
    public static final String FILE_NO_TYPE                           =  ZONED_NUMERIC_TYPE;
    public static final String CUST_NO_TYPE                           =  CHARACTER_TYPE;
    public static final String DATE_REVERSE_JULIAN_LOG_TYPE           =  ZONED_NUMERIC_TYPE;
    public static final String VESSEL_AIRLINE_NAME_TYPE               =  CHARACTER_TYPE;
    public static final String OPEN_CLOSED_TYPE                       =  CHARACTER_TYPE;
    public static final String COMPANY_NO_TYPE                        =  ZONED_NUMERIC_TYPE;
    public static final String DIVISION_NO_TYPE                       =  ZONED_NUMERIC_TYPE;
    public static final String TIB_EXTENSIONS_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String CI_TOT_ENTERED_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String PORT_LADING_TYPE                       =  ZONED_NUMERIC_TYPE;
    public static final String DIST_PORT_TYPE                         =  ZONED_NUMERIC_TYPE;
    public static final String BROKER_FILER_TYPE                      =  CHARACTER_TYPE;
    public static final String ENTRY_NO_TYPE                          =  ZONED_NUMERIC_TYPE;
    public static final String CONCEPT_TYPE                           =  CHARACTER_TYPE;
    public static final String ENTRY_TYPE_TYPE                        =  ZONED_NUMERIC_TYPE;
    public static final String MOT_TYPE                               =  ZONED_NUMERIC_TYPE;
    public static final String CARRIER_TYPE                           =  CHARACTER_TYPE;
    public static final String VOYAGE_FLIGHT_NO_TYPE                  =  CHARACTER_TYPE;
    public static final String BROKER_TEAM_TYPE                       =  CHARACTER_TYPE;
    public static final String BOND_TYPE_TYPE                         =  CHARACTER_TYPE;
    public static final String CERTIFICATION_CR_ES_TYPE               =  CHARACTER_TYPE;
    public static final String BOND_SURETY_TYPE                       =  ZONED_NUMERIC_TYPE;
    public static final String BOND_AMT_TYPE                          =  ZONED_NUMERIC_TYPE;
    public static final String SHIPPER_NAME_TYPE                      =  CHARACTER_TYPE;
    public static final String DESC_OF_GOODS_TYPE                     =  CHARACTER_TYPE;
    public static final String DIST_PORT_ENTRY_TYPE                   =  ZONED_NUMERIC_TYPE;
    public static final String COUNTRY_EXPORT_TYPE                    =  CHARACTER_TYPE;
    public static final String COUNTRY_ORIGIN_TYPE                    =  CHARACTER_TYPE;
    public static final String PIECE_COUNT_TYPE                       =  ZONED_NUMERIC_TYPE;
    public static final String UOM_TYPE                               =  CHARACTER_TYPE;
    public static final String WEIGHT_GROSS_TYPE                      =  ZONED_NUMERIC_TYPE;
    public static final String UOM_WEIGHT_TYPE                        =  CHARACTER_TYPE;
    public static final String VOLUME_TOT_TYPE                        =  ZONED_NUMERIC_TYPE;
    public static final String FREIGHT_VENDOR_NO_TYPE                 =  CHARACTER_TYPE;
    public static final String LOCATION_TYPE                          =  CHARACTER_TYPE;
    public static final String LOCATION_OF_GOODS_TYPE                 =  CHARACTER_TYPE;
    public static final String EXAM_TYPE_TYPE                         =  ZONED_NUMERIC_TYPE;
    public static final String EXAMINATION_LOCATION_TYPE              =  CHARACTER_TYPE;
    public static final String VAN_DEVANNING_LOCATION_TYPE            =  CHARACTER_TYPE;
    public static final String GENERAL_ORDER_WAREHOUSE_NO_TYPE        =  CHARACTER_TYPE;
    public static final String CONSOLIDATED_PERSONAL_SAMPLE_TYPE      =  CHARACTER_TYPE;
    public static final String CUSTOMS_TEAM_TYPE                      =  CHARACTER_TYPE;
    public static final String USER_CLASS_ID_TYPE                     =  CHARACTER_TYPE;
    public static final String CUSTOMS_PRIORITY_TYPE                  =  ZONED_NUMERIC_TYPE;
    public static final String NON_ID_LIVE_ENTRY_TYPE                 =  CHARACTER_TYPE;
    public static final String ENTRY_DATE_ELECTION_TYPE               =  CHARACTER_TYPE;
    public static final String ENTRY_DATE_ESTIMATED_ACTUAL_TYPE       =  CHARACTER_TYPE;
    public static final String SQUEEZE_IT_TYPE                        =  CHARACTER_TYPE;
    public static final String NO_TIB_EXTENSIONS_TYPE                 =  ZONED_NUMERIC_TYPE;
    public static final String ADA_CVD_SURETY_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String VALUE_ENTERED_TYPE                     =  ZONED_NUMERIC_TYPE;
    public static final String INTERNATIONAL_FREIGHT_CHARGES_TYPE     =  ZONED_NUMERIC_TYPE;
    public static final String INBOUND_CONSOLIDATOR_TYPE              =  CHARACTER_TYPE;
    public static final String FORWARDER_TYPE                         =  CHARACTER_TYPE;
    public static final String ACH_PAYMENT_TYPE                       =  CHARACTER_TYPE;
    public static final String ABI_PAYMENT_TYPE_TYPE                  =  ZONED_NUMERIC_TYPE;
    public static final String IRS_TAX_DEFERRED_TYPE                  =  CHARACTER_TYPE;
    public static final String IRS_TAX_DEFERRED_EFT_TYPE              =  CHARACTER_TYPE;
    public static final String ABI_ENTRY_TYPE                         =  CHARACTER_TYPE;
    public static final String RATE_PER_METER_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String OVERRIDE_FILE_CLOSING_TYPE             =  CHARACTER_TYPE;
    public static final String SIGNATURE_FOR_ES_TYPE                  =  CHARACTER_TYPE;
    public static final String SIGNATURE_FOR_CR_TYPE                  =  CHARACTER_TYPE;
    public static final String TRANSACTION_CONTROL_NO_TYPE            =  ZONED_NUMERIC_TYPE;
    public static final String MANIFEST_NO_TYPE                       =  CHARACTER_TYPE;
    public static final String INLAND_BILL_OF_LADING_TYPE             =  CHARACTER_TYPE;
    public static final String BROKER_YN_TYPE                         =  CHARACTER_TYPE;
    public static final String LOW_HIGH_MPF_TYPE                      =  CHARACTER_TYPE;
    public static final String MESSAGE_7501_TYPE                      =  CHARACTER_TYPE;
    public static final String MESSAGE_TIB_TYPE                       =  CHARACTER_TYPE;
    public static final String IMP_OR_OWNER_TYPE                      =  CHARACTER_TYPE;
    public static final String MERCH_PURCHASED_TYPE                   =  CHARACTER_TYPE;
    public static final String CONTAINER_TOT_TYPE                     =  ZONED_NUMERIC_TYPE;
    public static final String DO_TOT_TYPE                            =  ZONED_NUMERIC_TYPE;
    public static final String CI_TOT_TYPE                            =  ZONED_NUMERIC_TYPE;
    public static final String DUTY_AMT_LIQUIDATED_TYPE               =  ZONED_NUMERIC_TYPE;
    public static final String TAX_AMT_LIQUIDATED_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String FEE_AMT_LIQUIDATED_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String ADA_AMT_LIQUIDATED_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String CVD_AMT_LIQUIDATED_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String PROTEST_LIQUIDATION_TYPE               =  CHARACTER_TYPE;
    public static final String TYPE_LIQUIDATION_TYPE                  =  ZONED_NUMERIC_TYPE;
    public static final String ACTION_LIQUIDATION_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String EXTEND_SUSPEND_LIQ_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String NO_EXTEND_SUSPEND_LIQUIDATION_TYPE     =  ZONED_NUMERIC_TYPE;
    public static final String CUSTOMS_DOC_FILING_LOC_TYPE            =  CHARACTER_TYPE;
    public static final String DUTY_TOT_TYPE                          =  ZONED_NUMERIC_TYPE;
    public static final String TIB_DUTY_TOT_TYPE                      =  ZONED_NUMERIC_TYPE;
    public static final String TAX_DEFERRED_TOT_TYPE                  =  ZONED_NUMERIC_TYPE;
    public static final String TAX_NON_DEFERRED_TOT_TYPE              =  ZONED_NUMERIC_TYPE;
    public static final String FEES_TOT_TYPE                          =  ZONED_NUMERIC_TYPE;
    public static final String ADA_NON_BONDED_TOT_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String CVD_NON_BONDED_TOT_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String CVD_BONDED_TOT_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String ADA_BONDED_TOT_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String DUTY_FEES_TAXES_BILLED_TOT_TYPE        =  ZONED_NUMERIC_TYPE;
    public static final String DUTY_FEES_TAXES_PAID_TOT_TYPE          =  ZONED_NUMERIC_TYPE;
    public static final String CHECK_NO_FOR_DUTY_TYPE                 =  ZONED_NUMERIC_TYPE;
    public static final String DUTY_PAID_DIRECT_TYPE                  =  CHARACTER_TYPE;
    public static final String DUTY_PAID_DIRECT_AMT_TYPE              =  ZONED_NUMERIC_TYPE;
    public static final String STATEMENT_NO_SHIPMENT_TYPE             =  CHARACTER_TYPE;
    public static final String FREIGHT_BILLED_TOT_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String FREIGHT_PAID_TOT_TYPE                  =  ZONED_NUMERIC_TYPE;
    public static final String CHECK_NO_FOR_FREIGHT_TYPE              =  ZONED_NUMERIC_TYPE;
    public static final String FREIGHT_PAID_DIRECT_TYPE               =  CHARACTER_TYPE;
    public static final String FREIGHT_PAID_DIRECT_AMT_TYPE           =  ZONED_NUMERIC_TYPE;
    public static final String BILLED_TO_DATE_TOT_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String PAID_BY_CLIENT_TOT_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String CR_PROCESSING_RESULTS_TYPE             =  CHARACTER_TYPE;
    public static final String CR_DISPOSITION_TYPE                    =  CHARACTER_TYPE;
    public static final String CR_CERTIFICATION_OUTPUT_MESS_TYPE      =  CHARACTER_TYPE;
    public static final String EXAMINATION_OVERRIDDEN_TYPE            =  CHARACTER_TYPE;
    public static final String CENSUS_WARNING_TYPE                    =  CHARACTER_TYPE;
    public static final String SQUEEZED_TYPE                          =  CHARACTER_TYPE;
    public static final String USER_CLASS_ID_CR_TYPE                  =  CHARACTER_TYPE;
    public static final String USER_CLASS_ID_ES_TYPE                  =  CHARACTER_TYPE;
    public static final String AII_TRANSACTION_TYPE                   =  CHARACTER_TYPE;
    public static final String CERTIFICATION_CR_TYPE                  =  CHARACTER_TYPE;
    public static final String ALREADY_SENT_CR_TYPE                   =  CHARACTER_TYPE;
    public static final String ERROR_FREE_CR_TYPE                     =  CHARACTER_TYPE;
    public static final String VALIDATE_CR_TYPE                       =  CHARACTER_TYPE;
    public static final String VALIDATE_ES_TYPE                       =  CHARACTER_TYPE;
    public static final String ALREADY_SENT_ES_TYPE                   =  CHARACTER_TYPE;
    public static final String ABI_STATUS_ES_TYPE                     =  CHARACTER_TYPE;
    public static final String CERTIFICATION_ES_TYPE                  =  CHARACTER_TYPE;
    public static final String FILE_OPENED_FOR_NO_CREDIT_TYPE         =  CHARACTER_TYPE;
    public static final String CREDIT_LIMIT_CODE_TYPE                 =  CHARACTER_TYPE;
    public static final String VESSEL_FLAG_TYPE                       =  CHARACTER_TYPE;
    public static final String HIGH_SEB_CHG_TYPE                      =  CHARACTER_TYPE;
    public static final String ABI_ENTRY_SUMMARY_TYPE                 =  CHARACTER_TYPE;
    public static final String DESTINATION_STATE_TYPE                 =  CHARACTER_TYPE;
    public static final String VALUE_STATEMENT_TYPE                   =  CHARACTER_TYPE;
    public static final String CHARGES_TYPE                           =  ZONED_NUMERIC_TYPE;
    public static final String CHARGES_VALUE_REMAINING_TYPE           =  ZONED_NUMERIC_TYPE;
    public static final String CHARGES_REMAINING_TYPE                 =  ZONED_NUMERIC_TYPE;
    public static final String MULTIPLE_EXPORT_TYPE                   =  CHARACTER_TYPE;
    public static final String WEIGHT_REMAINING_TYPE                  =  ZONED_NUMERIC_TYPE;
    public static final String WEIGHT_VALUE_REMAINING_TYPE            =  ZONED_NUMERIC_TYPE;
    public static final String PRINT_DUTY_LINES_TYPE                  =  CHARACTER_TYPE;
    public static final String SEND_DUTY_LINES_TYPE                   =  CHARACTER_TYPE;
    public static final String VALUE_US_TYPE                          =  ZONED_NUMERIC_TYPE;
    public static final String CURRENCY_TYPE                          =  CHARACTER_TYPE;
    public static final String EXCHANGE_RATE_TYPE                     =  ZONED_NUMERIC_TYPE;
    public static final String USER_ENTERED_WEIGHT_TOTAL_TYPE         =  ZONED_NUMERIC_TYPE;
    public static final String USER_ENTERED_WEIGHT_VALUE_TYPE         =  ZONED_NUMERIC_TYPE;
    public static final String USER_ENTERED_CHARGES_TOTAL_TYPE        =  ZONED_NUMERIC_TYPE;
    public static final String USER_ENTERED_CHARGES_VALUE_TYPE        =  ZONED_NUMERIC_TYPE;
    public static final String DUTY_DIF_TYPE                          =  ZONED_NUMERIC_TYPE;
    public static final String CONVERT_FOR_ES_TYPE                    =  CHARACTER_TYPE;
    public static final String CONVERT_FOR_CR_TYPE                    =  CHARACTER_TYPE;
    public static final String DATE_ENTRY_TYPE                        =  ZONED_NUMERIC_TYPE;
    public static final String VALIDATION_DIVISION_TYPE               =  ZONED_NUMERIC_TYPE;
    public static final String UOM_VOLUME_TYPE                        =  CHARACTER_TYPE;
    public static final String ABI_BRANCH_DESIGNATION_TYPE            =  CHARACTER_TYPE;
    public static final String MESSAGE_NO_1_TYPE                      =  CHARACTER_TYPE;
    public static final String MESSAGE_NO_2_TYPE                      =  CHARACTER_TYPE;
    public static final String MESSAGE_NO_3_TYPE                      =  CHARACTER_TYPE;
    public static final String FDA_DISPOSITION_TYPE                   =  CHARACTER_TYPE;
    public static final String FDA_OUTPUT_MESS_TYPE                   =  CHARACTER_TYPE;
    public static final String OGA_IDENTIFIER_TYPE                    =  CHARACTER_TYPE;
    public static final String OGA_OUTPUT_MESS_TYPE                   =  CHARACTER_TYPE;
    public static final String PAPERLESS_ES_TYPE                      =  CHARACTER_TYPE;
    public static final String OGA_DISPOSITION_TYPE                   =  CHARACTER_TYPE;
    public static final String PROTEST_NO_1_TYPE                      =  ZONED_NUMERIC_TYPE;
    public static final String PROTEST_TYPE_1_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String PROTEST_STATUS_1_TYPE                  =  CHARACTER_TYPE;
    public static final String PROTEST_SUMMONS_INDICATOR_1_TYPE       =  ZONED_NUMERIC_TYPE;
    public static final String PROTEST_NO_2_TYPE                      =  ZONED_NUMERIC_TYPE;
    public static final String PROTEST_TYPE_2_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String PROTEST_STATUS_2_TYPE                  =  CHARACTER_TYPE;
    public static final String PROTEST_SUMMONS_INDICATOR_2_TYPE       =  ZONED_NUMERIC_TYPE;
    public static final String STATEMENT_PAYABLE_SCHEDULED_TYPE       =  CHARACTER_TYPE;
    public static final String OTHER_AMT_TYPE                         =  ZONED_NUMERIC_TYPE;
    public static final String MANUFACTURER_ID_TYPE                   =  CHARACTER_TYPE;
    public static final String FDA_CORRECTION_TYPE                    =  CHARACTER_TYPE;
    public static final String FCC_CORRECTION_TYPE                    =  CHARACTER_TYPE;
    public static final String FWS_CORRECTION_TYPE                    =  CHARACTER_TYPE;
    public static final String CHINVHDR_TYPE                          =  CHARACTER_TYPE;
    public static final String CHSPCIHD_TYPE                          =  CHARACTER_TYPE;
    public static final String CHSPCRHD_TYPE                          =  CHARACTER_TYPE;
    public static final String CHSPESHD_TYPE                          =  CHARACTER_TYPE;
    public static final String PRO_RATE_WEIGHT_TYPE                   =  CHARACTER_TYPE;
    public static final String PRO_RATE_CHARGES_TYPE                  =  CHARACTER_TYPE;
    public static final String CREDIT_CODE_TYPE                       =  CHARACTER_TYPE;
    public static final String RELEASE_ORIGIN_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String SHIPPER_TYPE                           =  CHARACTER_TYPE;
    public static final String NCAP_OPEN_CLOSED_TYPE                  =  CHARACTER_TYPE;
    public static final String NCAP_RELEASE_TYPE                      =  CHARACTER_TYPE;
    public static final String NCAP_ENTRY_SUMMARY_TYPE                =  CHARACTER_TYPE;
    public static final String FILLER_1_TYPE                          =  CHARACTER_TYPE;
    public static final String CUSTOMS_STATUS_TYPE                    =  CHARACTER_TYPE;
    public static final String ALREADY_SENT_BR_TYPE                   =  CHARACTER_TYPE;
    public static final String ERROR_FREE_BR_TYPE                     =  CHARACTER_TYPE;
    public static final String ABI_BORDER_RELEASE_TYPE                =  CHARACTER_TYPE;
    public static final String MULTIPLE_CONSIGNEE_TYPE                =  CHARACTER_TYPE;
    public static final String PROVINCE_TYPE                          =  CHARACTER_TYPE;
    public static final String USER_ENTERED_VALUE_TYPE                =  CHARACTER_TYPE;
    public static final String WATCH_FLAG_TYPE                        =  CHARACTER_TYPE;
    public static final String SHIPMENT_TYPE_TYPE                     =  CHARACTER_TYPE;
    public static final String CR_OTHER_TYPE                          =  ZONED_NUMERIC_TYPE;
    public static final String CR_VALUE_ENTERED_TYPE                  =  ZONED_NUMERIC_TYPE;
    public static final String DEDUCT_BROKERAGE_TYPE                  =  CHARACTER_TYPE;
    public static final String LINE_RELEASED_TYPE                     =  CHARACTER_TYPE;
    public static final String INT_EXAM_LOCATION_TYPE                 =  CHARACTER_TYPE;
    public static final String EDI_UPLOADED_TYPE                      =  CHARACTER_TYPE;
    public static final String BREAK_BULK_DIVISION_TYPE               =  ZONED_NUMERIC_TYPE;
    public static final String CO_LOADED_TYPE                         =  CHARACTER_TYPE;
    public static final String MASTER_LOADER_TYPE                     =  CHARACTER_TYPE;
    public static final String MASTER_BILL_TYPE                       =  CHARACTER_TYPE;
    public static final String MASTER_BILL_2_TYPE                     =  CHARACTER_TYPE;
    public static final String PROFIT_ALLOC_METHOD_TYPE               =  CHARACTER_TYPE;
    public static final String ACTUAL_HBL_COUNT_TYPE                  =  ZONED_NUMERIC_TYPE;
    public static final String CONTROL_HBL_COUNT_TYPE                 =  ZONED_NUMERIC_TYPE;
    public static final String BB_SHIPMENT_TYPE_TYPE                  =  CHARACTER_TYPE;
    public static final String TYPE_FORMAL_INFORMAL_ETC_TYPE          =  CHARACTER_TYPE;
    public static final String FINAL_WITHDRAWAL_TYPE                  =  CHARACTER_TYPE;
    public static final String LCL_FCL_FLAG_TYPE                      =  CHARACTER_TYPE;
    public static final String CHARGEABLE_WEIGHT_TYPE                 =  ZONED_NUMERIC_TYPE;
    public static final String ADD_CONSIGNEE_TYPE                     =  CHARACTER_TYPE;
    public static final String VALUE_FOREIGN_TYPE                     =  ZONED_NUMERIC_TYPE;
    public static final String TIB_FEES_TOT_TYPE                      =  ZONED_NUMERIC_TYPE;
    public static final String BB_OPEN_CLOSED_TYPE                    =  CHARACTER_TYPE;
    public static final String AIRPORT_CODE_TYPE                      =  CHARACTER_TYPE;
    public static final String TRANSPORT_TYPE                         =  CHARACTER_TYPE;
    public static final String BIRD_FILER_TYPE                        =  CHARACTER_TYPE;
    public static final String EDI_ADD_SCREEN_SEQ_TYPE                =  CHARACTER_TYPE;
    public static final String AEI_UPLOAD_TYPE                        =  CHARACTER_TYPE;
    public static final String BUSINESS_PRODUCT_TYPE                  =  CHARACTER_TYPE;
    public static final String BIRD_REF_TYPE                          =  CHARACTER_TYPE;
    public static final String TIB_BOND_110_TYPE                      =  CHARACTER_TYPE;
    public static final String CI_TOT_TO_BILL_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String ENTRY_DATE_BASIS_TYPE                  =  CHARACTER_TYPE;
    public static final String RND_VALUE_ENTERED_TYPE                 =  ZONED_NUMERIC_TYPE;
    public static final String REQ_SWL_PERMIT_TYPE                    =  CHARACTER_TYPE;
    public static final String ESTIMATED_VALUE_TYPE                   =  ZONED_NUMERIC_TYPE;
    public static final String ESTIMATED_FREIGHT_TYPE                 =  ZONED_NUMERIC_TYPE;
    public static final String FDA_RELEASE_NO_TYPE                    =  ZONED_NUMERIC_TYPE;
    public static final String SHIP_ID_TYPE                           =  CHARACTER_TYPE;
    public static final String ISSUER_DUNS_NO_TYPE                    =  CHARACTER_TYPE;
    public static final String TRANS_REF_NO_TYPE                      =  CHARACTER_TYPE;
    public static final String SHIPMENT_STATUS_TYPE                   =  CHARACTER_TYPE;
    public static final String DEFERRAL_CLAIM_TYPE_TYPE               =  CHARACTER_TYPE;
    public static final String DEFERRAL_PART_INDICATOR_TYPE           =  ZONED_NUMERIC_TYPE;
    public static final String ENTRY_LIST_DISCLAIMER_TYPE             =  CHARACTER_TYPE;
    public static final String DUTY_DEFERRED_TYPE                     =  ZONED_NUMERIC_TYPE;
    public static final String FOREIGN_DUTY_DEFERRED_TYPE             =  ZONED_NUMERIC_TYPE;
    public static final String TOT_DUTY_RECEIVED_TYPE                 =  ZONED_NUMERIC_TYPE;
    public static final String PROCESS_9802_TYPE                      =  CHARACTER_TYPE;
    public static final String SKIP_BILLING_TYPE                      =  CHARACTER_TYPE;
    public static final String IT_PORT_TYPE                           =  ZONED_NUMERIC_TYPE;
    public static final String RECON_NAFTA_TYPE                       =  CHARACTER_TYPE;
    public static final String RECON_CLASS_TYPE                       =  CHARACTER_TYPE;
    public static final String RECON_VALUE_TYPE                       =  CHARACTER_TYPE;
    public static final String RECON_9802_TYPE                        =  CHARACTER_TYPE;
    public static final String BOND_PRODUCER_ACCOUNT_TYPE             =  CHARACTER_TYPE;
    public static final String ITAR_TYPE                              =  CHARACTER_TYPE;
    public static final String BB_CONCEPT_TYPE                        =  CHARACTER_TYPE;
    public static final String SQ_RELEASED_TYPE                       =  CHARACTER_TYPE;
    public static final String AUTO_ES_TYPE                           =  CHARACTER_TYPE;
    public static final String ESTIMATED_VALUE_FLAG_TYPE              =  CHARACTER_TYPE;
    public static final String AUTO_BILLING_TYPE                      =  CHARACTER_TYPE;
    public static final String ITDS_TYPE                              =  CHARACTER_TYPE;
    public static final String RND_RCLS_VAL_ENTERED_TYPE              =  ZONED_NUMERIC_TYPE;
    public static final String INT_AMT_LIQUIDATED_TYPE                =  ZONED_NUMERIC_TYPE;
    public static final String RLF_TRANSACTION_TYPE                   =  CHARACTER_TYPE;
    public static final String PREPAID_COLLECT_TYPE                   =  CHARACTER_TYPE;
    public static final String USCS_ENTRY_TYPE_TYPE                   =  ZONED_NUMERIC_TYPE;
    public static final String AII_ACCEPTED_TYPE                      =  CHARACTER_TYPE;
    public static final String SEND_BCS_TYPE                          =  CHARACTER_TYPE;
    public static final String FILLER_TYPE                            =  CHARACTER_TYPE;

    public ShipmentHeaderImpl() {
        this(new char[SHIPMENT_HEADER_SIZE]);
    }
    
    public ShipmentHeaderImpl(char[] data_elements) {
        
        super();
        if (data_elements.length != SHIPMENT_HEADER_SIZE)
            data_elements = new char[SHIPMENT_HEADER_SIZE];
            
        for (int i = 0; i < SHIPMENT_HEADER_SIZE; i++) {
            data_elements[i] = ' ';
        }
        
        DATA_ELEMENT_SIZE = SHIPMENT_HEADER_SIZE;
        this.data_elements = data_elements;
    }
}
