// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: copybook_service.proto
#ifndef GRPC_copybook_5fservice_2eproto__INCLUDED
#define GRPC_copybook_5fservice_2eproto__INCLUDED

#include "copybook_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace copybook {
namespace transport {

// ── Service Definition ─────────────────────────────────────────────────
//
class CopybookService final {
 public:
  static constexpr char const* service_full_name() {
    return "copybook.transport.CopybookService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Send a raw COBOL buffer to the server for storage/processing.
    virtual ::grpc::Status SendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::copybook::transport::SendResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SendResponse>> AsyncSendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SendResponse>>(AsyncSendRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SendResponse>> PrepareAsyncSendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SendResponse>>(PrepareAsyncSendRecordRaw(context, request, cq));
    }
    // Extract named fields from a raw COBOL buffer.
    virtual ::grpc::Status GetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::copybook::transport::GetFieldsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::GetFieldsResponse>> AsyncGetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::GetFieldsResponse>>(AsyncGetFieldsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::GetFieldsResponse>> PrepareAsyncGetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::GetFieldsResponse>>(PrepareAsyncGetFieldsRaw(context, request, cq));
    }
    // Pack named field values into a raw COBOL buffer.
    virtual ::grpc::Status SetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::copybook::transport::SetFieldsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SetFieldsResponse>> AsyncSetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SetFieldsResponse>>(AsyncSetFieldsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SetFieldsResponse>> PrepareAsyncSetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SetFieldsResponse>>(PrepareAsyncSetFieldsRaw(context, request, cq));
    }
    // Get the schema for a specific copybook record.
    virtual ::grpc::Status GetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::copybook::transport::SchemaResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SchemaResponse>> AsyncGetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SchemaResponse>>(AsyncGetSchemaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SchemaResponse>> PrepareAsyncGetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SchemaResponse>>(PrepareAsyncGetSchemaRaw(context, request, cq));
    }
    // List all known copybook schemas.
    virtual ::grpc::Status ListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::copybook::transport::ListSchemasResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ListSchemasResponse>> AsyncListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ListSchemasResponse>>(AsyncListSchemasRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ListSchemasResponse>> PrepareAsyncListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ListSchemasResponse>>(PrepareAsyncListSchemasRaw(context, request, cq));
    }
    // Convert between raw buffer and JSON/YAML formats.
    virtual ::grpc::Status Convert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::copybook::transport::ConvertResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ConvertResponse>> AsyncConvert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ConvertResponse>>(AsyncConvertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ConvertResponse>> PrepareAsyncConvert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ConvertResponse>>(PrepareAsyncConvertRaw(context, request, cq));
    }
    // Stream records: client sends a stream of records, server acknowledges each.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>> StreamRecords(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>>(StreamRecordsRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>> AsyncStreamRecords(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>>(AsyncStreamRecordsRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>> PrepareAsyncStreamRecords(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>>(PrepareAsyncStreamRecordsRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Send a raw COBOL buffer to the server for storage/processing.
      virtual void SendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest* request, ::copybook::transport::SendResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest* request, ::copybook::transport::SendResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Extract named fields from a raw COBOL buffer.
      virtual void GetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest* request, ::copybook::transport::GetFieldsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest* request, ::copybook::transport::GetFieldsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Pack named field values into a raw COBOL buffer.
      virtual void SetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest* request, ::copybook::transport::SetFieldsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest* request, ::copybook::transport::SetFieldsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Get the schema for a specific copybook record.
      virtual void GetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest* request, ::copybook::transport::SchemaResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest* request, ::copybook::transport::SchemaResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // List all known copybook schemas.
      virtual void ListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest* request, ::copybook::transport::ListSchemasResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest* request, ::copybook::transport::ListSchemasResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Convert between raw buffer and JSON/YAML formats.
      virtual void Convert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest* request, ::copybook::transport::ConvertResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Convert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest* request, ::copybook::transport::ConvertResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Stream records: client sends a stream of records, server acknowledges each.
      virtual void StreamRecords(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::copybook::transport::SendRequest,::copybook::transport::SendResponse>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SendResponse>* AsyncSendRecordRaw(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SendResponse>* PrepareAsyncSendRecordRaw(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::GetFieldsResponse>* AsyncGetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::GetFieldsResponse>* PrepareAsyncGetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SetFieldsResponse>* AsyncSetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SetFieldsResponse>* PrepareAsyncSetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SchemaResponse>* AsyncGetSchemaRaw(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::SchemaResponse>* PrepareAsyncGetSchemaRaw(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ListSchemasResponse>* AsyncListSchemasRaw(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ListSchemasResponse>* PrepareAsyncListSchemasRaw(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ConvertResponse>* AsyncConvertRaw(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::copybook::transport::ConvertResponse>* PrepareAsyncConvertRaw(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* StreamRecordsRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* AsyncStreamRecordsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* PrepareAsyncStreamRecordsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::copybook::transport::SendResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SendResponse>> AsyncSendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SendResponse>>(AsyncSendRecordRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SendResponse>> PrepareAsyncSendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SendResponse>>(PrepareAsyncSendRecordRaw(context, request, cq));
    }
    ::grpc::Status GetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::copybook::transport::GetFieldsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::GetFieldsResponse>> AsyncGetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::GetFieldsResponse>>(AsyncGetFieldsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::GetFieldsResponse>> PrepareAsyncGetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::GetFieldsResponse>>(PrepareAsyncGetFieldsRaw(context, request, cq));
    }
    ::grpc::Status SetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::copybook::transport::SetFieldsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SetFieldsResponse>> AsyncSetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SetFieldsResponse>>(AsyncSetFieldsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SetFieldsResponse>> PrepareAsyncSetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SetFieldsResponse>>(PrepareAsyncSetFieldsRaw(context, request, cq));
    }
    ::grpc::Status GetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::copybook::transport::SchemaResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SchemaResponse>> AsyncGetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SchemaResponse>>(AsyncGetSchemaRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SchemaResponse>> PrepareAsyncGetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::SchemaResponse>>(PrepareAsyncGetSchemaRaw(context, request, cq));
    }
    ::grpc::Status ListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::copybook::transport::ListSchemasResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::ListSchemasResponse>> AsyncListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::ListSchemasResponse>>(AsyncListSchemasRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::ListSchemasResponse>> PrepareAsyncListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::ListSchemasResponse>>(PrepareAsyncListSchemasRaw(context, request, cq));
    }
    ::grpc::Status Convert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::copybook::transport::ConvertResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::ConvertResponse>> AsyncConvert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::ConvertResponse>>(AsyncConvertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::ConvertResponse>> PrepareAsyncConvert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::copybook::transport::ConvertResponse>>(PrepareAsyncConvertRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>> StreamRecords(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>>(StreamRecordsRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>> AsyncStreamRecords(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>>(AsyncStreamRecordsRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>> PrepareAsyncStreamRecords(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>>(PrepareAsyncStreamRecordsRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest* request, ::copybook::transport::SendResponse* response, std::function<void(::grpc::Status)>) override;
      void SendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest* request, ::copybook::transport::SendResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest* request, ::copybook::transport::GetFieldsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest* request, ::copybook::transport::GetFieldsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest* request, ::copybook::transport::SetFieldsResponse* response, std::function<void(::grpc::Status)>) override;
      void SetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest* request, ::copybook::transport::SetFieldsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest* request, ::copybook::transport::SchemaResponse* response, std::function<void(::grpc::Status)>) override;
      void GetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest* request, ::copybook::transport::SchemaResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest* request, ::copybook::transport::ListSchemasResponse* response, std::function<void(::grpc::Status)>) override;
      void ListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest* request, ::copybook::transport::ListSchemasResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Convert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest* request, ::copybook::transport::ConvertResponse* response, std::function<void(::grpc::Status)>) override;
      void Convert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest* request, ::copybook::transport::ConvertResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void StreamRecords(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::copybook::transport::SendRequest,::copybook::transport::SendResponse>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::SendResponse>* AsyncSendRecordRaw(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::SendResponse>* PrepareAsyncSendRecordRaw(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::GetFieldsResponse>* AsyncGetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::GetFieldsResponse>* PrepareAsyncGetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::SetFieldsResponse>* AsyncSetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::SetFieldsResponse>* PrepareAsyncSetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::SchemaResponse>* AsyncGetSchemaRaw(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::SchemaResponse>* PrepareAsyncGetSchemaRaw(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::ListSchemasResponse>* AsyncListSchemasRaw(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::ListSchemasResponse>* PrepareAsyncListSchemasRaw(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::ConvertResponse>* AsyncConvertRaw(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::copybook::transport::ConvertResponse>* PrepareAsyncConvertRaw(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* StreamRecordsRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* AsyncStreamRecordsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* PrepareAsyncStreamRecordsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendRecord_;
    const ::grpc::internal::RpcMethod rpcmethod_GetFields_;
    const ::grpc::internal::RpcMethod rpcmethod_SetFields_;
    const ::grpc::internal::RpcMethod rpcmethod_GetSchema_;
    const ::grpc::internal::RpcMethod rpcmethod_ListSchemas_;
    const ::grpc::internal::RpcMethod rpcmethod_Convert_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamRecords_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Send a raw COBOL buffer to the server for storage/processing.
    virtual ::grpc::Status SendRecord(::grpc::ServerContext* context, const ::copybook::transport::SendRequest* request, ::copybook::transport::SendResponse* response);
    // Extract named fields from a raw COBOL buffer.
    virtual ::grpc::Status GetFields(::grpc::ServerContext* context, const ::copybook::transport::GetFieldsRequest* request, ::copybook::transport::GetFieldsResponse* response);
    // Pack named field values into a raw COBOL buffer.
    virtual ::grpc::Status SetFields(::grpc::ServerContext* context, const ::copybook::transport::SetFieldsRequest* request, ::copybook::transport::SetFieldsResponse* response);
    // Get the schema for a specific copybook record.
    virtual ::grpc::Status GetSchema(::grpc::ServerContext* context, const ::copybook::transport::SchemaRequest* request, ::copybook::transport::SchemaResponse* response);
    // List all known copybook schemas.
    virtual ::grpc::Status ListSchemas(::grpc::ServerContext* context, const ::copybook::transport::ListSchemasRequest* request, ::copybook::transport::ListSchemasResponse* response);
    // Convert between raw buffer and JSON/YAML formats.
    virtual ::grpc::Status Convert(::grpc::ServerContext* context, const ::copybook::transport::ConvertRequest* request, ::copybook::transport::ConvertResponse* response);
    // Stream records: client sends a stream of records, server acknowledges each.
    virtual ::grpc::Status StreamRecords(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::copybook::transport::SendResponse, ::copybook::transport::SendRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendRecord() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRecord(::grpc::ServerContext* /*context*/, const ::copybook::transport::SendRequest* /*request*/, ::copybook::transport::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendRecord(::grpc::ServerContext* context, ::copybook::transport::SendRequest* request, ::grpc::ServerAsyncResponseWriter< ::copybook::transport::SendResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFields() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::GetFieldsRequest* /*request*/, ::copybook::transport::GetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFields(::grpc::ServerContext* context, ::copybook::transport::GetFieldsRequest* request, ::grpc::ServerAsyncResponseWriter< ::copybook::transport::GetFieldsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetFields() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_SetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::SetFieldsRequest* /*request*/, ::copybook::transport::SetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetFields(::grpc::ServerContext* context, ::copybook::transport::SetFieldsRequest* request, ::grpc::ServerAsyncResponseWriter< ::copybook::transport::SetFieldsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSchema : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSchema() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetSchema() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSchema(::grpc::ServerContext* /*context*/, const ::copybook::transport::SchemaRequest* /*request*/, ::copybook::transport::SchemaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSchema(::grpc::ServerContext* context, ::copybook::transport::SchemaRequest* request, ::grpc::ServerAsyncResponseWriter< ::copybook::transport::SchemaResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListSchemas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListSchemas() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_ListSchemas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSchemas(::grpc::ServerContext* /*context*/, const ::copybook::transport::ListSchemasRequest* /*request*/, ::copybook::transport::ListSchemasResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListSchemas(::grpc::ServerContext* context, ::copybook::transport::ListSchemasRequest* request, ::grpc::ServerAsyncResponseWriter< ::copybook::transport::ListSchemasResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Convert() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::copybook::transport::ConvertRequest* /*request*/, ::copybook::transport::ConvertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConvert(::grpc::ServerContext* context, ::copybook::transport::ConvertRequest* request, ::grpc::ServerAsyncResponseWriter< ::copybook::transport::ConvertResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamRecords() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_StreamRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::copybook::transport::SendResponse, ::copybook::transport::SendRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamRecords(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::copybook::transport::SendResponse, ::copybook::transport::SendRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(6, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendRecord<WithAsyncMethod_GetFields<WithAsyncMethod_SetFields<WithAsyncMethod_GetSchema<WithAsyncMethod_ListSchemas<WithAsyncMethod_Convert<WithAsyncMethod_StreamRecords<Service > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendRecord() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::copybook::transport::SendRequest* request, ::copybook::transport::SendResponse* response) { return this->SendRecord(context, request, response); }));}
    void SetMessageAllocatorFor_SendRecord(
        ::grpc::MessageAllocator< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRecord(::grpc::ServerContext* /*context*/, const ::copybook::transport::SendRequest* /*request*/, ::copybook::transport::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::copybook::transport::SendRequest* /*request*/, ::copybook::transport::SendResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetFields() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::copybook::transport::GetFieldsRequest, ::copybook::transport::GetFieldsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::copybook::transport::GetFieldsRequest* request, ::copybook::transport::GetFieldsResponse* response) { return this->GetFields(context, request, response); }));}
    void SetMessageAllocatorFor_GetFields(
        ::grpc::MessageAllocator< ::copybook::transport::GetFieldsRequest, ::copybook::transport::GetFieldsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::copybook::transport::GetFieldsRequest, ::copybook::transport::GetFieldsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::GetFieldsRequest* /*request*/, ::copybook::transport::GetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFields(
      ::grpc::CallbackServerContext* /*context*/, const ::copybook::transport::GetFieldsRequest* /*request*/, ::copybook::transport::GetFieldsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetFields() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::copybook::transport::SetFieldsRequest, ::copybook::transport::SetFieldsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::copybook::transport::SetFieldsRequest* request, ::copybook::transport::SetFieldsResponse* response) { return this->SetFields(context, request, response); }));}
    void SetMessageAllocatorFor_SetFields(
        ::grpc::MessageAllocator< ::copybook::transport::SetFieldsRequest, ::copybook::transport::SetFieldsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::copybook::transport::SetFieldsRequest, ::copybook::transport::SetFieldsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::SetFieldsRequest* /*request*/, ::copybook::transport::SetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetFields(
      ::grpc::CallbackServerContext* /*context*/, const ::copybook::transport::SetFieldsRequest* /*request*/, ::copybook::transport::SetFieldsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetSchema : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetSchema() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::copybook::transport::SchemaRequest, ::copybook::transport::SchemaResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::copybook::transport::SchemaRequest* request, ::copybook::transport::SchemaResponse* response) { return this->GetSchema(context, request, response); }));}
    void SetMessageAllocatorFor_GetSchema(
        ::grpc::MessageAllocator< ::copybook::transport::SchemaRequest, ::copybook::transport::SchemaResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::copybook::transport::SchemaRequest, ::copybook::transport::SchemaResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetSchema() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSchema(::grpc::ServerContext* /*context*/, const ::copybook::transport::SchemaRequest* /*request*/, ::copybook::transport::SchemaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSchema(
      ::grpc::CallbackServerContext* /*context*/, const ::copybook::transport::SchemaRequest* /*request*/, ::copybook::transport::SchemaResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListSchemas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListSchemas() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::copybook::transport::ListSchemasRequest, ::copybook::transport::ListSchemasResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::copybook::transport::ListSchemasRequest* request, ::copybook::transport::ListSchemasResponse* response) { return this->ListSchemas(context, request, response); }));}
    void SetMessageAllocatorFor_ListSchemas(
        ::grpc::MessageAllocator< ::copybook::transport::ListSchemasRequest, ::copybook::transport::ListSchemasResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::copybook::transport::ListSchemasRequest, ::copybook::transport::ListSchemasResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListSchemas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSchemas(::grpc::ServerContext* /*context*/, const ::copybook::transport::ListSchemasRequest* /*request*/, ::copybook::transport::ListSchemasResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListSchemas(
      ::grpc::CallbackServerContext* /*context*/, const ::copybook::transport::ListSchemasRequest* /*request*/, ::copybook::transport::ListSchemasResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Convert() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::copybook::transport::ConvertRequest, ::copybook::transport::ConvertResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::copybook::transport::ConvertRequest* request, ::copybook::transport::ConvertResponse* response) { return this->Convert(context, request, response); }));}
    void SetMessageAllocatorFor_Convert(
        ::grpc::MessageAllocator< ::copybook::transport::ConvertRequest, ::copybook::transport::ConvertResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::copybook::transport::ConvertRequest, ::copybook::transport::ConvertResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::copybook::transport::ConvertRequest* /*request*/, ::copybook::transport::ConvertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Convert(
      ::grpc::CallbackServerContext* /*context*/, const ::copybook::transport::ConvertRequest* /*request*/, ::copybook::transport::ConvertResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamRecords() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackBidiHandler< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamRecords(context); }));
    }
    ~WithCallbackMethod_StreamRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::copybook::transport::SendResponse, ::copybook::transport::SendRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* StreamRecords(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_SendRecord<WithCallbackMethod_GetFields<WithCallbackMethod_SetFields<WithCallbackMethod_GetSchema<WithCallbackMethod_ListSchemas<WithCallbackMethod_Convert<WithCallbackMethod_StreamRecords<Service > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendRecord() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRecord(::grpc::ServerContext* /*context*/, const ::copybook::transport::SendRequest* /*request*/, ::copybook::transport::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFields() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::GetFieldsRequest* /*request*/, ::copybook::transport::GetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetFields() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_SetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::SetFieldsRequest* /*request*/, ::copybook::transport::SetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetSchema : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSchema() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetSchema() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSchema(::grpc::ServerContext* /*context*/, const ::copybook::transport::SchemaRequest* /*request*/, ::copybook::transport::SchemaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListSchemas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListSchemas() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_ListSchemas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSchemas(::grpc::ServerContext* /*context*/, const ::copybook::transport::ListSchemasRequest* /*request*/, ::copybook::transport::ListSchemasResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Convert() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::copybook::transport::ConvertRequest* /*request*/, ::copybook::transport::ConvertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamRecords() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_StreamRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::copybook::transport::SendResponse, ::copybook::transport::SendRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendRecord() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRecord(::grpc::ServerContext* /*context*/, const ::copybook::transport::SendRequest* /*request*/, ::copybook::transport::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendRecord(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFields() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::GetFieldsRequest* /*request*/, ::copybook::transport::GetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFields(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetFields() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_SetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::SetFieldsRequest* /*request*/, ::copybook::transport::SetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetFields(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSchema : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSchema() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetSchema() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSchema(::grpc::ServerContext* /*context*/, const ::copybook::transport::SchemaRequest* /*request*/, ::copybook::transport::SchemaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSchema(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListSchemas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListSchemas() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_ListSchemas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSchemas(::grpc::ServerContext* /*context*/, const ::copybook::transport::ListSchemasRequest* /*request*/, ::copybook::transport::ListSchemasResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListSchemas(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Convert() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::copybook::transport::ConvertRequest* /*request*/, ::copybook::transport::ConvertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestConvert(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamRecords() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_StreamRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::copybook::transport::SendResponse, ::copybook::transport::SendRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamRecords(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(6, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendRecord() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendRecord(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendRecord(::grpc::ServerContext* /*context*/, const ::copybook::transport::SendRequest* /*request*/, ::copybook::transport::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendRecord(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetFields() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetFields(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::GetFieldsRequest* /*request*/, ::copybook::transport::GetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFields(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetFields() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetFields(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::SetFieldsRequest* /*request*/, ::copybook::transport::SetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetFields(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetSchema : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetSchema() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSchema(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetSchema() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSchema(::grpc::ServerContext* /*context*/, const ::copybook::transport::SchemaRequest* /*request*/, ::copybook::transport::SchemaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSchema(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListSchemas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListSchemas() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListSchemas(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListSchemas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListSchemas(::grpc::ServerContext* /*context*/, const ::copybook::transport::ListSchemasRequest* /*request*/, ::copybook::transport::ListSchemasResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListSchemas(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Convert() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Convert(context, request, response); }));
    }
    ~WithRawCallbackMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::copybook::transport::ConvertRequest* /*request*/, ::copybook::transport::ConvertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Convert(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamRecords : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamRecords() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamRecords(context); }));
    }
    ~WithRawCallbackMethod_StreamRecords() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamRecords(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::copybook::transport::SendResponse, ::copybook::transport::SendRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamRecords(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendRecord : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendRecord() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* streamer) {
                       return this->StreamedSendRecord(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendRecord() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendRecord(::grpc::ServerContext* /*context*/, const ::copybook::transport::SendRequest* /*request*/, ::copybook::transport::SendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendRecord(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::copybook::transport::SendRequest,::copybook::transport::SendResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetFields() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::copybook::transport::GetFieldsRequest, ::copybook::transport::GetFieldsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::copybook::transport::GetFieldsRequest, ::copybook::transport::GetFieldsResponse>* streamer) {
                       return this->StreamedGetFields(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::GetFieldsRequest* /*request*/, ::copybook::transport::GetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetFields(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::copybook::transport::GetFieldsRequest,::copybook::transport::GetFieldsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetFields : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetFields() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::copybook::transport::SetFieldsRequest, ::copybook::transport::SetFieldsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::copybook::transport::SetFieldsRequest, ::copybook::transport::SetFieldsResponse>* streamer) {
                       return this->StreamedSetFields(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetFields() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetFields(::grpc::ServerContext* /*context*/, const ::copybook::transport::SetFieldsRequest* /*request*/, ::copybook::transport::SetFieldsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetFields(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::copybook::transport::SetFieldsRequest,::copybook::transport::SetFieldsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSchema : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSchema() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::copybook::transport::SchemaRequest, ::copybook::transport::SchemaResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::copybook::transport::SchemaRequest, ::copybook::transport::SchemaResponse>* streamer) {
                       return this->StreamedGetSchema(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSchema() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSchema(::grpc::ServerContext* /*context*/, const ::copybook::transport::SchemaRequest* /*request*/, ::copybook::transport::SchemaResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSchema(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::copybook::transport::SchemaRequest,::copybook::transport::SchemaResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListSchemas : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListSchemas() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::copybook::transport::ListSchemasRequest, ::copybook::transport::ListSchemasResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::copybook::transport::ListSchemasRequest, ::copybook::transport::ListSchemasResponse>* streamer) {
                       return this->StreamedListSchemas(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListSchemas() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListSchemas(::grpc::ServerContext* /*context*/, const ::copybook::transport::ListSchemasRequest* /*request*/, ::copybook::transport::ListSchemasResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListSchemas(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::copybook::transport::ListSchemasRequest,::copybook::transport::ListSchemasResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Convert : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Convert() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::copybook::transport::ConvertRequest, ::copybook::transport::ConvertResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::copybook::transport::ConvertRequest, ::copybook::transport::ConvertResponse>* streamer) {
                       return this->StreamedConvert(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Convert() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Convert(::grpc::ServerContext* /*context*/, const ::copybook::transport::ConvertRequest* /*request*/, ::copybook::transport::ConvertResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedConvert(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::copybook::transport::ConvertRequest,::copybook::transport::ConvertResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendRecord<WithStreamedUnaryMethod_GetFields<WithStreamedUnaryMethod_SetFields<WithStreamedUnaryMethod_GetSchema<WithStreamedUnaryMethod_ListSchemas<WithStreamedUnaryMethod_Convert<Service > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendRecord<WithStreamedUnaryMethod_GetFields<WithStreamedUnaryMethod_SetFields<WithStreamedUnaryMethod_GetSchema<WithStreamedUnaryMethod_ListSchemas<WithStreamedUnaryMethod_Convert<Service > > > > > > StreamedService;
};

}  // namespace transport
}  // namespace copybook


#endif  // GRPC_copybook_5fservice_2eproto__INCLUDED
