// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: copybook_service.proto

#include "copybook_service.pb.h"
#include "copybook_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace copybook {
namespace transport {

static const char* CopybookService_method_names[] = {
  "/copybook.transport.CopybookService/SendRecord",
  "/copybook.transport.CopybookService/GetFields",
  "/copybook.transport.CopybookService/SetFields",
  "/copybook.transport.CopybookService/GetSchema",
  "/copybook.transport.CopybookService/ListSchemas",
  "/copybook.transport.CopybookService/Convert",
  "/copybook.transport.CopybookService/StreamRecords",
};

std::unique_ptr< CopybookService::Stub> CopybookService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CopybookService::Stub> stub(new CopybookService::Stub(channel, options));
  return stub;
}

CopybookService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendRecord_(CopybookService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetFields_(CopybookService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetFields_(CopybookService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSchema_(CopybookService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListSchemas_(CopybookService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Convert_(CopybookService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamRecords_(CopybookService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status CopybookService::Stub::SendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::copybook::transport::SendResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendRecord_, context, request, response);
}

void CopybookService::Stub::async::SendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest* request, ::copybook::transport::SendResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRecord_, context, request, response, std::move(f));
}

void CopybookService::Stub::async::SendRecord(::grpc::ClientContext* context, const ::copybook::transport::SendRequest* request, ::copybook::transport::SendResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendRecord_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::SendResponse>* CopybookService::Stub::PrepareAsyncSendRecordRaw(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::copybook::transport::SendResponse, ::copybook::transport::SendRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendRecord_, context, request);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::SendResponse>* CopybookService::Stub::AsyncSendRecordRaw(::grpc::ClientContext* context, const ::copybook::transport::SendRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendRecordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CopybookService::Stub::GetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::copybook::transport::GetFieldsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::copybook::transport::GetFieldsRequest, ::copybook::transport::GetFieldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFields_, context, request, response);
}

void CopybookService::Stub::async::GetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest* request, ::copybook::transport::GetFieldsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::copybook::transport::GetFieldsRequest, ::copybook::transport::GetFieldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFields_, context, request, response, std::move(f));
}

void CopybookService::Stub::async::GetFields(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest* request, ::copybook::transport::GetFieldsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFields_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::GetFieldsResponse>* CopybookService::Stub::PrepareAsyncGetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::copybook::transport::GetFieldsResponse, ::copybook::transport::GetFieldsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFields_, context, request);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::GetFieldsResponse>* CopybookService::Stub::AsyncGetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::GetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFieldsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CopybookService::Stub::SetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::copybook::transport::SetFieldsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::copybook::transport::SetFieldsRequest, ::copybook::transport::SetFieldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetFields_, context, request, response);
}

void CopybookService::Stub::async::SetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest* request, ::copybook::transport::SetFieldsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::copybook::transport::SetFieldsRequest, ::copybook::transport::SetFieldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetFields_, context, request, response, std::move(f));
}

void CopybookService::Stub::async::SetFields(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest* request, ::copybook::transport::SetFieldsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetFields_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::SetFieldsResponse>* CopybookService::Stub::PrepareAsyncSetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::copybook::transport::SetFieldsResponse, ::copybook::transport::SetFieldsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetFields_, context, request);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::SetFieldsResponse>* CopybookService::Stub::AsyncSetFieldsRaw(::grpc::ClientContext* context, const ::copybook::transport::SetFieldsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetFieldsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CopybookService::Stub::GetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::copybook::transport::SchemaResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::copybook::transport::SchemaRequest, ::copybook::transport::SchemaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSchema_, context, request, response);
}

void CopybookService::Stub::async::GetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest* request, ::copybook::transport::SchemaResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::copybook::transport::SchemaRequest, ::copybook::transport::SchemaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSchema_, context, request, response, std::move(f));
}

void CopybookService::Stub::async::GetSchema(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest* request, ::copybook::transport::SchemaResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSchema_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::SchemaResponse>* CopybookService::Stub::PrepareAsyncGetSchemaRaw(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::copybook::transport::SchemaResponse, ::copybook::transport::SchemaRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSchema_, context, request);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::SchemaResponse>* CopybookService::Stub::AsyncGetSchemaRaw(::grpc::ClientContext* context, const ::copybook::transport::SchemaRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSchemaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CopybookService::Stub::ListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::copybook::transport::ListSchemasResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::copybook::transport::ListSchemasRequest, ::copybook::transport::ListSchemasResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListSchemas_, context, request, response);
}

void CopybookService::Stub::async::ListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest* request, ::copybook::transport::ListSchemasResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::copybook::transport::ListSchemasRequest, ::copybook::transport::ListSchemasResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSchemas_, context, request, response, std::move(f));
}

void CopybookService::Stub::async::ListSchemas(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest* request, ::copybook::transport::ListSchemasResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListSchemas_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::ListSchemasResponse>* CopybookService::Stub::PrepareAsyncListSchemasRaw(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::copybook::transport::ListSchemasResponse, ::copybook::transport::ListSchemasRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListSchemas_, context, request);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::ListSchemasResponse>* CopybookService::Stub::AsyncListSchemasRaw(::grpc::ClientContext* context, const ::copybook::transport::ListSchemasRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListSchemasRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CopybookService::Stub::Convert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::copybook::transport::ConvertResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::copybook::transport::ConvertRequest, ::copybook::transport::ConvertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Convert_, context, request, response);
}

void CopybookService::Stub::async::Convert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest* request, ::copybook::transport::ConvertResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::copybook::transport::ConvertRequest, ::copybook::transport::ConvertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Convert_, context, request, response, std::move(f));
}

void CopybookService::Stub::async::Convert(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest* request, ::copybook::transport::ConvertResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Convert_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::ConvertResponse>* CopybookService::Stub::PrepareAsyncConvertRaw(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::copybook::transport::ConvertResponse, ::copybook::transport::ConvertRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Convert_, context, request);
}

::grpc::ClientAsyncResponseReader< ::copybook::transport::ConvertResponse>* CopybookService::Stub::AsyncConvertRaw(::grpc::ClientContext* context, const ::copybook::transport::ConvertRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConvertRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* CopybookService::Stub::StreamRecordsRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>::Create(channel_.get(), rpcmethod_StreamRecords_, context);
}

void CopybookService::Stub::async::StreamRecords(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::copybook::transport::SendRequest,::copybook::transport::SendResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::copybook::transport::SendRequest,::copybook::transport::SendResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamRecords_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* CopybookService::Stub::AsyncStreamRecordsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>::Create(channel_.get(), cq, rpcmethod_StreamRecords_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>* CopybookService::Stub::PrepareAsyncStreamRecordsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>::Create(channel_.get(), cq, rpcmethod_StreamRecords_, context, false, nullptr);
}

CopybookService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CopybookService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CopybookService::Service, ::copybook::transport::SendRequest, ::copybook::transport::SendResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CopybookService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::copybook::transport::SendRequest* req,
             ::copybook::transport::SendResponse* resp) {
               return service->SendRecord(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CopybookService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CopybookService::Service, ::copybook::transport::GetFieldsRequest, ::copybook::transport::GetFieldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CopybookService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::copybook::transport::GetFieldsRequest* req,
             ::copybook::transport::GetFieldsResponse* resp) {
               return service->GetFields(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CopybookService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CopybookService::Service, ::copybook::transport::SetFieldsRequest, ::copybook::transport::SetFieldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CopybookService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::copybook::transport::SetFieldsRequest* req,
             ::copybook::transport::SetFieldsResponse* resp) {
               return service->SetFields(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CopybookService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CopybookService::Service, ::copybook::transport::SchemaRequest, ::copybook::transport::SchemaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CopybookService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::copybook::transport::SchemaRequest* req,
             ::copybook::transport::SchemaResponse* resp) {
               return service->GetSchema(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CopybookService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CopybookService::Service, ::copybook::transport::ListSchemasRequest, ::copybook::transport::ListSchemasResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CopybookService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::copybook::transport::ListSchemasRequest* req,
             ::copybook::transport::ListSchemasResponse* resp) {
               return service->ListSchemas(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CopybookService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CopybookService::Service, ::copybook::transport::ConvertRequest, ::copybook::transport::ConvertResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CopybookService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::copybook::transport::ConvertRequest* req,
             ::copybook::transport::ConvertResponse* resp) {
               return service->Convert(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CopybookService_method_names[6],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< CopybookService::Service, ::copybook::transport::SendRequest, ::copybook::transport::SendResponse>(
          [](CopybookService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::copybook::transport::SendResponse,
             ::copybook::transport::SendRequest>* stream) {
               return service->StreamRecords(ctx, stream);
             }, this)));
}

CopybookService::Service::~Service() {
}

::grpc::Status CopybookService::Service::SendRecord(::grpc::ServerContext* context, const ::copybook::transport::SendRequest* request, ::copybook::transport::SendResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CopybookService::Service::GetFields(::grpc::ServerContext* context, const ::copybook::transport::GetFieldsRequest* request, ::copybook::transport::GetFieldsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CopybookService::Service::SetFields(::grpc::ServerContext* context, const ::copybook::transport::SetFieldsRequest* request, ::copybook::transport::SetFieldsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CopybookService::Service::GetSchema(::grpc::ServerContext* context, const ::copybook::transport::SchemaRequest* request, ::copybook::transport::SchemaResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CopybookService::Service::ListSchemas(::grpc::ServerContext* context, const ::copybook::transport::ListSchemasRequest* request, ::copybook::transport::ListSchemasResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CopybookService::Service::Convert(::grpc::ServerContext* context, const ::copybook::transport::ConvertRequest* request, ::copybook::transport::ConvertResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CopybookService::Service::StreamRecords(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::copybook::transport::SendResponse, ::copybook::transport::SendRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace copybook
}  // namespace transport

